const words = [
    { english: "the", polish: "ten" },
    { english: "be", polish: "być" },
    { english: "and", polish: "i" },
    { english: "of", polish: "z" },
    { english: "a", polish: "jeden" },
    { english: "in", polish: "w" },
    { english: "to", polish: "do" },
    { english: "have", polish: "mieć" },
    { english: "it", polish: "to" },
    { english: "you", polish: "ty" },
    { english: "that", polish: "że" },
    { english: "he", polish: "on" },
    { english: "was", polish: "był" },
    { english: "for", polish: "dla" },
    { english: "on", polish: "na" },
    { english: "are", polish: "są" },
    { english: "as", polish: "jak" },
    { english: "with", polish: "z" },
    { english: "his", polish: "jego" },
    { english: "they", polish: "oni" },
    { english: "at", polish: "w" },
    { english: "be", polish: "być" },
    { english: "this", polish: "ten" },
    { english: "from", polish: "z" },
    { english: "or", polish: "lub" },
    { english: "one", polish: "jeden" },
    { english: "all", polish: "wszystko" },
    { english: "would", polish: "by" },
    { english: "there", polish: "tam" },
    { english: "say", polish: "powiedzieć" },
    { english: "who", polish: "kto" },
    { english: "make", polish: "robić" },
    { english: "when", polish: "kiedy" },
    { english: "can", polish: "móc" },
    { english: "like", polish: "lubić" },
    { english: "time", polish: "czas" },
    { english: "no", polish: "nie" },
    { english: "just", polish: "tylko" },
    { english: "him", polish: "jego" },
    { english: "know", polish: "wiedzieć" },
    { english: "take", polish: "brać" },
    { english: "people", polish: "ludzie" },
    { english: "into", polish: "do" },
    { english: "year", polish: "rok" },
    { english: "your", polish: "twój" },
    { english: "good", polish: "dobry" },
    { english: "some", polish: "niektóre" },
    { english: "could", polish: "mógł" },
    { english: "them", polish: "ich" },
    { english: "see", polish: "widzieć" },
    { english: "other", polish: "inny" },
    { english: "than", polish: "niż" },
    { english: "then", polish: "potem" },
    { english: "now", polish: "teraz" },
    { english: "look", polish: "patrzeć" },
    { english: "only", polish: "tylko" },
    { english: "come", polish: "przyjść" },
    { english: "its", polish: "jego" },
    { english: "over", polish: "nad" },
    { english: "think", polish: "myśleć" },
    { english: "also", polish: "też" },
    { english: "back", polish: "z powrotem" },
    { english: "after", polish: "po" },
    { english: "use", polish: "używać" },
    { english: "two", polish: "dwa" },
    { english: "how", polish: "jak" },
    { english: "our", polish: "nasz" },
    { english: "work", polish: "praca" },
    { english: "first", polish: "pierwszy" },
    { english: "well", polish: "dobrze" },
    { english: "way", polish: "sposób" },
    { english: "even", polish: "nawet" },
    { english: "new", polish: "nowy" },
    { english: "want", polish: "chcieć" },
    { english: "because", polish: "ponieważ" },
    { english: "any", polish: "jakikolwiek" },
    { english: "these", polish: "te" },
    { english: "give", polish: "dawać" },
    { english: "day", polish: "dzień" },
    { english: "most", polish: "najwięcej" },
    { english: "us", polish: "nas" },
    { english: "am", polish: "jestem" },
    { english: "such", polish: "taki" },
    { english: "no", polish: "żaden" },
    { english: "say", polish: "powiedzieć" },
    { english: "might", polish: "móc" },
    { english: "find", polish: "znaleźć" },
    { english: "thing", polish: "rzecz" },
    { english: "tell", polish: "powiedzieć" },
    { english: "see", polish: "widzieć" },
    { english: "place", polish: "miejsce" },
    { english: "such", polish: "taki" },
    { english: "life", polish: "życie" },
    { english: "after", polish: "po" },
    { english: "call", polish: "dzwonić" },
    { english: "most", polish: "najwięcej" },
    { english: "over", polish: "nad" },
    { english: "right", polish: "prawo" },
    { english: "always", polish: "zawsze" },
    { english: "another", polish: "kolejny" },
    { english: "three", polish: "trzy" },
    { english: "own", polish: "własny" },
    { english: "between", polish: "pomiędzy" },
    { english: "need", polish: "potrzebować" },
    { english: "feel", polish: "czuć" },
    { english: "high", polish: "wysoki" },
    { english: "something", polish: "coś" },
    { english: "every", polish: "każdy" },
    { english: "head", polish: "głowa" },
    { english: "might", polish: "móc" },
    { english: "home", polish: "dom" },
    { english: "back", polish: "z powrotem" },
    { english: "few", polish: "kilku" },
    { english: "another", polish: "kolejny" },
    { english: "through", polish: "przez" },
    { english: "need", polish: "potrzebować" },
    { english: "to", polish: "do" },
    { english: "under", polish: "pod" },
    { english: "stay", polish: "zostać" },
    { english: "help", polish: "pomóc" },
    { english: "long", polish: "długi" },
    { english: "want", polish: "chcieć" },
    { english: "never", polish: "nigdy" },
    { english: "must", polish: "musieć" },
    { english: "while", polish: "podczas" },
    { english: "set", polish: "ustawić" },
    { english: "talk", polish: "rozmawiać" },
    { english: "turn", polish: "obrót" },
    { english: "keep", polish: "utrzymać" },
    { english: "always", polish: "zawsze" },
    { english: "leave", polish: "opuścić" },
    { english: "something", polish: "coś" },
    { english: "try", polish: "spróbować" },
    { english: "move", polish: "ruch" },
    { english: "together", polish: "razem" },
    { english: "begin", polish: "zacząć" },
    { english: "face", polish: "twarz" },
    { english: "both", polish: "oba" },
    { english: "home", polish: "dom" },
    { english: "end", polish: "koniec" },
    { english: "course", polish: "kurs" },
    { english: "next", polish: "następny" },
    { english: "believe", polish: "wierzyć" },
    { english: "only", polish: "tylko" },
    { english: "ask", polish: "pytać" },
    { english: "always", polish: "zawsze" },
    { english: "change", polish: "zmiana" },
    { english: "point", polish: "punkt" },
    { english: "seem", polish: "wydawać się" },
    { english: "start", polish: "zacząć" },
    { english: "talk", polish: "rozmawiać" },
    { english: "feel", polish: "czuć" },
    { english: "public", polish: "publiczny" },
    { english: "read", polish: "czytać" },
    { english: "stop", polish: "stop" },
    { english: "every", polish: "każdy" },
    { english: "hold", polish: "trzymać" },
    { english: "turn", polish: "obrót" },
    { english: "second", polish: "drugi" },
    { english: "study", polish: "uczyć się" },
    { english: "left", polish: "lewy" },
    { english: "write", polish: "pisać" },
    { english: "close", polish: "blisko" },
    { english: "course", polish: "kurs" },
    { english: "heard", polish: "słyszeć" },
    { english: "door", polish: "drzwi" },
    { english: "good", polish: "dobry" },
    { english: "right", polish: "prawo" },
    { english: "hard", polish: "ciężki" },
    { english: "big", polish: "duży" },
    { english: "small", polish: "mały" },
    { english: "last", polish: "ostatni" },
    { english: "next", polish: "następny" },
    { english: "important", polish: "ważny" },
    { english: "long", polish: "długi" },
    { english: "try", polish: "spróbować" },
    { english: "work", polish: "praca" },
    { english: "sure", polish: "pewien" },
    { english: "important", polish: "ważny" },
    { english: "line", polish: "linia" },
    { english: "play", polish: "grać" },
    { english: "follow", polish: "śledzić" },
    { english: "stay", polish: "zostać" },
    { english: "present", polish: "prezent" },
    { english: "keep", polish: "utrzymać" },
    { english: "go", polish: "iść" },
    { english: "give", polish: "dawać" },
    { english: "make", polish: "robić" },
    { english: "work", polish: "praca" },
    { english: "home", polish: "dom" },
    { english: "place", polish: "miejsce" },
    { english: "big", polish: "duży" },
    { english: "long", polish: "długi" },
    { english: "different", polish: "inny" },
    { english: "often", polish: "często" },
    { english: "few", polish: "kilku" },
    { english: "hard", polish: "ciężki" },
    { english: "kind", polish: "miły" },
    { english: "kind", polish: "rodzaj" },
    { english: "really", polish: "naprawdę" },
    { english: "nothing", polish: "nic" },
    { english: "someone", polish: "ktoś" },
    { english: "everything", polish: "wszystko" },
    { english: "everyone", polish: "wszyscy" },
    { english: "someone", polish: "ktoś" },
    { english: "something", polish: "coś" },
    { english: "anyone", polish: "ktokolwiek" },
    { english: "anything", polish: "cokolwiek" },
    { english: "without", polish: "bez" },
    { english: "against", polish: "przeciwko" },
    { english: "under", polish: "pod" },
    { english: "above", polish: "ponad" },
    { english: "within", polish: "w" },
    { english: "among", polish: "wśród" },
    { english: "across", polish: "przez" },
    { english: "toward", polish: "w kierunku" },
    { english: "during", polish: "podczas" },
    { english: "between", polish: "pomiędzy" },
    { english: "except", polish: "oprócz" },
    { english: "near", polish: "blisko" },
    { english: "outside", polish: "na zewnątrz" },
    { english: "inside", polish: "wewnątrz" },
    { english: "above", polish: "powyżej" },
    { english: "below", polish: "poniżej" },
    { english: "throughout", polish: "przez" },
    { english: "against", polish: "przeciw" },
    { english: "before", polish: "przed" },
    { english: "after", polish: "po" },
    { english: "until", polish: "aż" },
    { english: "despite", polish: "pomimo" },
    { english: "along", polish: "wzdłuż" },
    { english: "towards", polish: "w kierunku" },
    { english: "about", polish: "o" },
    { english: "after", polish: "po" },
    { english: "until", polish: "do" },
    { english: "before", polish: "przed" },
    { english: "within", polish: "w" },
    { english: "beside", polish: "obok" },
    { english: "like", polish: "jak" },
    { english: "as", polish: "jak" },
    { english: "whether", polish: "czy" },
    { english: "instead", polish: "zamiast" },
    { english: "unless", polish: "chyba że" },
    { english: "provided", polish: "pod warunkiem" },
    { english: "while", polish: "podczas" },
    { english: "since", polish: "od" },
    { english: "until", polish: "aż" },
    { english: "whether", polish: "czy" },
    { english: "though", polish: "choć" },
    { english: "but", polish: "ale" },
    { english: "and", polish: "i" },
    { english: "for", polish: "dla" },
    { english: "nor", polish: "ani" },
    { english: "so", polish: "więc" },
    { english: "either", polish: "albo" },
    { english: "neither", polish: "żaden" },
    { english: "whether", polish: "czy" },
    { english: "rather", polish: "raczej" },
    { english: "while", polish: "podczas" },
    { english: "however", polish: "jednak" },
    { english: "besides", polish: "oprócz" },
    { english: "except", polish: "oprócz" },
    { english: "where", polish: "gdzie" },
    { english: "why", polish: "dlaczego" },
    { english: "who", polish: "kto" },
    { english: "what", polish: "co" },
    { english: "when", polish: "kiedy" },
    { english: "which", polish: "który" },
    { english: "that", polish: "to" },
    { english: "how", polish: "jak" },
    { english: "whose", polish: "czyj" },
    { english: "whom", polish: "kogo" },
    { english: "anybody", polish: "ktokolwiek" },
    { english: "somebody", polish: "ktoś" },
    { english: "everybody", polish: "wszyscy" },
    { english: "nobody", polish: "nikt" },
    { english: "each", polish: "każdy" },
    { english: "neither", polish: "żaden" },
    { english: "either", polish: "którykolwiek" },
    { english: "any", polish: "jakikolwiek" },
    { english: "some", polish: "niektóre" },
    { english: "no", polish: "żaden" },
    { english: "all", polish: "wszystko" },
    { english: "few", polish: "niewiele" },
    { english: "many", polish: "wiele" },
    { english: "much", polish: "dużo" },
    { english: "less", polish: "mniej" },
    { english: "more", polish: "więcej" },
    { english: "most", polish: "najwięcej" },
    { english: "fewest", polish: "najmniej" },
    { english: "each", polish: "każdy" },
    { english: "either", polish: "którykolwiek" },
    { english: "neither", polish: "żaden" },
    { english: "any", polish: "jakikolwiek" },
    { english: "some", polish: "niektóre" },
    { english: "none", polish: "żaden" },
    { english: "all", polish: "wszystko" },
    { english: "most", polish: "najwięcej" },
    { english: "many", polish: "wiele" },
    { english: "few", polish: "niewiele" },
    { english: "little", polish: "mało" },
    { english: "lot", polish: "dużo" },
    { english: "various", polish: "różne" },
    { english: "multiple", polish: "wielokrotny" },
    { english: "each", polish: "każdy" },
    { english: "either", polish: "którykolwiek" },
    { english: "neither", polish: "żaden" },
    { english: "none", polish: "żaden" },
    { english: "whole", polish: "cały" },
    { english: "most", polish: "najwięcej" },
    { english: "least", polish: "najmniej" },
    { english: "more", polish: "więcej" },
    { english: "less", polish: "mniej" },
    { english: "all", polish: "wszystko" },
    { english: "any", polish: "jakikolwiek" },
    { english: "some", polish: "niektóre" },
    { english: "each", polish: "każdy" },
    { english: "every", polish: "każdy" },
    { english: "either", polish: "albo" },
    { english: "neither", polish: "ani" },
    { english: "a few", polish: "kilku" },
    { english: "a lot", polish: "dużo" },
    { english: "many", polish: "wiele" },
    { english: "few", polish: "niewiele" },
    { english: "less", polish: "mniej" },
    { english: "most", polish: "najwięcej" },
    { english: "less", polish: "mniej" },
    { english: "more", polish: "więcej" },
    { english: "no", polish: "żaden" },
    { english: "some", polish: "niektóre" },
    { english: "any", polish: "jakikolwiek" },
    { english: "none", polish: "żaden" },
    { english: "each", polish: "każdy" },
    { english: "few", polish: "niewiele" },
    { english: "many", polish: "wiele" },
    { english: "most", polish: "najwięcej" },
    { english: "more", polish: "więcej" },
    { english: "less", polish: "mniej" },
    { english: "least", polish: "najmniej" },
    { english: "whole", polish: "cały" },
    { english: "fewest", polish: "najmniej" },
    { english: "more", polish: "więcej" },
    { english: "several", polish: "kilka" },
    { english: "countless", polish: "niezliczone" },
    { english: "enough", polish: "wystarczająco" },
    { english: "sufficient", polish: "wystarczający" },
    { english: "numerous", polish: "liczne" },
    { english: "many", polish: "wiele" },
    { english: "plenty", polish: "wiele" },
    { english: "a lot of", polish: "dużo" },
    { english: "some", polish: "niektóre" },
    { english: "a little", polish: "trochę" },
    { english: "a few", polish: "kilku" },
    { english: "a couple of", polish: "kilka" },
    { english: "one or two", polish: "jeden lub dwa" },
    { english: "less", polish: "mniej" },
    { english: "more", polish: "więcej" },
    { english: "fewer", polish: "mniej" },
    { english: "several", polish: "kilka" },
    { english: "multiple", polish: "wielokrotny" },
    { english: "both", polish: "oba" },
    { english: "neither", polish: "ani jeden" },
    { english: "either", polish: "jeden z dwóch" },
    { english: "half", polish: "połowa" },
    { english: "whole", polish: "cały" },
    { english: "each", polish: "każdy" },
    { english: "every", polish: "każdy" },
    { english: "most", polish: "najwięcej" },
    { english: "some", polish: "niektóre" },
    { english: "any", polish: "jakikolwiek" },
    { english: "none", polish: "żaden" },
    { english: "all", polish: "wszystko" },
    { english: "the whole", polish: "cały" },
    { english: "the majority", polish: "większość" },
    { english: "the minority", polish: "mniejszość" },
    { english: "countless", polish: "niewielu" },
    { english: "more than", polish: "więcej niż" },
    { english: "less than", polish: "mniej niż" },
    { english: "better than", polish: "lepszy niż" },
    { english: "worse than", polish: "gorszy niż" },
    { english: "the least", polish: "najmniej" },
    { english: "the most", polish: "najwięcej" },
    { english: "the best", polish: "najlepszy" },
    { english: "the worst", polish: "najgorszy" },
    { english: "as much as", polish: "tak dużo jak" },
    { english: "as little as", polish: "tak mało jak" },
    { english: "just as much as", polish: "dokładnie tyle samo" },
    { english: "as many as", polish: "tak wiele jak" },
    { english: "in as many ways as", polish: "na tak wiele sposobów jak" },
    { english: "more and more", polish: "coraz więcej" },
    { english: "less and less", polish: "coraz mniej" },
    { english: "more and more", polish: "coraz więcej" },
    { english: "fewer and fewer", polish: "coraz mniej" },
    { english: "the same", polish: "to samo" },
    { english: "the other", polish: "drugi" },
    { english: "another", polish: "inny" },
    { english: "each", polish: "każdy" },
    { english: "every", polish: "każdy" },
    { english: "all", polish: "wszystko" },
    { english: "some", polish: "niektóre" },
    { english: "any", polish: "jakikolwiek" },
    { english: "no", polish: "żaden" },
    { english: "many", polish: "wiele" },
    { english: "few", polish: "niewiele" },
    { english: "a few", polish: "kilku" },
    { english: "a couple of", polish: "kilka" },
    { english: "some", polish: "niektóre" },
    { english: "all", polish: "wszystko" },
    { english: "each", polish: "każdy" },
    { english: "every", polish: "każdy" },
    { english: "most", polish: "najwięcej" },
    { english: "few", polish: "niewiele" },
    { english: "many", polish: "wiele" },
    { english: "some", polish: "niektóre" },
    { english: "any", polish: "jakikolwiek" },
    { english: "none", polish: "żaden" },
    { english: "the majority", polish: "większość" },
    { english: "the minority", polish: "mniejszość" },
    { english: "a little", polish: "trochę" },
    { english: "a lot", polish: "dużo" },
    { english: "enough", polish: "wystarczająco" },
    { english: "more", polish: "więcej" },
    { english: "less", polish: "mniej" },
    { english: "no", polish: "żaden" },
    { english: "some", polish: "niektóre" },
    { english: "any", polish: "jakikolwiek" },
    { english: "none", polish: "żaden" },
    { english: "both", polish: "oba" },
    { english: "neither", polish: "ani" },
    { english: "either", polish: "jeden z dwóch" },
    { english: "all", polish: "wszystko" },
    { english: "many", polish: "wiele" },
    { english: "few", polish: "niewiele" },
    { english: "a few", polish: "kilku" },
    { english: "the same", polish: "to samo" },
    { english: "the other", polish: "inny" },
    { english: "another", polish: "inny" },
    { english: "one", polish: "jeden" },
    { english: "two", polish: "dwa" },
    { english: "three", polish: "trzy" },
    { english: "four", polish: "cztery" },
    { english: "five", polish: "pięć" },
    { english: "six", polish: "sześć" },
    { english: "seven", polish: "siedem" },
    { english: "eight", polish: "osiem" },
    { english: "nine", polish: "dziewięć" },
    { english: "ten", polish: "dziesięć" },
    { english: "eleven", polish: "jedenaście" },
    { english: "twelve", polish: "dwanaście" },
    { english: "thirteen", polish: "trzynaście" },
    { english: "fourteen", polish: "czternaście" },
    { english: "fifteen", polish: "piętnaście" },
    { english: "sixteen", polish: "szesnaście" },
    { english: "seventeen", polish: "siedemnaście" },
    { english: "eighteen", polish: "osiemnaście" },
    { english: "nineteen", polish: "dziewiętnaście" },
    { english: "twenty", polish: "dwadzieścia" },
    { english: "thirty", polish: "trzydzieści" },
    { english: "forty", polish: "czterdzieści" },
    { english: "fifty", polish: "pięćdziesiąt" },
    { english: "sixty", polish: "sześćdziesiąt" },
    { english: "seventy", polish: "siedemdziesiąt" },
    { english: "eighty", polish: "osiemdziesiąt" },
    { english: "ninety", polish: "dziewięćdziesiąt" },
    { english: "hundred", polish: "sto" },
    { english: "thousand", polish: "tysiąc" },
    { english: "million", polish: "milion" },
    { english: "billion", polish: "miliard" },
    { english: "first", polish: "pierwszy" },
    { english: "second", polish: "drugi" },
    { english: "third", polish: "trzeci" },
    { english: "fourth", polish: "czwarty" },
    { english: "fifth", polish: "piąty" },
    { english: "sixth", polish: "szósty" },
    { english: "seventh", polish: "siódmy" },
    { english: "eighth", polish: "ósmy" },
    { english: "ninth", polish: "dziewiąty" },
    { english: "tenth", polish: "dziesiąty" },
    { english: "twentieth", polish: "dwudziesty" },
    { english: "thirtieth", polish: "trzydziesty" },
    { english: "fortieth", polish: "czterdziesty" },
    { english: "fiftieth", polish: "pięćdziesiąty" },
    { english: "sixtieth", polish: "sześćdziesiąty" },
    { english: "seventieth", polish: "siedemdziesiąty" },
    { english: "eightieth", polish: "osiemdziesiąty" },
    { english: "ninetieth", polish: "dziewięćdziesiąty" },
    { english: "hundredth", polish: "setny" },
    { english: "thousandth", polish: "tysięczny" },
    { english: "millionth", polish: "milionowy" },
    { english: "billionth", polish: "miliardowy" },
    { english: "the first", polish: "pierwszy" },
    { english: "the second", polish: "drugi" },
    { english: "the third", polish: "trzeci" },
    { english: "the fourth", polish: "czwarty" },
    { english: "the fifth", polish: "piąty" },
    { english: "the sixth", polish: "szósty" },
    { english: "the seventh", polish: "siódmy" },
    { english: "the eighth", polish: "ósmy" },
    { english: "the ninth", polish: "dziewiąty" },
    { english: "the tenth", polish: "dziesiąty" },
    { english: "the twentieth", polish: "dwudziesty" },
    { english: "the thirtieth", polish: "trzydziesty" },
    { english: "the fortieth", polish: "czterdziesty" },
    { english: "the fiftieth", polish: "pięćdziesiąty" },
    { english: "the sixtieth", polish: "sześćdziesiąty" },
    { english: "the seventieth", polish: "siedemdziesiąty" },
    { english: "the eightieth", polish: "osiemdziesiąty" },
    { english: "the ninetieth", polish: "dziewięćdziesiąty" },
    { english: "the hundredth", polish: "setny" },
    { english: "the thousandth", polish: "tysięczny" },
    { english: "the millionth", polish: "milionowy" },
    { english: "the billionth", polish: "miliardowy" },
    { english: "and", polish: "i" },
    { english: "or", polish: "lub" },
    { english: "but", polish: "ale" },
    { english: "for", polish: "dla" },
    { english: "nor", polish: "ani" },
    { english: "so", polish: "więc" },
    { english: "either", polish: "albo" },
    { english: "neither", polish: "ani" },
    { english: "yet", polish: "jeszcze" },
    { english: "also", polish: "również" },
    { english: "too", polish: "też" },
    { english: "as well", polish: "też" },
    { english: "in addition", polish: "w dodatku" },
    { english: "on the other hand", polish: "z drugiej strony" },
    { english: "otherwise", polish: "w przeciwnym razie" },
    { english: "besides", polish: "oprócz" },
    { english: "however", polish: "jednak" },
    { english: "though", polish: "jednak" },
    { english: "although", polish: "chociaż" },
    { english: "even though", polish: "nawet jeśli" },
    { english: "while", polish: "podczas gdy" },
    { english: "whereas", polish: "gdzie" },
    { english: "in contrast", polish: "w przeciwieństwie" },
    { english: "similarly", polish: "podobnie" },
    { english: "likewise", polish: "podobnie" },
    { english: "as a result", polish: "w wyniku" },
    { english: "thus", polish: "tak" },
    { english: "therefore", polish: "dlatego" },
    { english: "because", polish: "ponieważ" },
    { english: "since", polish: "ponieważ" },
   { english: "for example", polish: "na przykład" },
    { english: "for instance", polish: "na przykład" },
    { english: "namely", polish: "to jest" },
    { english: "that is", polish: "to znaczy" },
    { english: "in other words", polish: "innymi słowy" },
    { english: "in summary", polish: "podsumowując" },
    { english: "to sum up", polish: "podsumowując" },
    { english: "in conclusion", polish: "w konkluzji" },
    { english: "in brief", polish: "w skrócie" },
    { english: "overall", polish: "ogólnie" },
    { english: "meanwhile", polish: "tymczasem" },
    { english: "after all", polish: "w końcu" },
    { english: "furthermore", polish: "ponadto" },
    { english: "moreover", polish: "ponadto" },
    { english: "instead", polish: "zamiast" },
    { english: "in fact", polish: "w rzeczywistości" },
    { english: "in reality", polish: "w rzeczywistości" },
    { english: "as far as", polish: "o ile" },
    { english: "as long as", polish: "tak długo jak" },
    { english: "as soon as", polish: "jak tylko" },
    { english: "if", polish: "jeśli" },
    { english: "unless", polish: "chyba że" },
    { english: "provided that", polish: "pod warunkiem" },
    { english: "even if", polish: "nawet jeśli" },
    { english: "whether", polish: "czy" },
    { english: "once", polish: "jak już" },
    { english: "before", polish: "przed" },
    { english: "after", polish: "po" },
    { english: "during", polish: "podczas" },
    { english: "until", polish: "aż" },
    { english: "as", polish: "jako" },
    { english: "while", polish: "podczas gdy" },
    { english: "when", polish: "kiedy" },
    { english: "where", polish: "gdzie" },
    { english: "while", polish: "podczas gdy" },
    { english: "whenever", polish: "kiedykolwiek" },
    { english: "wherever", polish: "gdziekolwiek" },
    { english: "as if", polish: "jak gdyby" },
    { english: "as though", polish: "jak gdyby" },
    { english: "like", polish: "jak" },
    { english: "such as", polish: "taki jak" },
    { english: "in the same way", polish: "w ten sam sposób" },
    { english: "in a similar way", polish: "w podobny sposób" },
    { english: "in addition to", polish: "oprócz" },
    { english: "along with", polish: "razem z" },
    { english: "together with", polish: "razem z" },
    { english: "apart from", polish: "oprócz" },
    { english: "in spite of", polish: "pomimo" },
    { english: "despite", polish: "pomimo" },
    { english: "regardless of", polish: "niezależnie od" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "in light of", polish: "w świetle" },
    { english: "in terms of", polish: "w zakresie" },
    { english: "with respect to", polish: "w odniesieniu do" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "as far as", polish: "o ile" },
    { english: "as long as", polish: "tak długo jak" },
    { english: "as soon as", polish: "jak tylko" },
    { english: "if", polish: "jeśli" },
    { english: "unless", polish: "chyba że" },
    { english: "provided that", polish: "pod warunkiem" },
    { english: "even if", polish: "nawet jeśli" },
    { english: "whether", polish: "czy" },
    { english: "once", polish: "jak już" },
    { english: "before", polish: "przed" },
    { english: "after", polish: "po" },
    { english: "during", polish: "podczas" },
    { english: "until", polish: "aż" },
    { english: "as", polish: "jako" },
    { english: "while", polish: "podczas gdy" },
    { english: "when", polish: "kiedy" },
    { english: "where", polish: "gdzie" },
    { english: "whenever", polish: "kiedykolwiek" },
    { english: "wherever", polish: "gdziekolwiek" },
    { english: "as if", polish: "jak gdyby" },
    { english: "as though", polish: "jak gdyby" },
    { english: "like", polish: "jak" },
    { english: "such as", polish: "taki jak" },
    { english: "in the same way", polish: "w ten sam sposób" },
    { english: "in a similar way", polish: "w podobny sposób" },
    { english: "in addition to", polish: "oprócz" },
    { english: "along with", polish: "razem z" },
    { english: "together with", polish: "razem z" },
    { english: "apart from", polish: "oprócz" },
    { english: "in spite of", polish: "pomimo" },
    { english: "despite", polish: "pomimo" },
    { english: "regardless of", polish: "niezależnie od" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "in light of", polish: "w świetle" },
    { english: "in terms of", polish: "w zakresie" },
    { english: "with respect to", polish: "w odniesieniu do" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "to", polish: "do" },
    { english: "with", polish: "z" },
    { english: "without", polish: "bez" },
    { english: "against", polish: "przeciw" },
    { english: "about", polish: "o" },
    { english: "for", polish: "dla" },
    { english: "in", polish: "w" },
    { english: "on", polish: "na" },
    { english: "at", polish: "w" },
    { english: "by", polish: "przez" },
    { english: "between", polish: "pomiędzy" },
    { english: "among", polish: "wśród" },
    { english: "over", polish: "nad" },
    { english: "under", polish: "pod" },
    { english: "around", polish: "około" },
    { english: "through", polish: "przez" },
    { english: "into", polish: "do" },
    { english: "from", polish: "z" },
    { english: "to", polish: "do" },
    { english: "until", polish: "aż" },
    { english: "after", polish: "po" },
    { english: "before", polish: "przed" },
    { english: "during", polish: "podczas" },
    { english: "about", polish: "o" },
    { english: "like", polish: "jak" },
    { english: "as", polish: "jako" },
    { english: "such as", polish: "taki jak" },
    { english: "including", polish: "w tym" },
    { english: "not only", polish: "nie tylko" },
    { english: "but also", polish: "ale także" },
    { english: "both... and", polish: "zarówno... jak i" },
    { english: "either... or", polish: "albo... albo" },
    { english: "neither... nor", polish: "ani... ani" },
    { english: "not... but", polish: "nie... ale" },
    { english: "whether... or", polish: "czy... czy" },
    { english: "either... or", polish: "czy... czy" },
    { english: "neither... nor", polish: "ani... ani" },
    { english: "as... as", polish: "tak... jak" },
    { english: "less... than", polish: "mniej... niż" },
    { english: "more... than", polish: "więcej... niż" },
    { english: "the same... as", polish: "tak samo... jak" },
    { english: "the more... the more", polish: "im więcej... tym więcej" },
    { english: "the less... the less", polish: "im mniej... tym mniej" },
    { english: "as many... as", polish: "tak wiele... jak" },
    { english: "at least", polish: "przynajmniej" },
    { english: "at most", polish: "najwyżej" },
    { english: "more or less", polish: "więcej lub mniej" },
    { english: "to some extent", polish: "do pewnego stopnia" },
    { english: "in some way", polish: "w pewien sposób" },
    { english: "to a certain degree", polish: "do pewnego stopnia" },
    { english: "to a large extent", polish: "w dużym stopniu" },
    { english: "in general", polish: "ogólnie" },
    { english: "generally speaking", polish: "mówiąc ogólnie" },
    { english: "on the whole", polish: "ogólnie rzecz biorąc" },
    { english: "in particular", polish: "w szczególności" },
    { english: "especially", polish: "szczególnie" },
    { english: "particularly", polish: "szczególnie" },
    { english: "typically", polish: "typowo" },
    { english: "normally", polish: "normalnie" },
    { english: "usually", polish: "zwykle" },
    { english: "often", polish: "często" },
    { english: "seldom", polish: "rzadko" },
    { english: "rarely", polish: "rzadko" },
    { english: "sometimes", polish: "czasami" },
    { english: "occasionally", polish: "okazjonalnie" },
    { english: "always", polish: "zawsze" },
    { english: "never", polish: "nigdy" },
    { english: "now", polish: "teraz" },
    { english: "then", polish: "potem" },
    { english: "before", polish: "przed" },
    { english: "after", polish: "po" },
    { english: "today", polish: "dzisiaj" },
    { english: "tomorrow", polish: "jutro" },
    { english: "yesterday", polish: "wczoraj" },
    { english: "nowadays", polish: "w dzisiejszych czasach" },
    { english: "soon", polish: "wkrótce" },
    { english: "later", polish: "później" },
    { english: "previously", polish: "wcześniej" },
    { english: "eventually", polish: "ostatecznie" },
    { english: "finally", polish: "w końcu" },
    { english: "currently", polish: "aktualnie" },
    { english: "recently", polish: "niedawno" },
    { english: "previously", polish: "wcześniej" },
    { english: "in the meantime", polish: "w międzyczasie" },
    { english: "at the moment", polish: "w tej chwili" },
    { english: "once upon a time", polish: "dawno, dawno temu" },
    { english: "for a long time", polish: "od długiego czasu" },
    { english: "for a while", polish: "przez chwilę" },
    { english: "at first", polish: "na początku" },
    { english: "initially", polish: "początkowo" },
    { english: "originally", polish: "pierwotnie" },
    { english: "eventually", polish: "ostatecznie" },
    { english: "finally", polish: "na koniec" },
    { english: "all of a sudden", polish: "nagle" },
    { english: "suddenly", polish: "nagle" },
    { english: "in an instant", polish: "w mgnieniu oka" },
    { english: "right now", polish: "w tej chwili" },
    { english: "at present", polish: "aktualnie" },
    { english: "in the future", polish: "w przyszłości" },
    { english: "at some point", polish: "w pewnym momencie" },
    { english: "soon", polish: "wkrótce" },
    { english: "later", polish: "później" },
    { english: "tomorrow", polish: "jutro" },
    { english: "yesterday", polish: "wczoraj" },
    { english: "nowadays", polish: "w dzisiejszych czasach" },
    { english: "in the past", polish: "w przeszłości" },
    { english: "eventually", polish: "ostatecznie" },
    { english: "finally", polish: "na koniec" },
    { english: "next", polish: "następny" },
    { english: "last", polish: "ostatni" },
    { english: "previous", polish: "poprzedni" },
    { english: "following", polish: "następujący" },
    { english: "subsequent", polish: "następny" },
    { english: "simultaneously", polish: "równocześnie" },
    { english: "in the meantime", polish: "w międzyczasie" },
    { english: "afterwards", polish: "później" },
    { english: "earlier", polish: "wcześniej" },
    { english: "now", polish: "teraz" },
    { english: "then", polish: "potem" },
    { english: "before", polish: "przed" },
    { english: "after", polish: "po" },
    { english: "while", polish: "podczas gdy" },
    { english: "at the same time", polish: "jednocześnie" },
    { english: "while", polish: "podczas gdy" },
    { english: "whenever", polish: "kiedykolwiek" },
    { english: "wherever", polish: "gdziekolwiek" },
    { english: "nowhere", polish: "nigdzie" },
    { english: "somewhere", polish: "gdzieś" },
    { english: "anywhere", polish: "gdziekolwiek" },
    { english: "everywhere", polish: "wszędzie" },
    { english: "here", polish: "tutaj" },
    { english: "there", polish: "tam" },
    { english: "above", polish: "ponad" },
    { english: "below", polish: "poniżej" },
    { english: "near", polish: "blisko" },
    { english: "far", polish: "daleko" },
    { english: "inside", polish: "w środku" },
    { english: "outside", polish: "na zewnątrz" },
    { english: "behind", polish: "za" },
    { english: "in front of", polish: "przed" },
    { english: "in back of", polish: "za" },
    { english: "underneath", polish: "pod" },
    { english: "over", polish: "nad" },
    { english: "between", polish: "pomiędzy" },
    { english: "among", polish: "wśród" },
    { english: "throughout", polish: "na całym" },
    { english: "across", polish: "przez" },
    { english: "toward", polish: "w kierunku" },
    { english: "against", polish: "przeciw" },
    { english: "into", polish: "do" },
    { english: "onto", polish: "na" },
    { english: "out of", polish: "poza" },
    { english: "with", polish: "z" },
    { english: "without", polish: "bez" },
    { english: "despite", polish: "pomimo" },
    { english: "regardless of", polish: "bez względu na" },
    { english: "in addition to", polish: "oprócz" },
    { english: "in front of", polish: "przed" },
    { english: "behind", polish: "za" },
    { english: "beneath", polish: "pod" },
    { english: "through", polish: "przez" },
    { english: "towards", polish: "w kierunku" },
    { english: "past", polish: "obok" },
    { english: "along", polish: "wzdłuż" },
    { english: "around", polish: "wokół" },
    { english: "across", polish: "na całym" },
    { english: "past", polish: "obok" },
    { english: "by", polish: "przez" },
    { english: "next to", polish: "obok" },
    { english: "alongside", polish: "obok" },
    { english: "within", polish: "w" },
    { english: "without", polish: "bez" },
    { english: "around", polish: "około" },
    { english: "throughout", polish: "na całym" },
    { english: "at", polish: "w" },
    { english: "in", polish: "w" },
    { english: "on", polish: "na" },
    { english: "to", polish: "do" },
    { english: "with", polish: "z" },
    { english: "against", polish: "przeciw" },
    { english: "towards", polish: "w kierunku" },
    { english: "against", polish: "przeciw" },
    { english: "besides", polish: "oprócz" },
    { english: "beyond", polish: "poza" },
    { english: "through", polish: "przez" },
    { english: "by", polish: "przez" },
    { english: "over", polish: "nad" },
    { english: "under", polish: "pod" },
    { english: "before", polish: "przed" },
    { english: "after", polish: "po" },
    { english: "during", polish: "podczas" },
    { english: "for", polish: "dla" },
    { english: "against", polish: "przeciw" },
    { english: "according to", polish: "zgodnie z" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "in spite of", polish: "pomimo" },
    { english: "despite", polish: "pomimo" },
    { english: "regardless of", polish: "bez względu na" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "in light of", polish: "w świetle" },
    { english: "with respect to", polish: "w odniesieniu do" },
    { english: "in reference to", polish: "w odniesieniu do" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in terms of", polish: "w zakresie" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in case of", polish: "w przypadku" },
    { english: "in the event of", polish: "w przypadku" },
    { english: "under the circumstances", polish: "w danych okolicznościach" },
    { english: "within", polish: "w" },
    { english: "outside", polish: "na zewnątrz" },
    { english: "in the direction of", polish: "w kierunku" },
    { english: "to the extent of", polish: "do stopnia" },
    { english: "as well as", polish: "jak również" },
    { english: "apart from", polish: "oprócz" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "in light of", polish: "w świetle" },
    { english: "in relation to", polish: "w związku z" },
    { english: "according to", polish: "zgodnie z" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "despite", polish: "pomimo" },
    { english: "in spite of", polish: "pomimo" },
    { english: "regardless of", polish: "bez względu na" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in reference to", polish: "w odniesieniu do" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in case of", polish: "w przypadku" },
    { english: "under the circumstances", polish: "w danych okolicznościach" },
    { english: "by means of", polish: "za pomocą" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "in place of", polish: "zamiast" },
    { english: "in exchange for", polish: "w zamian za" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "in the event of", polish: "w przypadku" },
    { english: "in case of", polish: "w przypadku" },
    { english: "in the light of", polish: "w świetle" },
    { english: "in view of", polish: "w obliczu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "on account of", polish: "z powodu" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "in terms of", polish: "w zakresie" },
    { english: "in reference to", polish: "w odniesieniu do" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in light of", polish: "w świetle" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "by way of", polish: "poprzez" },
    { english: "in spite of", polish: "pomimo" },
    { english: "regardless of", polish: "bez względu na" },
    { english: "in addition to", polish: "oprócz" },
    { english: "together with", polish: "razem z" },
    { english: "along with", polish: "razem z" },
    { english: "as well as", polish: "jak również" },
    { english: "apart from", polish: "oprócz" },
    { english: "besides", polish: "oprócz" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in light of", polish: "w świetle" },
    { english: "on the basis of", polish: "na podstawie" },
    { english: "by means of", polish: "za pomocą" },
    { english: "as a consequence of", polish: "w konsekwencji" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "in the aftermath of", polish: "w następstwie" },
    { english: "in the wake of", polish: "w obliczu" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "as per", polish: "zgodnie z" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "according to", polish: "zgodnie z" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "by way of", polish: "poprzez" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in reference to", polish: "w odniesieniu do" },
    { english: "with respect to", polish: "w odniesieniu do" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in terms of", polish: "w zakresie" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in case of", polish: "w przypadku" },
    { english: "on the occasion of", polish: "z okazji" },
    { english: "in honor of", polish: "na cześć" },
    { english: "in recognition of", polish: "w uznaniu" },
    { english: "in memory of", polish: "w pamięci" },
    { english: "in place of", polish: "w miejsce" },
    { english: "on account of", polish: "z powodu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in light of", polish: "w świetle" },
    { english: "in view of", polish: "w obliczu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "because of", polish: "z powodu" },
    { english: "due to", polish: "z powodu" },
    { english: "in the event of", polish: "w przypadku" },
    { english: "in case of", polish: "w przypadku" },
    { english: "on the occasion of", polish: "z okazji" },
    { english: "in memory of", polish: "w pamięci" },
    { english: "in honor of", polish: "na cześć" },
    { english: "in recognition of", polish: "w uznaniu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in view of", polish: "w obliczu" },
    { english: "on account of", polish: "z powodu" },
    { english: "in the light of", polish: "w świetle" },
    { english: "on the occasion of", polish: "z okazji" },
    { english: "in recognition of", polish: "w uznaniu" },
    { english: "in honor of", polish: "na cześć" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "as per", polish: "zgodnie z" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "together with", polish: "razem z" },
    { english: "along with", polish: "razem z" },
    { english: "together with", polish: "razem z" },
    { english: "along with", polish: "razem z" },
    { english: "as well as", polish: "jak również" },
    { english: "in addition to", polish: "oprócz" },
    { english: "besides", polish: "oprócz" },
    { english: "apart from", polish: "oprócz" },
    { english: "by means of", polish: "za pomocą" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "as per", polish: "zgodnie z" },
    { english: "by means of", polish: "za pomocą" },
    { english: "in addition to", polish: "oprócz" },
    { english: "besides", polish: "oprócz" },
    { english: "apart from", polish: "oprócz" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "in the wake of", polish: "w obliczu" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in honor of", polish: "na cześć" },
    { english: "in memory of", polish: "w pamięci" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "by means of", polish: "za pomocą" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "as per", polish: "zgodnie z" },
    { english: "according to", polish: "zgodnie z" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "by way of", polish: "poprzez" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "by means of", polish: "za pomocą" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "together with", polish: "razem z" },
    { english: "along with", polish: "razem z" },
    { english: "as well as", polish: "jak również" },
    { english: "besides", polish: "oprócz" },
    { english: "apart from", polish: "oprócz" },
    { english: "by means of", polish: "za pomocą" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "in recognition of", polish: "w uznaniu" },
    { english: "in honor of", polish: "na cześć" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in the event of", polish: "w przypadku" },
    { english: "on account of", polish: "z powodu" },
    { english: "due to", polish: "z powodu" },
    { english: "because of", polish: "z powodu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in honor of", polish: "na cześć" },
    { english: "in memory of", polish: "w pamięci" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "as per", polish: "zgodnie z" },
    { english: "in line with", polish: "w zgodzie z" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "in recognition of", polish: "w uznaniu" },
    { english: "in honor of", polish: "na cześć" },
    { english: "in memory of", polish: "w pamięci" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in connection with", polish: "w związku z" },
    { english: "in light of", polish: "w świetle" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "on behalf of", polish: "w imieniu" },
    { english: "by means of", polish: "za pomocą" },
    { english: "as per", polish: "zgodnie z" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in connection with", polish: "w związku z" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "in favor of", polish: "na rzecz" },
    { english: "in support of", polish: "w wsparciu" },
    { english: "as a result of", polish: "w wyniku" },
    { english: "by means of", polish: "za pomocą" },
    { english: "by virtue of", polish: "na mocy" },
    { english: "as per", polish: "zgodnie z" },
    { english: "in response to", polish: "w odpowiedzi na" },
    { english: "in relation to", polish: "w związku z" },
    { english: "in view of", polish: "w obliczu" },
    { english: "in light of", polish: "w świetle" },
    { english: "in accordance with", polish: "zgodnie z" },
    { english: "for the sake of", polish: "dla dobra" },
    { english: "for the purpose of", polish: "w celu" },
    { english: "in consideration of", polish: "w obliczu" },
    { english: "in honor of", polish: "na cześć" },
    { english: "in memory of", polish: "w pamięci" }
];

let selectedWords = [];
let currentIndex = 0;
let isEnglishToPolish = true;
let score = 0;
let answerGiven = false; // Śledzenie, czy odpowiedź została podana

// Elementy DOM
const container = document.getElementById("containerAnswer");
const wordDisplay = document.getElementById('wordDisplay');
const userInput = document.getElementById('userInput');
const submitBtn = document.getElementById('submitBtn');
const result = document.getElementById('result');
const nextBtn = document.getElementById('nextBtn');
const optionsContainer = document.getElementById('optionsContainer');
const translationDisplay = document.getElementById('translationDisplay');
const toggleTranslationBtn = document.getElementById('toggleTranslationBtn');
const switchLanguageBtn = document.getElementById('switchLanguageBtn');

// Inicjalizacja
function init() {
    selectedWords = words.slice(); // Wybierz wszystkie słowa
    currentIndex = 0;
    displayWord(); // Wyświetl pierwsze słowo
}

// Wybór słów
document.querySelectorAll('.word-select-btn').forEach(button => {
    button.addEventListener('click', () => {
        const count = button.getAttribute('data-count');
        if (count === 'all') {
            selectedWords = words.slice(); // Wybierz wszystkie słowa
        } else {
            const num = Math.min(parseInt(count), words.length);
            selectedWords = getRandomWords(words, num); // Wybierz losowe słowa
        }
        currentIndex = 0;
        result.textContent = `Wybrano ${selectedWords.length} słówek do nauki.`; // Wyświetl informację
        setTimeout(displayWord, 2000); // Wyświetl pierwsze słowo
    });
});

// Funkcja losująca słowa
function getRandomWords(sourceArray, count) {
    const shuffled = sourceArray.slice().sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
}

// Wyświetlanie słowa
function displayWord() {
    if (selectedWords.length === 0) {
        result.textContent = "Nie wybrano słówek do nauki!";
        return;
    }

    const currentWord = isEnglishToPolish ? selectedWords[currentIndex].english : selectedWords[currentIndex].polish;
    wordDisplay.textContent = currentWord;
    generateOptions(isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english);
    userInput.value = '';
    result.textContent = '';
}

// Generowanie opcji do wyboru
function generateOptions(correctAnswer) {
    optionsContainer.innerHTML = ''; // Wyczyść poprzednie opcje

    const options = [correctAnswer];
    while (options.length < 4) {
        const randomWord = selectedWords[Math.floor(Math.random() * selectedWords.length)];
        if (isEnglishToPolish) {
            if (!options.includes(randomWord.polish)) options.push(randomWord.polish);
        } else {
            if (!options.includes(randomWord.english)) options.push(randomWord.english);
        }
    }

    shuffle(options); // Tasowanie opcji

    options.forEach(option => {
        const btn = document.createElement('button');
        btn.textContent = option;
        btn.className = 'option-btn';
        btn.addEventListener('click', () => checkAnswer(option, correctAnswer));
        optionsContainer.appendChild(btn);
    });
}

// Sprawdzanie odpowiedzi
function checkAnswer(selected, correct) {
    if (answerGiven) return; // Jeśli odpowiedź została już podana, nie rób nic

    const isCorrect = selected === correct || userInput.value.trim().toLowerCase() === correct.toLowerCase();
    
    if (isCorrect) {
        result.textContent = "Dobrze!";
        score++; // Zwiększ wynik
        container.classList.add('bounce'); // Animacja bounce

        // Dodaj klasę .btn-yellow do wszystkich przycisków
        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-yellow'));

        // Usuń klasy po pewnym czasie
        setTimeout(() => {
            container.classList.remove('bounce');
            buttons.forEach(button => button.classList.remove('btn-yellow'));
        }, 600);
    } else {
        result.textContent = `Źle! Poprawne tłumaczenie to: ${correct}`;
        container.classList.add('shake'); // Animacja shake

        // Dodaj klasę .btn-red do wszystkich przycisków
        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-red'));

        // Usuń klasy po pewnym czasie
        setTimeout(() => {
            container.classList.remove('shake');
            buttons.forEach(button => button.classList.remove('btn-red'));
        }, 600);
    }

    answerGiven = true; // Oznacz, że odpowiedź została podana
}

// Obsługa przycisku "Submit"
submitBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    checkAnswer(null, correctTranslation);
});

// Obsługa przycisku "Next"
nextBtn.addEventListener('click', () => {
    if (!answerGiven) return; // Jeśli odpowiedź nie została podana, nie rób nic
    currentIndex = (currentIndex + 1) % selectedWords.length; // Przechodź do następnego słowa (cyklicznie)
    answerGiven = false; // Zresetuj stan
    displayWord();
});

// Toggle tłumaczenia
toggleTranslationBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    translationDisplay.textContent = translationDisplay.textContent ? '' : correctTranslation;
});

// Zmiana języka
switchLanguageBtn.addEventListener('click', () => {
    isEnglishToPolish = !isEnglishToPolish; // Zmień kierunek języka
    displayWord(); // Odśwież wyświetlane słowo
});

// Inicjalizacja
init();

// Funkcja tasująca
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

// Przycisk do ukrywania/pokazywania kontenera wyboru słów
const toggleButton = document.getElementById('hideButton');
const myDiv = document.getElementById('wordSelectContainer');

toggleButton.addEventListener('click', () => {
    myDiv.style.display = myDiv.style.display === 'none' ? 'block' : 'none'; // Przełącz widoczność
});