const words = [
    { english: "asset - An asset is any resource owned by a business or individual that is expected to provide future economic benefits", polish: "aktywa - Aktywa to zasoby posiadane przez firmę lub osobę, które mają zapewnić przyszłe korzyści ekonomiczne." },
    { english: "liability - A liability is a financial obligation or debt owed by a company, which must be settled in the future", polish: "zobowiązania - Zobowiązania to finansowe zobowiązania lub długi, które firma musi spłacić w przyszłości." },
    { english: "equity - Equity represents the value of the owners' interest in a business, calculated as assets minus liabilities", polish: "kapitał własny - Kapitał własny to wartość interesów właścicieli w firmie, obliczana jako aktywa pomniejszone o zobowiązania." },
    { english: "revenue - Revenue is the total income generated by the sale of goods or services by a company", polish: "przychody - Przychody to całkowity dochód generowany ze sprzedaży towarów lub usług przez firmę." },
    { english: "expense - An expense is the cost incurred by a business in the process of earning revenue", polish: "koszty - Koszty to wydatki ponoszone przez firmę w procesie generowania przychodów." },
    { english: "balance sheet - A balance sheet is a financial statement that summarizes a company's assets, liabilities, and equity at a specific point in time", polish: "bilans - Bilans to sprawozdanie finansowe, które podsumowuje aktywa, zobowiązania i kapitał własny firmy w danym momencie." },
    { english: "profit - Profit is the financial gain obtained when the revenue exceeds the expenses", polish: "zysk - Zysk to korzyść finansowa uzyskana, gdy przychody przekraczają koszty." },
    { english: "loss - A loss occurs when the expenses exceed the revenue, resulting in a negative financial outcome", polish: "strata - Strata występuje, gdy koszty przekraczają przychody, prowadząc do negatywnego wyniku finansowego." },
    { english: "income statement - An income statement is a financial document that shows a company's revenues, expenses, and profits or losses over a specific period", polish: "rachunek zysków i strat - Rachunek zysków i strat to dokument finansowy, który pokazuje przychody, koszty i zyski lub straty firmy za określony okres." },
    { english: "cash flow - Cash flow refers to the movement of money in and out of a business, including operating, investing, and financing activities", polish: "przepływy pieniężne - Przepływy pieniężne odnoszą się do ruchu pieniędzy wchodzących i wychodzących z firmy, w tym działalności operacyjnej, inwestycyjnej i finansowej." },
    { english: "working capital - Working capital is the difference between a company's current assets and current liabilities, used to fund daily operations", polish: "kapitał obrotowy - Kapitał obrotowy to różnica między aktywami bieżącymi a zobowiązaniami bieżącymi firmy, wykorzystywana do finansowania codziennej działalności." },
    { english: "debt - Debt refers to the money owed by an individual or company to another party, typically with interest", polish: "dług - Dług odnosi się do pieniędzy, które osoba lub firma jest winna innej stronie, zwykle z odsetkami." },
    { english: "credit - Credit is the ability to borrow money or obtain goods and services with the promise to pay later", polish: "kredyt - Kredyt to zdolność do pożyczania pieniędzy lub uzyskiwania towarów i usług z obietnicą późniejszej spłaty." },
    { english: "accounts payable - Accounts payable are the amounts a company owes to its suppliers for goods or services received", polish: "zobowiązania - Zobowiązania to kwoty, które firma jest winna swoim dostawcom za otrzymane towary lub usługi." },
    { english: "accounts receivable - Accounts receivable are the amounts owed to a company by its customers for goods or services provided", polish: "należności - Należności to kwoty, które firma jest winna przez swoich klientów za dostarczone towary lub usługi." },
    { english: "financial statements - Financial statements are formal records of the financial activities of a business, including the balance sheet, income statement, and cash flow statement", polish: "sprawozdania finansowe - Sprawozdania finansowe to formalne zapisy działalności finansowej firmy, w tym bilans, rachunek zysków i strat oraz sprawozdanie z przepływów pieniężnych." },
    { english: "audit - An audit is an independent examination of financial records to ensure their accuracy and compliance with regulations", polish: "audyt - Audyt to niezależne badanie zapisów finansowych, mające na celu zapewnienie ich dokładności i zgodności z przepisami." },
    { english: "tax - A tax is a compulsory financial charge imposed by the government on individuals and businesses to fund public services", polish: "podatek - Podatek to obowiązkowa opłata finansowa nałożona przez rząd na osoby fizyczne i firmy w celu finansowania usług publicznych." },
    { english: "capital gain - A capital gain is the profit from the sale of an asset such as stocks, bonds, or real estate", polish: "zysk kapitałowy - Zysk kapitałowy to zysk ze sprzedaży aktywa, takiego jak akcje, obligacje lub nieruchomości." },
    { english: "dividend - A dividend is a payment made by a corporation to its shareholders, usually in the form of cash or additional shares", polish: "dywidenda - Dywidenda to płatność dokonana przez korporację na rzecz jej akcjonariuszy, zwykle w formie gotówki lub dodatkowych akcji." },
    { english: "interest - Interest is the cost of borrowing money, typically expressed as a percentage of the principal amount", polish: "odsetki - Odsetki to koszt pożyczania pieniędzy, zwykle wyrażony jako procent od kwoty głównej." },
    { english: "budget - A budget is a financial plan that estimates income and expenses over a specific period", polish: "budżet - Budżet to plan finansowy, który szacuje dochody i wydatki w określonym okresie." },
    { english: "depreciation - Depreciation is the reduction in the value of an asset over time due to wear and tear or obsolescence", polish: "amortyzacja - Amortyzacja to spadek wartości aktywa w czasie z powodu zużycia lub przestarzałości." },
    { english: "amortization - Amortization is the process of gradually reducing a debt or the cost of an intangible asset over time", polish: "amortyzacja - Amortyzacja to proces stopniowego redukowania zadłużenia lub kosztu aktywa niematerialnego w czasie." },
    { english: "capital expenditure - Capital expenditures are funds used by a company to acquire or upgrade physical assets such as property, buildings, or equipment", polish: "wydatki kapitałowe - Wydatki kapitałowe to środki wykorzystywane przez firmę na nabycie lub ulepszenie aktywów trwałych, takich jak nieruchomości, budynki lub wyposażenie." },
    { english: "operating income - Operating income is the profit a company makes from its regular business activities, excluding income from non-operating activities", polish: "dochód operacyjny - Dochód operacyjny to zysk, jaki firma osiąga z regularnej działalności gospodarczej, z wyłączeniem dochodów z działalności nieoperacyjnej." },
    { english: "non-operating income - Non-operating income refers to income earned from activities not related to a company's core business operations", polish: "dochód nieoperacyjny - Dochód nieoperacyjny odnosi się do dochodów uzyskanych z działalności niezwiązanej z podstawową działalnością firmy." },
    { english: "gross margin - Gross margin is the difference between sales and the cost of goods sold, expressed as a percentage of sales", polish: "marża brutto - Marża brutto to różnica między sprzedażą a kosztem sprzedanych towarów, wyrażona jako procent sprzedaży." },
    { english: "net margin - Net margin is the percentage of revenue that remains after all expenses, taxes, and costs have been deducted from total revenue", polish: "marża netto - Marża netto to procent przychodów, który pozostaje po odliczeniu wszystkich wydatków, podatków i kosztów od całkowitych przychodów." },
    { english: "return on investment (ROI) - ROI is a performance measure used to evaluate the efficiency of an investment, calculated by dividing the net profit by the cost of the investment", polish: "zwrot z inwestycji (ROI) - ROI to miara efektywności inwestycji, obliczana przez podzielenie zysku netto przez koszt inwestycji." },
    { english: "inventory - Inventory refers to the raw materials, work-in-progress, and finished goods held by a company for the purpose of resale or production", polish: "zapasy - Zapasy to surowce, półprodukty i gotowe towary przechowywane przez firmę w celu odsprzedaży lub produkcji." },
    { english: "debt-to-equity ratio - The debt-to-equity ratio is a measure of a company's financial leverage, calculated by dividing total liabilities by shareholders' equity", polish: "wskaźnik zadłużenia do kapitału własnego - Wskaźnik zadłużenia do kapitału własnego to miara dźwigni finansowej firmy, obliczana przez podzielenie całkowitych zobowiązań przez kapitał własny akcjonariuszy." },
    {english: "working capital - Working capital is the difference between a company's current assets and current liabilities, used to fund daily operations", polish: "kapitał obrotowy - Kapitał obrotowy to różnica między aktywami bieżącymi a zobowiązaniami bieżącymi firmy, wykorzystywana do finansowania codziennej działalności."},
    {english: "depreciation - Depreciation is the reduction in the value of an asset over time due to wear and tear or obsolescence", polish: "amortyzacja - Amortyzacja to spadek wartości aktywa w czasie z powodu zużycia lub przestarzałości."},
    {english: "cost of goods sold (COGS) - The cost of goods sold is the direct costs attributable to the production of the goods sold by a company", polish: "koszt sprzedanych towarów (COGS) - Koszt sprzedanych towarów to bezpośrednie koszty przypisane do produkcji towarów sprzedanych przez firmę."},
    {english: "earnings per share (EPS) - EPS is the portion of a company's profit allocated to each outstanding share of common stock", polish: "zysk na akcję (EPS) - EPS to część zysku firmy przypisana do każdej wyemitowanej akcji zwykłej."},
    {english: "market capitalization - Market capitalization is the total market value of a company's outstanding shares, calculated by multiplying the share price by the total number of shares", polish: "kapitalizacja rynkowa - Kapitalizacja rynkowa to całkowita wartość rynkowa wyemitowanych akcji firmy, obliczana przez pomnożenie ceny akcji przez łączną liczbę akcji."},
    {english: "dividend yield - Dividend yield is the annual dividend payment divided by the stock price, expressed as a percentage", polish: "stopa dywidendy - Stopa dywidendy to roczna wypłata dywidendy podzielona przez cenę akcji, wyrażona jako procent."},
    {english: "price-to-earnings ratio (P/E) - The P/E ratio is a valuation ratio calculated by dividing a company's share price by its earnings per share", polish: "wskaźnik cena do zysków (P/E) - Wskaźnik P/E to wskaźnik wyceny, obliczany przez podzielenie ceny akcji firmy przez zysk na akcję."},
    {english: "current ratio - The current ratio is a liquidity ratio that measures a company's ability to pay short-term liabilities with its short-term assets", polish: "wskaźnik bieżący - Wskaźnik bieżący to wskaźnik płynności, który mierzy zdolność firmy do spłacania zobowiązań krótkoterminowych za pomocą aktywów krótkoterminowych."},
    {english: "quick ratio - The quick ratio is a more stringent liquidity ratio that excludes inventory from the company's current assets", polish: "wskaźnik szybki - Wskaźnik szybki to bardziej rygorystyczny wskaźnik płynności, który wyklucza zapasy z aktywów bieżących firmy."},
    {english: "debt ratio - The debt ratio is a financial ratio that measures the proportion of a company's assets that are financed through debt", polish: "wskaźnik zadłużenia - Wskaźnik zadłużenia to wskaźnik finansowy, który mierzy proporcję aktywów firmy finansowanych długiem."},
    {english: "interest coverage ratio - The interest coverage ratio measures a company's ability to meet its interest payments on outstanding debt", polish: "wskaźnik pokrycia odsetek - Wskaźnik pokrycia odsetek mierzy zdolność firmy do spłacania odsetek od zadłużenia."},
    {english: "return on assets (ROA) - ROA is a profitability ratio that shows how effectively a company uses its assets to generate profit", polish: "zwrot z aktywów (ROA) - ROA to wskaźnik rentowności, który pokazuje, jak skutecznie firma wykorzystuje swoje aktywa do generowania zysków."},
    {english: "return on equity (ROE) - ROE is a measure of a company's profitability that compares net income to shareholders' equity", polish: "zwrot z kapitału własnego (ROE) - ROE to miara rentowności firmy, która porównuje zysk netto do kapitału własnego akcjonariuszy."},
    {english: "gross profit - Gross profit is the difference between revenue and the cost of goods sold, excluding other expenses such as operating expenses", polish: "zysk brutto - Zysk brutto to różnica między przychodami a kosztem sprzedanych towarów, z wyłączeniem innych wydatków, takich jak koszty operacyjne."},
    {english: "net income - Net income is the amount of money a company has left over after all expenses, taxes, and other costs are subtracted from total revenue", polish: "dochód netto - Dochód netto to kwota, która pozostaje firmie po odliczeniu wszystkich wydatków, podatków i innych kosztów od całkowitych przychodów."},
    {english: "cost accounting - Cost accounting involves the recording, analysis, and reporting of costs associated with a company's production or operations", polish: "rachunek kosztów - Rachunek kosztów obejmuje rejestrowanie, analizowanie i raportowanie kosztów związanych z produkcją lub działalnością firmy."},
    {english: "financial leverage - Financial leverage refers to the use of debt to acquire additional assets, with the aim of increasing the return on equity", polish: "dźwignia finansowa - Dźwignia finansowa odnosi się do użycia długu do pozyskania dodatkowych aktywów, w celu zwiększenia zwrotu z kapitału własnego."},
    {english: "capital structure - Capital structure is the mix of debt and equity financing a company uses to fund its operations and growth", polish: "struktura kapitałowa - Struktura kapitałowa to kombinacja finansowania długiem i kapitałem własnym, którą firma wykorzystuje do finansowania swojej działalności i wzrostu."},
    {english: "business valuation - Business valuation is the process of determining the economic value of a business or company", polish: "wycena firmy - Wycena firmy to proces określania wartości ekonomicznej firmy."},
    {english: "financial ratio - A financial ratio is a relationship between two numbers, typically used to assess a company's financial performance", polish: "wskaźnik finansowy - Wskaźnik finansowy to zależność między dwoma liczbami, zwykle wykorzystywana do oceny wyników finansowych firmy."},
    {english: "dividend payout ratio - The dividend payout ratio is the proportion of earnings paid out to shareholders in the form of dividends", polish: "wskaźnik wypłaty dywidendy - Wskaźnik wypłaty dywidendy to proporcja zysków wypłacanych akcjonariuszom w formie dywidend."},
    {english: "liquidity ratio - Liquidity ratio is a measure of a company's ability to pay off its short-term debts with its liquid assets", polish: "wskaźnik płynności - Wskaźnik płynności to miara zdolności firmy do spłacenia krótkoterminowych długów za pomocą jej aktywów płynnych."},
    {english: "capital allocation - Capital allocation is the process of distributing a company's financial resources across various investment opportunities", polish: "alokacja kapitału - Alokacja kapitału to proces rozdzielania zasobów finansowych firmy między różne możliwości inwestycyjne."},
    {english: "cost-benefit analysis - Cost-benefit analysis is a process of comparing the costs of an action or project with its potential benefits", polish: "analiza kosztów i korzyści - Analiza kosztów i korzyści to proces porównywania kosztów działania lub projektu z potencjalnymi korzyściami."},
    {english: "debt-to-equity ratio - The debt-to-equity ratio is a measure of a company's financial leverage, calculated by dividing total liabilities by shareholders' equity", polish: "wskaźnik zadłużenia do kapitału własnego - Wskaźnik zadłużenia do kapitału własnego to miara dźwigni finansowej firmy, obliczana przez podzielenie całkowitych zobowiązań przez kapitał własny akcjonariuszy."},
    {english: "return on investment (ROI) - ROI is a measure of the profitability of an investment, calculated by dividing the net return by the initial investment", polish: "zwrot z inwestycji (ROI) - ROI to miara rentowności inwestycji, obliczana przez podzielenie zwrotu netto przez początkową inwestycję."},
    {english: "asset allocation - Asset allocation is the process of deciding how to distribute an investment portfolio among different asset categories, such as stocks, bonds, and cash", polish: "alokacja aktywów - Alokacja aktywów to proces podejmowania decyzji, jak rozdzielić portfel inwestycyjny pomiędzy różne kategorie aktywów, takie jak akcje, obligacje i gotówka."},
    {english: "operating income - Operating income is the profit a company makes from its core business operations, excluding any income from non-operating activities", polish: "dochód operacyjny - Dochód operacyjny to zysk, który firma uzyskuje z podstawowej działalności operacyjnej, z wyłączeniem dochodów z działalności nieoperacyjnej."},
    {english: "balance sheet - A balance sheet is a financial statement that reports a company's financial position by listing its assets, liabilities, and equity", polish: "bilans - Bilans to sprawozdanie finansowe, które przedstawia sytuację finansową firmy, wykazując jej aktywa, zobowiązania i kapitał własny."},
    {english: "cash flow - Cash flow refers to the movement of money into and out of a business, used to assess the company's financial health", polish: "przepływ gotówki - Przepływ gotówki odnosi się do przepływu pieniędzy do i z firmy, wykorzystywanego do oceny kondycji finansowej firmy."},
    {english: "gross margin - Gross margin is the difference between sales revenue and the cost of goods sold, expressed as a percentage of sales", polish: "marża brutto - Marża brutto to różnica między przychodami ze sprzedaży a kosztem sprzedanych towarów, wyrażona jako procent sprzedaży."},
    {english: "operating margin - Operating margin is a profitability ratio that shows the percentage of revenue a company retains after covering operating expenses", polish: "marża operacyjna - Marża operacyjna to wskaźnik rentowności, który pokazuje procent przychodów, który firma zatrzymuje po pokryciu kosztów operacyjnych."},
    {english: "net profit margin - Net profit margin is a profitability ratio that shows the percentage of revenue that remains as profit after all expenses and taxes", polish: "marża zysku netto - Marża zysku netto to wskaźnik rentowności, który pokazuje procent przychodów, który pozostaje jako zysk po odliczeniu wszystkich wydatków i podatków."},
    {english: "fixed costs - Fixed costs are expenses that do not change with the level of production or sales, such as rent or salaries", polish: "koszty stałe - Koszty stałe to wydatki, które nie zmieniają się w zależności od poziomu produkcji lub sprzedaży, takie jak czynsz czy pensje."},
    {english: "variable costs - Variable costs are expenses that change with the level of production or sales, such as raw materials or direct labor", polish: "koszty zmienne - Koszty zmienne to wydatki, które zmieniają się w zależności od poziomu produkcji lub sprzedaży, takie jak surowce czy praca bezpośrednia."},
    {english: "break-even point - The break-even point is the level of sales at which total revenue equals total costs, resulting in neither profit nor loss", polish: "punkt rentowności - Punkt rentowności to poziom sprzedaży, przy którym całkowite przychody równe są całkowitym kosztom, co skutkuje brakiem zysku lub straty."},
    {english: "accounts payable - Accounts payable refers to money that a company owes to suppliers or creditors for goods or services received", polish: "zobowiązania - Zobowiązania to pieniądze, które firma jest winna dostawcom lub wierzycielom za otrzymane towary lub usługi."},
    {english: "accounts receivable - Accounts receivable refers to money that customers owe to a company for goods or services provided", polish: "należności - Należności to pieniądze, które klienci są winni firmie za dostarczone towary lub usługi."},
    {english: "audit - An audit is an independent examination of financial records to ensure accuracy and compliance with regulations", polish: "audyt - Audyt to niezależne badanie dokumentacji finansowej w celu zapewnienia dokładności i zgodności z przepisami."},
    {english: "dividend - A dividend is a payment made by a company to its shareholders, typically in the form of cash or additional shares", polish: "dywidenda - Dywidenda to wypłata dokonywana przez firmę jej akcjonariuszom, zazwyczaj w formie gotówki lub dodatkowych akcji."},
    {english: "corporate tax - Corporate tax is a tax imposed on the profits of a corporation", polish: "podatek korporacyjny - Podatek korporacyjny to podatek nakładany na zyski korporacji."},
    {english: "financial statement - A financial statement is a formal record of a company's financial activities, including income statement, balance sheet, and cash flow statement", polish: "sprawozdanie finansowe - Sprawozdanie finansowe to formalny zapis działalności finansowej firmy, w tym rachunek zysków i strat, bilans oraz rachunek przepływów pieniężnych."},
    {english: "taxable income - Taxable income is the amount of income that is subject to taxation after deductions and exemptions", polish: "dochód podlegający opodatkowaniu - Dochód podlegający opodatkowaniu to kwota dochodu, która podlega opodatkowaniu po odliczeniu ulg i zwolnień."},
    {english: "tax evasion - Tax evasion is the illegal practice of intentionally avoiding paying taxes", polish: "unikanie opodatkowania - Unikanie opodatkowania to nielegalna praktyka polegająca na celowym unikaniu płacenia podatków."},
    {english: "tax avoidance - Tax avoidance is the legal practice of minimizing tax liability through strategic planning and use of deductions", polish: "unikanie opodatkowania - Unikanie opodatkowania to legalna praktyka minimalizowania zobowiązań podatkowych poprzez planowanie strategiczne i wykorzystanie odliczeń."},
    {english: "capital gain - A capital gain is the profit earned from the sale of an asset, such as real estate or stocks", polish: "zysk kapitałowy - Zysk kapitałowy to zysk uzyskany ze sprzedaży aktywa, takiego jak nieruchomość czy akcje."},
    {english: "liability - Liability refers to an obligation or debt that a company or individual must pay in the future", polish: "zobowiązanie - Zobowiązanie odnosi się do obowiązku lub długu, który firma lub osoba musi spłacić w przyszłości."},
    {english: "equity - Equity represents the value of ownership interest in a company, calculated as assets minus liabilities", polish: "kapitał własny - Kapitał własny to wartość udziału w przedsiębiorstwie, obliczana jako aktywa minus zobowiązania."},
    {english: "goodwill - Goodwill is an intangible asset that represents the value of a company's brand, reputation, customer relationships, and intellectual property", polish: "warta firma - Warta firma to niematerialny składnik aktywów, który reprezentuje wartość marki firmy, jej reputacji, relacji z klientami oraz własności intelektualnej."},
    {english: "depreciation - Depreciation is the process of allocating the cost of a tangible asset over its useful life", polish: "amortyzacja - Amortyzacja to proces rozłożenia kosztu aktywa rzeczowego na jego przewidywany okres użytkowania."},
    {english: "accrual accounting - Accrual accounting is an accounting method that recognizes revenue and expenses when they are incurred, regardless of when cash is exchanged", polish: "rachunkowość memoriałowa - Rachunkowość memoriałowa to metoda rachunkowości, która uwzględnia przychody i koszty w momencie ich wystąpienia, niezależnie od tego, kiedy następuje wymiana gotówki."},
    {english: "cash basis accounting - Cash basis accounting is an accounting method where revenue and expenses are recognized only when cash is exchanged", polish: "rachunkowość kasowa - Rachunkowość kasowa to metoda rachunkowości, w której przychody i koszty są uwzględniane tylko w momencie wymiany gotówki."},
    {english: "earnings per share (EPS) - Earnings per share is a financial metric that indicates the portion of a company’s profit allocated to each outstanding share of common stock", polish: "zysk na akcję (EPS) - Zysk na akcję to wskaźnik finansowy, który wskazuje część zysku firmy przypadającą na każdą wyemitowaną akcję zwykłą."},
    {english: "stockholders equity - Stockholders' equity represents the ownership interest of shareholders in a company, calculated as total assets minus total liabilities", polish: "kapitał własny akcjonariuszy - Kapitał własny akcjonariuszy reprezentuje udział właścicielski akcjonariuszy w firmie, obliczany jako aktywa całkowite minus zobowiązania całkowite."},
    {english: "liquidity - Liquidity refers to the ability of an asset to be quickly converted into cash without significant loss of value", polish: "płynność - Płynność odnosi się do zdolności aktywa do szybkiej konwersji na gotówkę bez znacznej utraty wartości."},
    {english: "solvency - Solvency refers to the ability of a company to meet its long-term financial obligations", polish: "zdolność kredytowa - Zdolność kredytowa odnosi się do zdolności firmy do spłacania swoich długoterminowych zobowiązań finansowych."},
    {english: "financial leverage - Financial leverage is the use of borrowed funds to increase the potential return on investment", polish: "dźwignia finansowa - Dźwignia finansowa to wykorzystanie pożyczonych środków do zwiększenia potencjalnego zwrotu z inwestycji."},
    {english: "short-term debt - Short-term debt refers to loans or obligations that must be repaid within a year", polish: "krótkoterminowy dług - Krótkoterminowy dług odnosi się do pożyczek lub zobowiązań, które muszą zostać spłacone w ciągu roku."},
    {english: "long-term debt - Long-term debt refers to loans or obligations that are due for repayment over a period longer than one year", polish: "długoterminowy dług - Długoterminowy dług odnosi się do pożyczek lub zobowiązań, które mają być spłacone w okresie dłuższym niż jeden rok."},
    {english: "tax deduction - A tax deduction is an expense that can be subtracted from a taxpayer’s gross income to reduce taxable income", polish: "odliczenie podatkowe - Odliczenie podatkowe to wydatek, który można odjąć od dochodu brutto podatnika, aby zmniejszyć dochód podlegający opodatkowaniu."},
    {english: "tax credit - A tax credit is a direct reduction in the amount of taxes owed, often given for specific activities or purchases", polish: "ulga podatkowa - Ulga podatkowa to bezpośrednia redukcja kwoty należnych podatków, często przyznawana za konkretne działania lub zakupy."},
    {english: "capital structure - Capital structure refers to the way a company finances its operations, typically through a combination of debt and equity", polish: "struktura kapitałowa - Struktura kapitałowa odnosi się do sposobu finansowania działalności firmy, zazwyczaj za pomocą kombinacji długu i kapitału własnego."},
    {english: "stock buyback - A stock buyback occurs when a company buys back its own shares from the market, often to reduce the number of outstanding shares", polish: "odkup akcji - Odkup akcji ma miejsce, gdy firma wykupuje swoje własne akcje z rynku, często w celu zmniejszenia liczby wyemitowanych akcji."},
    {english: "leveraged buyout (LBO) - A leveraged buyout is a type of acquisition where a company is purchased using a significant amount of borrowed funds", polish: "wykup lewarowany (LBO) - Wykup lewarowany to rodzaj przejęcia, w którym firma jest kupowana przy użyciu znacznej ilości pożyczonych środków."},
    {english: "working capital - Working capital is the difference between a company’s current assets and current liabilities, used to measure its short-term financial health", polish: "kapitał obrotowy - Kapitał obrotowy to różnica między aktywami obrotowymi a zobowiązaniami krótkoterminowymi firmy, wykorzystywana do oceny jej krótkoterminowej kondycji finansowej."},
    {english: "business model - A business model describes how a company creates, delivers, and captures value for its customers", polish: "model biznesowy - Model biznesowy opisuje, jak firma tworzy, dostarcza i pozyskuje wartość dla swoich klientów."},
    {english: "venture capital - Venture capital is financing provided to early-stage, high-potential companies in exchange for equity or ownership interest", polish: "kapitał podwyższonego ryzyka - Kapitał podwyższonego ryzyka to finansowanie udzielane firmom na wczesnym etapie rozwoju, które mają wysokie możliwości, w zamian za udziały lub prawo własności."},
    {english: "private equity - Private equity is capital invested in a company that is not listed on a public exchange, typically used to fund expansion or buyouts", polish: "kapitał prywatny - Kapitał prywatny to kapitał inwestowany w firmę, która nie jest notowana na giełdzie publicznej, zazwyczaj wykorzystywany do finansowania rozwoju lub wykupów."},
    {english: "angel investor - An angel investor is an individual who provides capital to early-stage startups, typically in exchange for ownership equity or convertible debt", polish: "anioł biznesu - Anioł biznesu to osoba, która udziela kapitału firmom na wczesnym etapie, zazwyczaj w zamian za udziały własnościowe lub konwertowalny dług."},
    {english: "crowdfunding - Crowdfunding is a method of raising capital by soliciting small contributions from a large number of people, typically through online platforms", polish: "crowdfunding - Crowdfunding to metoda pozyskiwania kapitału poprzez zbieranie małych wkładów od dużej liczby osób, zazwyczaj za pośrednictwem platform internetowych."},
    {english: "initial public offering (IPO) - An IPO is the first sale of a company’s stock to the public, allowing the company to raise capital from public investors", polish: "pierwsza oferta publiczna (IPO) - IPO to pierwsza sprzedaż akcji firmy na rynku publicznym, pozwalająca firmie na pozyskanie kapitału od inwestorów publicznych."},
    {english: "secondary market - A secondary market is a market where previously issued securities, such as stocks and bonds, are bought and sold", polish: "rynek wtórny - Rynek wtórny to rynek, na którym kupowane i sprzedawane są wcześniej wydane papiery wartościowe, takie jak akcje i obligacje."},
    {english: "primary market - The primary market is the market where new securities are issued and sold for the first time", polish: "rynek pierwotny - Rynek pierwotny to rynek, na którym nowe papiery wartościowe są emitowane i sprzedawane po raz pierwszy."},
    {english: "diversification - Diversification is a risk management strategy that involves spreading investments across various financial assets to reduce exposure to any single risk", polish: "dywersyfikacja - Dywersyfikacja to strategia zarządzania ryzykiem, która polega na rozpraszaniu inwestycji w różnych aktywach finansowych, aby zminimalizować ryzyko związane z pojedynczym aktywem."},
    {english: "hedging - Hedging is an investment strategy used to offset the risk of adverse price movements in an asset", polish: "hedging - Hedging to strategia inwestycyjna, która służy do zminimalizowania ryzyka niekorzystnych zmian cen aktywa."},
    {english: "securitization - Securitization is the process of converting assets into securities that can be traded on financial markets", polish: "sekurytyzacja - Sekurytyzacja to proces przekształcania aktywów w papiery wartościowe, które mogą być przedmiotem obrotu na rynkach finansowych."},
    {english: "capital gains - Capital gains are the profits realized from the sale of assets or investments, typically taxed at a different rate than ordinary income", polish: "zysk kapitałowy - Zysk kapitałowy to zyski uzyskane ze sprzedaży aktywów lub inwestycji, zazwyczaj opodatkowane w inny sposób niż dochód zwykły."},
    {english: "inflation - Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power", polish: "inflacja - Inflacja to wskaźnik, w jakim ogólny poziom cen towarów i usług rośnie, co powoduje spadek siły nabywczej."},
    {english: "deflation - Deflation is the reduction in the general level of prices for goods and services, typically caused by a decrease in the supply of money", polish: "deflacja - Deflacja to spadek ogólnego poziomu cen towarów i usług, zazwyczaj spowodowany spadkiem podaży pieniądza."},
    {english: "monetary policy - Monetary policy refers to the actions taken by a central bank to control the money supply and interest rates to stabilize the economy", polish: "polityka monetarna - Polityka monetarna odnosi się do działań podejmowanych przez bank centralny w celu kontrolowania podaży pieniądza i stóp procentowych, mających na celu stabilizację gospodarki."},
    {english: "fiscal policy - Fiscal policy refers to the use of government spending and taxation to influence the economy", polish: "polityka fiskalna - Polityka fiskalna odnosi się do wykorzystania wydatków rządowych i opodatkowania w celu wpływania na gospodarkę."},
    {english: "interest rate - An interest rate is the percentage charged on a loan or earned through an investment", polish: "stopa procentowa - Stopa procentowa to procentowa opłata za pożyczkę lub procent uzyskany z inwestycji."},
    {english: "reserve requirement - Reserve requirement is the minimum amount of reserves that a bank must hold against deposits, as mandated by the central bank", polish: "wymóg rezerw - Wymóg rezerw to minimalna kwota rezerw, które bank musi utrzymywać wobec depozytów, zgodnie z wymaganiami banku centralnego."},
    {english: "exchange rate - An exchange rate is the value of one currency for the purpose of conversion to another", polish: "kurs wymiany - Kurs wymiany to wartość jednej waluty w celu jej wymiany na inną."},
    {english: "currency devaluation - Currency devaluation is the reduction in the value of a currency relative to other currencies, often by a central bank", polish: "dewaluacja waluty - Dewaluacja waluty to obniżenie wartości waluty w stosunku do innych walut, często przez bank centralny."},
    {english: "currency appreciation - Currency appreciation refers to the increase in the value of a currency relative to others", polish: "aprecjacja waluty - Aprecjacja waluty odnosi się do wzrostu wartości waluty w stosunku do innych."},
    {english: "trade deficit - A trade deficit occurs when a country imports more goods and services than it exports", polish: "deficyt handlowy - Deficyt handlowy występuje, gdy kraj importuje więcej towarów i usług, niż eksportuje."},
    {english: "trade surplus - A trade surplus occurs when a country exports more goods and services than it imports", polish: "nadwyżka handlowa - Nadwyżka handlowa występuje, gdy kraj eksportuje więcej towarów i usług, niż importuje."},
    {english: "tariff - A tariff is a tax imposed on imported goods, typically used to protect domestic industries", polish: "cło - Cło to podatek nałożony na towary importowane, zazwyczaj w celu ochrony krajowych przemysłów."},
    {english: "subsidy - A subsidy is a financial aid or support provided by the government to encourage the production or consumption of a particular product", polish: "subsydia - Subsydia to wsparcie finansowe udzielane przez rząd w celu zachęcenia do produkcji lub konsumpcji określonego produktu."},
    {english: "GDP (Gross Domestic Product) - GDP is the total market value of all final goods and services produced within a country in a given period", polish: "PKB (Produkt Krajowy Brutto) - PKB to całkowita wartość rynkowa wszystkich finalnych dóbr i usług wytworzonych w kraju w danym okresie."},
    {english: "real GDP - Real GDP is the GDP adjusted for inflation, reflecting the true value of goods and services produced", polish: "realny PKB - Realny PKB to PKB skorygowany o inflację, odzwierciedlający rzeczywistą wartość wytworzonych dóbr i usług."},
    {english: "nominal GDP - Nominal GDP is the GDP measured using current prices, without adjusting for inflation", polish: "nominalny PKB - Nominalny PKB to PKB mierzony przy użyciu bieżących cen, bez uwzględniania inflacji."},
    {english: "inflation rate - The inflation rate is the percentage change in the general price level of goods and services over a period", polish: "wskaźnik inflacji - Wskaźnik inflacji to procentowa zmiana ogólnego poziomu cen towarów i usług w danym okresie."},
    {english: "unemployment rate - The unemployment rate is the percentage of the labor force that is jobless and actively seeking work", polish: "wskaźnik bezrobocia - Wskaźnik bezrobocia to procent siły roboczej, która jest bez pracy i aktywnie poszukuje zatrudnienia."},
    {english: "monetary tightening - Monetary tightening refers to actions taken by a central bank to reduce the money supply, often by raising interest rates", polish: "zacieśnianie polityki monetarnej - Zacieśnianie polityki monetarnej odnosi się do działań podejmowanych przez bank centralny w celu zmniejszenia podaży pieniądza, często poprzez podnoszenie stóp procentowych."},
    {english: "monetary easing - Monetary easing refers to actions taken by a central bank to increase the money supply, typically by lowering interest rates", polish: "poluzowanie polityki monetarnej - Poluzowanie polityki monetarnej odnosi się do działań podejmowanych przez bank centralny w celu zwiększenia podaży pieniądza, zazwyczaj poprzez obniżanie stóp procentowych."},
    {english: "quantitative easing - Quantitative easing is a non-conventional monetary policy where a central bank buys financial assets to inject liquidity into the economy", polish: "luźna polityka monetarna - Luźna polityka monetarna to niestandardowa polityka monetarna, w której bank centralny kupuje aktywa finansowe, aby wprowadzić płynność do gospodarki."},
    {english: "interest rate hike - An interest rate hike is an increase in the central bank's benchmark interest rate, typically used to combat inflation", polish: "podwyżka stóp procentowych - Podwyżka stóp procentowych to zwiększenie podstawowej stopy procentowej banku centralnego, zazwyczaj stosowane w celu walki z inflacją."},
    {english: "interest rate cut - An interest rate cut is a reduction in the central bank's benchmark interest rate, often aimed at stimulating economic growth", polish: "obniżenie stóp procentowych - Obniżenie stóp procentowych to zmniejszenie podstawowej stopy procentowej banku centralnego, często mające na celu stymulowanie wzrostu gospodarczego."},
    {english: "fiscal stimulus - A fiscal stimulus is a policy measure that involves increasing government spending or cutting taxes to boost economic activity", polish: "stymulacja fiskalna - Stymulacja fiskalna to środek polityczny polegający na zwiększeniu wydatków rządowych lub obniżeniu podatków w celu pobudzenia aktywności gospodarczej."},
    {english: "debt ceiling - The debt ceiling is a limit set by the government on the amount of debt that can be incurred by the federal government", polish: "limit zadłużenia - Limit zadłużenia to granica ustalana przez rząd na kwotę długu, jaką może zaciągnąć rząd federalny."},
    {english: "crowding out - Crowding out refers to a situation where increased government spending leads to reduced private sector investment", polish: "wypieranie sektora prywatnego - Wypieranie sektora prywatnego odnosi się do sytuacji, w której wzrost wydatków rządowych prowadzi do zmniejszenia inwestycji sektora prywatnego."},
    {english: "monopoly - A monopoly is a market structure where a single producer or seller controls the supply of a product or service", polish: "monopol - Monopol to struktura rynku, w której jeden producent lub sprzedawca kontroluje podaż produktu lub usługi."},
    {english: "oligopoly - An oligopoly is a market structure dominated by a small number of firms that control the majority of the market", polish: "oligopol - Oligopol to struktura rynku zdominowana przez niewielką liczbę firm, które kontrolują większość rynku."},
    {english: "perfect competition - Perfect competition is a market structure characterized by a large number of buyers and sellers, where no single participant has the power to influence prices", polish: "doskonała konkurencja - Doskonała konkurencja to struktura rynku charakteryzująca się dużą liczbą kupujących i sprzedających, gdzie żaden uczestnik rynku nie ma wpływu na ceny."},
    {english: "monopolistic competition - Monopolistic competition is a market structure in which many firms sell similar but not identical products, and each firm has some control over its prices", polish: "konkurencja monopolistyczna - Konkurencja monopolistyczna to struktura rynku, w której wiele firm sprzedaje podobne, ale nie identyczne produkty, a każda firma ma pewną kontrolę nad swoimi cenami."},
    {english: "price discrimination - Price discrimination occurs when a company charges different prices for the same product or service based on factors like location, age, or purchasing power", polish: "dyskryminacja cenowa - Dyskryminacja cenowa występuje, gdy firma pobiera różne ceny za ten sam produkt lub usługę w zależności od takich czynników jak lokalizacja, wiek czy siła nabywcza."},
    {english: "elasticity of demand - Elasticity of demand measures how much the quantity demanded of a good responds to a change in its price", polish: "elastyczność popytu - Elastyczność popytu mierzy, jak bardzo ilość żądanego dobra zmienia się w odpowiedzi na zmianę ceny."},
    {english: "inelastic demand - Inelastic demand refers to a situation where the quantity demanded of a good does not change significantly when its price changes", polish: "popyt nieelastyczny - Popyt nieelastyczny odnosi się do sytuacji, w której ilość żądanego dobra nie zmienia się znacząco, gdy cena zmienia się."},
    {english: "substitute goods - Substitute goods are products that can replace each other in use, such as butter and margarine", polish: "dobra substytucyjne - Dobra substytucyjne to produkty, które mogą zastępować się wzajemnie w użyciu, takie jak masło i margaryna."},
    {english: "complementary goods - Complementary goods are products that are used together, such as printers and ink cartridges", polish: "dobra komplementarne - Dobra komplementarne to produkty, które są używane razem, takie jak drukarki i tusze do drukarek."},
    {english: "economies of scale - Economies of scale refer to the cost advantages that firms experience when increasing their scale of production", polish: "korzyści skali - Korzyści skali to przewagi kosztowe, które firmy osiągają, zwiększając skalę produkcji."},
    {english: "diseconomies of scale - Diseconomies of scale occur when a company grows too large and the cost per unit increases as the company expands", polish: "dyskożności skali - Dyskożności skali występują, gdy firma staje się zbyt duża, a koszt jednostkowy wzrasta w miarę rozwoju firmy."},
    {english: "marginal cost - Marginal cost is the cost of producing one more unit of a good or service", polish: "koszt krańcowy - Koszt krańcowy to koszt wyprodukowania jednej dodatkowej jednostki dobra lub usługi."},
    {english: "marginal revenue - Marginal revenue is the additional revenue gained from selling one more unit of a good or service", polish: "przychód krańcowy - Przychód krańcowy to dodatkowy przychód uzyskany ze sprzedaży jednej dodatkowej jednostki dobra lub usługi."},
    {english: "market equilibrium - Market equilibrium occurs when the supply of goods matches demand, resulting in a stable market price", polish: "równowaga rynkowa - Równowaga rynkowa występuje, gdy podaż dóbr odpowiada popytowi, co prowadzi do stabilnej ceny rynkowej."},
    {english: "price ceiling - A price ceiling is a maximum price set by the government for a particular good or service", polish: "górna granica ceny - Górna granica ceny to maksymalna cena ustalana przez rząd dla określonego dobra lub usługi."},
    {english: "price floor - A price floor is a minimum price set by the government for a particular good or service", polish: "dolna granica ceny - Dolna granica ceny to minimalna cena ustalana przez rząd dla określonego dobra lub usługi."},
    {english: "perfectly competitive market - A perfectly competitive market is one where no single buyer or seller can influence the price of a product", polish: "doskonale konkurencyjny rynek - Doskonale konkurencyjny rynek to rynek, na którym żaden pojedynczy kupujący ani sprzedający nie mogą wpłynąć na cenę produktu."},
    {english: "barrier to entry - A barrier to entry is a factor that prevents or makes it difficult for new firms to enter a market", polish: "bariera wejścia - Bariera wejścia to czynnik, który uniemożliwia lub utrudnia nowym firmom wejście na rynek."},
    {english: "natural monopoly - A natural monopoly occurs when a single firm can produce the entire supply of a good or service at a lower cost than multiple firms", polish: "monopol naturalny - Monopol naturalny występuje, gdy jedna firma może wyprodukować całą podaż dobra lub usługi po niższym koszcie niż kilka firm."},
    {english: "oligopolistic market - An oligopolistic market is a market structure where a few large firms dominate and control the majority of the market share", polish: "rynek oligopolistyczny - Rynek oligopolistyczny to struktura rynku, w której kilka dużych firm dominuje i kontroluje większość udziału w rynku."},
    {english: "collusion - Collusion occurs when firms in an oligopoly work together to set prices or reduce competition", polish: "zmowa - Zmowa występuje, gdy firmy w oligopolu współpracują, aby ustalić ceny lub zmniejszyć konkurencję."},
    {english: "price war - A price war is a competitive exchange between companies who continually lower prices to gain market share", polish: "wojna cenowa - Wojna cenowa to konkurencyjna wymiana pomiędzy firmami, które stale obniżają ceny, aby zdobyć udział w rynku."},
    {english: "consumer surplus - Consumer surplus is the difference between what a consumer is willing to pay for a good and what they actually pay", polish: "nadwyżka konsumenta - Nadwyżka konsumenta to różnica między tym, ile konsument jest gotów zapłacić za dobro, a tym, ile faktycznie zapłaci."},
    {english: "producer surplus - Producer surplus is the difference between the price a producer is willing to sell a good for and the price they actually receive", polish: "nadwyżka producenta - Nadwyżka producenta to różnica między ceną, którą producent jest gotów sprzedać dobro, a ceną, którą faktycznie otrzymuje."},
    {english: "deadweight loss - Deadweight loss is a loss of economic efficiency that occurs when market equilibrium is not achieved", polish: "strata dobrobytu - Strata dobrobytu to utrata efektywności gospodarczej, która występuje, gdy równowaga rynkowa nie jest osiągnięta."},
    {english: "public goods - Public goods are goods that are non-excludable and non-rivalrous, meaning they are available to everyone and one person's use does not reduce availability to others", polish: "dobra publiczne - Dobra publiczne to dobra, które są niedzielne i nierywalne, co oznacza, że są dostępne dla wszystkich, a korzystanie przez jedną osobę nie zmniejsza dostępności dla innych."},
    {english: "private goods - Private goods are goods that are excludable and rivalrous, meaning people can be prevented from using them and one person's use reduces the availability to others", polish: "dobra prywatne - Dobra prywatne to dobra, które są wykluczające i rywalizujące, co oznacza, że ​​ludzie mogą zostać powstrzymani od ich używania, a korzystanie przez jedną osobę zmniejsza dostępność dla innych."},
    {english: "monetary policy - Monetary policy refers to the actions taken by a country's central bank to control the money supply and interest rates to achieve economic objectives", polish: "polityka monetarna - Polityka monetarna odnosi się do działań podejmowanych przez bank centralny danego kraju w celu kontrolowania podaży pieniądza i stóp procentowych w celu osiągnięcia celów gospodarczych."},
    {english: "open market operations - Open market operations refer to the buying and selling of government securities by a country's central bank to control the money supply", polish: "operacje otwartego rynku - Operacje otwartego rynku to kupno i sprzedaż papierów wartościowych rządu przez bank centralny danego kraju w celu kontrolowania podaży pieniądza."},
    {english: "interest rates - Interest rates are the cost of borrowing money, expressed as a percentage of the loan amount", polish: "stopy procentowe - Stopy procentowe to koszt pożyczania pieniędzy, wyrażony jako procent kwoty pożyczki."},
    {english: "reserve requirement - A reserve requirement is the minimum amount of reserves a bank must hold, set by a country's central bank", polish: "wymóg rezerw - Wymóg rezerw to minimalna kwota rezerw, które bank musi utrzymywać, ustalana przez bank centralny danego kraju."},
    {english: "inflation targeting - Inflation targeting is a monetary policy strategy used by central banks to keep inflation within a specific range", polish: "cel inflacyjny - Cel inflacyjny to strategia polityki monetarnej stosowana przez banki centralne, mająca na celu utrzymanie inflacji w określonym zakresie."},
    {english: "quantitative easing - Quantitative easing is a non-conventional monetary policy where a central bank buys securities to increase the money supply", polish: "polityka luzowania ilościowego - Polityka luzowania ilościowego to niekonwencjonalna polityka monetarna, w której bank centralny kupuje papiery wartościowe w celu zwiększenia podaży pieniądza."},
    {english: "federal funds rate - The federal funds rate is the interest rate at which depository institutions lend reserve balances to other depository institutions overnight", polish: "stopa funduszy federalnych - Stopa funduszy federalnych to stopa procentowa, po której instytucje depozytowe pożyczają sobie rezerwy od innych instytucji depozytowych na noc."},
    {english: "currency peg - A currency peg is a policy in which a country's currency is tied to another currency, often the US dollar, to stabilize its exchange rate", polish: "wiążąca waluta - Wiążąca waluta to polityka, w której waluta danego kraju jest powiązana z inną walutą, często dolarem amerykańskim, w celu stabilizacji kursu wymiany."},
    {english: "capital flight - Capital flight occurs when there is a large-scale exit of financial assets from a country, typically due to economic instability or fear of political instability", polish: "ucieczka kapitału - Ucieczka kapitału ma miejsce, gdy dochodzi do masowego wyjścia aktywów finansowych z kraju, zazwyczaj z powodu niestabilności gospodarczej lub obawy przed niestabilnością polityczną."},
    {english: "economic growth - Economic growth refers to the increase in the production of goods and services in an economy over time", polish: "wzrost gospodarczy - Wzrost gospodarczy odnosi się do wzrostu produkcji dóbr i usług w gospodarce w określonym czasie."},
    {english: "gross domestic product (GDP) - GDP is the total value of all goods and services produced by a country over a specific period, typically one year", polish: "produkt krajowy brutto (PKB) - PKB to całkowita wartość wszystkich dóbr i usług wyprodukowanych przez kraj w określonym okresie, zazwyczaj w ciągu roku."},
    {english: "per capita income - Per capita income is the average income earned by each individual in a country, calculated by dividing the country's total income by its population", polish: "dochód per capita - Dochód per capita to średni dochód osiągany przez każdego obywatela w kraju, obliczany przez podzielenie całkowitego dochodu kraju przez jego ludność."},
    {english: "labor force - The labor force is the total number of people who are either employed or actively seeking employment in a country", polish: "siła robocza - Siła robocza to łączna liczba osób, które są zatrudnione lub aktywnie poszukują pracy w kraju."},
    {english: "unemployment rate - The unemployment rate is the percentage of people in the labor force who are unemployed and actively seeking work", polish: "stopa bezrobocia - Stopa bezrobocia to procent osób w sile roboczej, które są bezrobotne i aktywnie poszukują pracy."},
    {english: "inflation - Inflation is the rate at which the general level of prices for goods and services rises, leading to a decrease in the purchasing power of currency", polish: "inflacja - Inflacja to tempo, w jakim ogólny poziom cen dóbr i usług rośnie, prowadząc do spadku siły nabywczej waluty."},
    {english: "deflation - Deflation is the decrease in the general price level of goods and services in an economy over a period of time", polish: "deflacja - Deflacja to spadek ogólnego poziomu cen dóbr i usług w gospodarce w określonym czasie."},
    {english: "stagflation - Stagflation is an economic condition characterized by a combination of stagnant economic growth, high unemployment, and high inflation", polish: "stagflacja - Stagflacja to warunki gospodarcze charakteryzujące się połączeniem stagnacji wzrostu gospodarczego, wysokiego bezrobocia i wysokiej inflacji."},
    {english: "hyperinflation - Hyperinflation is an extremely high and typically accelerating inflation rate, often exceeding 50% per month", polish: "hiperinfacja - Hiperinfacja to niezwykle wysoka i zazwyczaj przyspieszająca stopa inflacji, często przekraczająca 50% miesięcznie."},
    {english: "monetary policy tools - Monetary policy tools are the methods used by a central bank to control the money supply and interest rates in an economy", polish: "narzędzia polityki monetarnej - Narzędzia polityki monetarnej to metody wykorzystywane przez bank centralny do kontrolowania podaży pieniądza i stóp procentowych w gospodarce."},
    {english: "fiscal policy - Fiscal policy refers to government spending and tax policies that influence economic activity", polish: "polityka fiskalna - Polityka fiskalna odnosi się do wydatków rządowych i polityki podatkowej, które wpływają na aktywność gospodarczą."},
    {english: "public debt - Public debt is the total amount of money a government owes to external creditors or domestic lenders", polish: "dług publiczny - Dług publiczny to całkowita kwota pieniędzy, którą rząd jest winny zagranicznym wierzycielom lub krajowym pożyczkodawcom."},
    {english: "budget deficit - A budget deficit occurs when a government's expenditures exceed its revenues", polish: "deficyt budżetowy - Deficyt budżetowy występuje, gdy wydatki rządu przekraczają jego dochody."},
    {english: "budget surplus - A budget surplus occurs when a government's revenues exceed its expenditures", polish: "nadwyżka budżetowa - Nadwyżka budżetowa występuje, gdy dochody rządu przekraczają jego wydatki."},
    {english: "trade balance - The trade balance is the difference between the value of a country's exports and imports", polish: "bilans handlowy - Bilans handlowy to różnica między wartością eksportu a importu danego kraju."},
    {english: "balance of payments - The balance of payments is a record of all financial transactions made between a country and the rest of the world", polish: "bilans płatniczy - Bilans płatniczy to zapis wszystkich transakcji finansowych dokonywanych między krajem a resztą świata."},
    {english: "current account - The current account is a component of the balance of payments that includes trade in goods and services, income, and current transfers", polish: "rachunek bieżący - Rachunek bieżący to składnik bilansu płatniczego, który obejmuje handel dobrami i usługami, dochody i transfery bieżące."},
    {english: "capital account - The capital account is a component of the balance of payments that tracks capital transfers and financial assets", polish: "rachunek kapitałowy - Rachunek kapitałowy to składnik bilansu płatniczego, który śledzi transfery kapitałowe i aktywa finansowe."}

];

let selectedWords = [];
let currentIndex = 0;
let isEnglishToPolish = true;
let score = 0;
let answerGiven = false; // Track if an answer has been given
let isSpeakingEnabled = false; // Track if speaking is enabled

// DOM Elements
const container = document.getElementById("containerAnswer");
const wordDisplay = document.getElementById('wordDisplay');
const userInput = document.getElementById('userInput');
const submitBtn = document.getElementById('submitBtn');
const result = document.getElementById('result');
const nextBtn = document.getElementById('nextBtn');
const optionsContainer = document.getElementById('optionsContainer');
const translationDisplay = document.getElementById('translationDisplay');
const toggleTranslationBtn = document.getElementById('toggleTranslationBtn');
const switchLanguageBtn = document.getElementById('switchLanguageBtn');
const toggleSpeakBtn = document.getElementById('toggleSpeakBtn'); // New button for toggling speaking

// Initialization
function init() {
    selectedWords = words.slice(); // Select all words
    currentIndex = 0;
    translationDisplay.style.display = 'none'; // Hide translation by default
    displayWord(); // Display the first word
}

// Displaying the word
function displayWord() {
    if (selectedWords.length === 0) {
        result.textContent = "Nie wybrano słówek do nauki!";
        return;
    }

    const currentWord = isEnglishToPolish ? selectedWords[currentIndex].english : selectedWords[currentIndex].polish;
    wordDisplay.textContent = currentWord;
    generateOptions(isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english);
    userInput.value = '';
    result.textContent = '';

    // Speak the word only if speaking is enabled
    if (isSpeakingEnabled) {
        speakWord(); // Automatically speak the displayed word
    }

    // Update the translation display
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    translationDisplay.textContent = correctTranslation; // Show the current translation
}

// Function to speak the current word
function speakWord() {
    const currentWord = wordDisplay.textContent; // Read the word from the wordDisplay div
    const utterance = new SpeechSynthesisUtterance(currentWord);
    utterance.lang = isEnglishToPolish ? 'en-US' : 'pl-PL'; // Set language
    window.speechSynthesis.speak(utterance);
}

// Select words
document.querySelectorAll('.word-select-btn').forEach(button => {
    button.addEventListener('click', () => {
        const count = button.getAttribute('data-count');
        if (count === 'all') {
            selectedWords = words.slice(); // Select all words
        } else {
            const num = Math.min(parseInt(count), words.length);
            selectedWords = getRandomWords(words, num); // Select random words
        }
        currentIndex = 0;
        result.textContent = `Wybrano ${selectedWords.length} słówek do nauki.`; // Display information
        setTimeout(displayWord, 2000); // Display the first word
    });
});

// Random word selection function
function getRandomWords(sourceArray, count) {
    const shuffled = sourceArray.slice().sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
}

// Generating options for selection
function generateOptions(correctAnswer) {
    optionsContainer.innerHTML = ''; // Clear previous options

    const options = [correctAnswer];
    while (options.length < 4) {
        const randomWord = selectedWords[Math.floor(Math.random() * selectedWords.length)];
        if (isEnglishToPolish) {
            if (!options.includes(randomWord.polish)) options.push(randomWord.polish);
        } else {
            if (!options.includes(randomWord.english)) options.push(randomWord.english);
        }
    }

    shuffle(options); // Shuffle options

    options.forEach(option => {
        const btn = document.createElement('button');
        btn.textContent = option;
        btn.className = 'option-btn';
        btn.addEventListener('click', () => checkAnswer(option, correctAnswer));
        optionsContainer.appendChild(btn);
    });
}

// Check the answer
function checkAnswer(selected, correct) {
    if (answerGiven) return; // If an answer has already been given, do nothing

    const isCorrect = selected === correct || userInput.value.trim().toLowerCase() === correct.toLowerCase();
    
    if (isCorrect) {
        result.textContent = "Dobrze!";
        score++; // Increase score
        container.classList.add('bounce'); // Bounce animation

        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-yellow'));
        toggleTranslationBtn.classList.add("BtnGreen");
        switchLanguageBtn.classList.add("BtnGreen");
        nextBtn.classList.add("nextBtnGreen");
        submitBtn.classList.add("submitBtnGreen");
        toggleSpeakBtn.classList.add("BtnGreen");

        // Wait 2 seconds, then show the next word
        setTimeout(() => {
            currentIndex = (currentIndex + 1) % selectedWords.length; // Move to the next word
            answerGiven = false; // Reset state
            displayWord(); // Display new word
        }, 600);

        setTimeout(() => {
            container.classList.remove('bounce');
            buttons.forEach(button => button.classList.remove('btn-yellow'));
            toggleTranslationBtn.classList.remove("BtnGreen");
            switchLanguageBtn.classList.remove("BtnGreen");
            nextBtn.classList.remove("nextBtnGreen");
            submitBtn.classList.remove("submitBtnGreen");
            toggleSpeakBtn.classList.remove("BtnGreen");
        }, 600);
    } else {
        result.textContent = `Źle! Poprawne tłumaczenie to: ${correct}`;
        container.classList.add('shake'); // Shake animation

        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-red'));
        toggleTranslationBtn.classList.add("btn-red");
        switchLanguageBtn.classList.add("btn-red");
        nextBtn.classList.add("nextBtnRed");
        submitBtn.classList.add("submitBtnRed");
        toggleSpeakBtn.classList.add("btn-red");

        setTimeout(() => {
            container.classList.remove('shake');
            buttons.forEach(button => button.classList.remove('btn-red'));
            toggleTranslationBtn.classList.remove("btn-red");
            switchLanguageBtn.classList.remove("btn-red");
            nextBtn.classList.remove("nextBtnRed");
            submitBtn.classList.remove("submitBtnRed");
            toggleSpeakBtn.classList.remove("btn-red");
        }, 600);
    }

    answerGiven = true; // Mark that an answer has been given
}

// Handle submit button click
submitBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    checkAnswer(null, correctTranslation);
});

// Handle next button click
nextBtn.addEventListener('click', () => {
    if (!answerGiven) return; // If an answer hasn't been given, do nothing
    currentIndex = (currentIndex + 1) % selectedWords.length; // Move to the next word (cyclically)
    answerGiven = false; // Reset state
    displayWord();
});

// Toggle translation visibility
toggleTranslationBtn.addEventListener('click', () => {
    if (translationDisplay.style.display === 'none' || !translationDisplay.style.display) {
        translationDisplay.style.display = 'block'; // Show the translation
    } else {
        translationDisplay.style.display = 'none'; // Hide the translation
    }
});

// Switch language
switchLanguageBtn.addEventListener('click', () => {
    isEnglishToPolish = !isEnglishToPolish; // Change language direction
    displayWord(); // Refresh displayed word
});

// Toggle speaking
toggleSpeakBtn.addEventListener('click', () => {
    isSpeakingEnabled = !isSpeakingEnabled; // Toggle speaking on/off
    toggleSpeakBtn.innerHTML = isSpeakingEnabled ? '<i class="fa-solid fa-volume-low"></i>' : '<i class="fa-solid fa-volume-low"></i>'; // Update button text
});

// Initialization
init();

// Shuffle function
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

// Toggle word selection container
const toggleButton = document.getElementById('hideButton');
const myDiv = document.getElementById('wordSelectContainer');

toggleButton.addEventListener('click', () => {
    myDiv.style.display = myDiv.style.display === 'none' ? 'block' : 'none'; // Toggle visibility
});