const words = [
    { english: "abject", polish: "nędzny" },
    { english: "abstruse", polish: "niezrozumiały" },
    { english: "acquiescent", polish: "uległy" },
    { english: "adulation", polish: "pochlebstwo" },
    { english: "adverse", polish: "niekorzystny" },
    { english: "affluent", polish: "zamożny" },
    { english: "altruistic", polish: "altruistyczny" },
    { english: "antagonize", polish: "antagonizować" },
    { english: "archaic", polish: "archaiczny" },
    { english: "ascertain", polish: "ustalić" },
    { english: "aspire", polish: "dążyć" },
    { english: "assuage", polish: "łagodzić" },
    { english: "audacious", polish: "śmiały" },
    { english: "bane", polish: "klątwa" },
    { english: "bellicose", polish: "wojowniczy" },
    { english: "benign", polish: "łagodny" },
    { english: "blithe", polish: "beztroski" },
    { english: "bucolic", polish: "sielankowy" },
    { english: "cacophony", polish: "kakofonia" },
    { english: "capricious", polish: "kapryśny" },
    { english: "caustic", polish: "żrący" },
    { english: "censure", polish: "potępienie" },
    { english: "chronic", polish: "przewlekły" },
    { english: "cognizant", polish: "świadomy" },
    { english: "commensurate", polish: "proporcjonalny" },
    { english: "compelling", polish: "przekonujący" },
    { english: "complacent", polish: "zadowolony" },
    { english: "concur", polish: "zgadzać się" },
    { english: "conducive", polish: "sprzyjający" },
    { english: "connoisseur", polish: "koneser" },
    { english: "consolidate", polish: "zjednoczyć" },
    { english: "contrite", polish: "skruszony" },
    { english: "copious", polish: "obfity" },
    { english: "cryptic", polish: "tajemniczy" },
    { english: "culminate", polish: "osiągnąć szczyt" },
    { english: "curtail", polish: "ograniczać" },
    { english: "dauntless", polish: "nieustraszony" },
    { english: "debilitate", polish: "osłabiać" },
    { english: "deficit", polish: "deficyt" },
    { english: "deft", polish: "zręczny" },
    { english: "deliberate", polish: "zamierzony" },
    { english: "demure", polish: "skromny" },
    { english: "denigrate", polish: "zniechęcać" },
    { english: "deprecate", polish: "potępiać" },
    { english: "derivative", polish: "pochodny" },
    { english: "despot", polish: "despota" },
    { english: "diaphanous", polish: "przezroczysty" },
    { english: "dichotomy", polish: "dychotomia" },
    { english: "diligence", polish: "pracowitość" },
    { english: "diminutive", polish: "zdrobniony" },
    { english: "discerning", polish: "przenikliwy" },
    { english: "disdain", polish: "pogarda" },
    { english: "disparity", polish: "nierówność" },
    { english: "divergent", polish: "odmienny" },
    { english: "docile", polish: "uległy" },
    { english: "dormant", polish: "uśpiony" },
    { english: "dubious", polish: "wątpliwy" },
    { english: "ebullient", polish: "entuzjastyczny" },
    { english: "eccentric", polish: "ekscentryczny" },
    { english: "efficacy", polish: "skuteczność" },
    { english: "elated", polish: "uradowany" },
    { english: "eloquent", polish: "elokwentny" },
    { english: "emphatic", polish: "emfatyczny" },
    { english: "enervating", polish: "osłabiający" },
    { english: "ephemeral", polish: "przemijający" },
    { english: "equitable", polish: "sprawiedliwy" },
    { english: "esoteric", polish: "esoteryczny" },
    { english: "ethereal", polish: "eteryczny" },
    { english: "exacerbate", polish: "zaostrzać" },
    { english: "exemplary", polish: "wzorcowy" },
    { english: "exhaustive", polish: "wyczerpujący" },
    { english: "exonerate", polish: "uniewinnić" },
    { english: "exotic", polish: "egzotyczny" },
    { english: "expedite", polish: "przyspieszać" },
    { english: "extant", polish: "istniejący" },
    { english: "facetious", polish: "żartobliwy" },
    { english: "fallacious", polish: "błędny" },
    { english: "fathomable", polish: "do pojęcia" },
    { english: "fervor", polish: "zapał" },
    { english: "flabbergasted", polish: "zaskoczony" },
    { english: "flourish", polish: "kwitnąć" },
    { english: "fortuitous", polish: "przypadkowy" },
    { english: "frugal", polish: "oszczędny" },
    { english: "garrulous", polish: "gadaty" },
    { english: "germinate", polish: "kiełkować" },
    { english: "goad", polish: "podżegać" },
    { english: "grievous", polish: "ciężki" },
    { english: "haphazard", polish: "chaotyczny" },
    { english: "harangue", polish: "przemowa" },
    { english: "hedonistic", polish: "hedonistyczny" },
    { english: "herald", polish: "zapowiadać" },
    { english: "hermetic", polish: "hermetyczny" },
    { english: "hypothetical", polish: "hipotetyczny" },
    { english: "iconoclastic", polish: "ikonoklastyczny" },
    { english: "immutable", polish: "niezmienny" },
    { english: "impasse", polish: "martwy punkt" },
    { english: "impetuous", polish: "impulsywny" },
    { english: "implacable", polish: "nieprzejednany" },
    { english: "inane", polish: "pusty" },
    { english: "incandescent", polish: "żarzący" },
    { english: "incognito", polish: "nieznany" },
    { english: "indigenous", polish: "rdzenny" },
    { english: "inexorable", polish: "nieubłagany" },
    { english: "innocuous", polish: "nieszkodliwy" },
    { english: "insatiable", polish: "nienasycony" },
    { english: "insipid", polish: "mdły" },
    { english: "insular", polish: "wyspiarski" },
    { english: "integral", polish: "integralny" },
    { english: "intermittent", polish: "przerywany" },
    { english: "intractable", polish: "uparty" },
    { english: "inundate", polish: "zalewać" },
    { english: "irreverent", polish: "bezczelny" },
    { english: "jubilant", polish: "radosny" },
    { english: "juxtaposition", polish: "zestawienie" },
    { english: "lackadaisical", polish: "leniwy" },
    { english: "laudable", polish: "godny pochwały" },
    { english: "lethargic", polish: "ospaly" },
    { english: "lucid", polish: "przejrzysty" },
    { english: "malicious", polish: "złośliwy" },
    { english: "mendacious", polish: "kłamliwy" },
    { english: "meticulous", polish: "dokładny" },
    { english: "mirthful", polish: "radosny" },
    { english: "morose", polish: "ponury" },
    { english: "mundane", polish: "przyziemny" },
    { english: "nefarious", polish: "nikczemny" },
    { english: "nuance", polish: "niuanse" },
    { english: "obfuscate", polish: "mieszać" },
    { english: "oblivion", polish: "zapomnienie" },
    { english: "obstinate", polish: "uparty" },
    { english: "obviate", polish: "unikać" },
    { english: "occult", polish: "ukryty" },
    { english: "opulent", polish: "bogaty" },
    { english: "ostentatious", polish: "ostentacyjny" },
    { english: "paradigm", polish: "paradygmat" },
    { english: "parody", polish: "parodia" },
    { english: "patronage", polish: "patronat" },
    { english: "pedantic", polish: "pedantyczny" },
    { english: "pervasive", polish: "wszechobecny" },
    { english: "phlegmatic", polish: "flegmatyczny" },
    { english: "placid", polish: "spokojny" },
    { english: "plausible", polish: "wiarygodny" },
    { english: "polyglot", polish: "poliglot" },
    { english: "pragmatic", polish: "praktyczny" },
    { english: "precarious", polish: "niepewny" },
    { english: "prodigious", polish: "gigantyczny" },
    { english: "prolific", polish: "płodny" },
    { english: "prosaic", polish: "prozaiczny" },
    { english: "pugnacious", polish: "agresywny" },
    { english: "quandary", polish: "kłopot" },
    { english: "quintessential", polish: "kwintesencjalny" },
    { english: "quizzical", polish: "zdziwiony" },
    { english: "rambunctious", polish: "hałaśliwy" },
    { english: "rapacious", polish: "chciwy" },
    { english: "rebuke", polish: "zbesztać" },
    { english: "recalcitrant", polish: "oporny" },
    { english: "recapitulate", polish: "streszczać" },
    { english: "reciprocate", polish: "odwdzięczać się" },
    { english: "reclusive", polish: "izolowany" },
    { english: "refute", polish: "obalić" },
    { english: "reproach", polish: "wyrzut" },
    { english: "resilient", polish: "odporny" },
    { english: "reticent", polish: "małomówny" },
    { english: "sanguine", polish: "optymistyczny" },
    { english: "scrupulous", polish: "skrupulatny" },
    { english: "sequester", polish: "ukrywać" },
    { english: "skeptical", polish: "sceptyczny" },
    { english: "stoic", polish: "stoicki" },
    { english: "surreptitious", polish: "potajemny" },
    { english: "sycophant", polish: "podlizuch" },
    { english: "taciturn", polish: "małomówny" },
    { english: "temporal", polish: "czasowy" },
    { english: "torrid", polish: "upalny" },
    { english: "transient", polish: "przemijający" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "vapid", polish: "mdły" },
    { english: "verdant", polish: "zielony" },
    { english: "vex", polish: "denerwować" },
    { english: "vindicate", polish: "uzasadniać" },
    { english: "vociferous", polish: "hałaśliwy" },
    { english: "whimsical", polish: "kapryśny" },
    { english: "zealous", polish: "gorliwy" },
    { english: "abstruse", polish: "niezrozumiały" },
    { english: "accolade", polish: "wyróżnienie" },
    { english: "acquiesce", polish: "zgodzić się" },
    { english: "admonition", polish: "upomnienie" },
    { english: "affinity", polish: "sympatia" },
    { english: "aggrandize", polish: "powiększać" },
    { english: "alacrity", polish: "chęć" },
    { english: "animosity", polish: "animoszność" },
    { english: "antithesis", polish: "antyteza" },
    { english: "apathy", polish: "apatia" },
    { english: "apprehensive", polish: "obawiający się" },
    { english: "articulate", polish: "wyraźny" },
    { english: "assiduous", polish: "wytrwały" },
    { english: "augment", polish: "zwiększać" },
    { english: "baffling", polish: "zaskakujący" },
    { english: "benevolent", polish: "dobroduszny" },
    { english: "cacophony", polish: "kakofonia" },
    { english: "cajole", polish: "namawiać" },
    { english: "capricious", polish: "kapryśny" },
    { english: "cathartic", polish: "oczyszczający" },
    { english: "chicanery", polish: "oszustwo" },
    { english: "cogent", polish: "przekonujący" },
    { english: "complacent", polish: "zadowolony" },
    { english: "concur", polish: "zgadzać się" },
    { english: "conducive", polish: "sprzyjający" },
    { english: "congenial", polish: "sympatyczny" },
    { english: "conspicuous", polish: "rzucający się w oczy" },
    { english: "copious", polish: "obfity" },
    { english: "corroborate", polish: "potwierdzać" },
    { english: "cursory", polish: "pobieżny" },
    { english: "debilitate", polish: "osłabiać" },
    { english: "defunct", polish: "wygasły" },
    { english: "deference", polish: "szacunek" },
    { english: "deluge", polish: "powódź" },
    { english: "delineate", polish: "wytyczyć" },
    { english: "detrimental", polish: "szkodliwy" },
    { english: "dichotomy", polish: "dychotomia" },
    { english: "disdain", polish: "pogarda" },
    { english: "disparage", polish: "umniejszać" },
    { english: "disseminate", polish: "rozpowszechniać" },
    { english: "dissonant", polish: "dysonansowy" },
    { english: "ebullient", polish: "entuzjastyczny" },
    { english: "egregious", polish: "rażący" },
    { english: "elucidate", polish: "wyjaśniać" },
    { english: "emulate", polish: "naśladować" },
    { english: "enervate", polish: "osłabiać" },
    { english: "enigmatic", polish: "tajemniczy" },
    { english: "ephemeral", polish: "przemijający" },
    { english: "equanimity", polish: "spokój" },
    { english: "exacerbate", polish: "pogarszać" },
    { english: "exemplary", polish: "wzorcowy" },
    { english: "extrapolate", polish: "ekstrapolować" },
    { english: "fathom", polish: "pojąć" },
    { english: "fervent", polish: "gorliwy" },
    { english: "flamboyant", polish: "ekstrawagancki" },
    { english: "fortuitous", polish: "przypadkowy" },
    { english: "garrulous", polish: "gadaty" },
    { english: "gregarious", polish: "towarzyski" },
    { english: "harangue", polish: "przemowa" },
    { english: "hedonism", polish: "hedonizm" },
    { english: "herculean", polish: "herkulesowy" },
    { english: "histrionic", polish: "histrioniczny" },
    { english: "hubris", polish: "pycha" },
    { english: "iconoclast", polish: "ikonoklasta" },
    { english: "immutable", polish: "niezmienny" },
    { english: "impasse", polish: "martwy punkt" },
    { english: "impetuous", polish: "impulsywny" },
    { english: "inane", polish: "pusty" },
    { english: "incorrigible", polish: "niepoprawny" },
    { english: "indomitable", polish: "niezłomny" },
    { english: "ineffable", polish: "niewypowiedziany" },
    { english: "innate", polish: "wrodzony" },
    { english: "insidious", polish: "podstępny" },
    { english: "insipid", polish: "mdły" },
    { english: "integrity", polish: "integralność" },
    { english: "interminable", polish: "nieskończony" },
    { english: "intrinsic", polish: "wewnętrzny" },
    { english: "invective", polish: "inwektywa" },
    { english: "jubilant", polish: "radosny" },
    { english: "juxtaposition", polish: "zestawienie" },
    { english: "lackadaisical", polish: "leniwy" },
    { english: "laud", polish: "chwalać" },
    { english: "legitimate", polish: "legitny" },
    { english: "malleable", polish: "plastyczny" },
    { english: "meticulous", polish: "dokładny" },
    { english: "mollify", polish: "łagodzić" },
    { english: "nefarious", polish: "niegodziwy" },
    { english: "obfuscate", polish: "zaciemniać" },
    { english: "oblivious", polish: "nieświadomy" },
    { english: "opulent", polish: "bogaty" },
    { english: "ostentatious", polish: "ostentacyjny" },
    { english: "paradigm", polish: "paradygmat" },
    { english: "pedantic", polish: "pedantyczny" },
    { english: "pervasive", polish: "wszechobecny" },
    { english: "phlegmatic", polish: "flegmatyczny" },
    { english: "precarious", polish: "niepewny" },
    { english: "predecessor", polish: "poprzednik" },
    { english: "procrastinate", polish: "zwlekać" },
    { english: "prolific", polish: "płodny" },
    { english: "quintessential", polish: "kwintesencjalny" },
    { english: "rancorous", polish: "zgorzkniały" },
    { english: "reclusive", polish: "izolowany" },
    { english: "reiterate", polish: "powtarzać" },
    { english: "rejuvenate", polish: "odmładzać" },
    { english: "remorse", polish: "wyrzuty sumienia" },
    { english: "repudiate", polish: "odrzucać" },
    { english: "rescind", polish: "unieważnić" },
    { english: "sanguine", polish: "optymistyczny" },
    { english: "satiate", polish: "nasycić" },
    { english: "scintillating", polish: "iskrzący" },
    { english: "serendipity", polish: "szczęśliwy zbieg okoliczności" },
    { english: "skeptical", polish: "sceptyczny" },
    { english: "spurious", polish: "fałszywy" },
    { english: "stoic", polish: "stoicki" },
    { english: "tangible", polish: "namacalny" },
    { english: "tenacious", polish: "uparty" },
    { english: "tirade", polish: "tirada" },
    { english: "transient", polish: "przemijający" },
    { english: "traverse", polish: "przemierzać" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "unprecedented", polish: "bezprecedensowy" },
    { english: "vapid", polish: "mdły" },
    { english: "vicarious", polish: "pośredni" },
    { english: "vindicate", polish: "uzasadniać" },
    { english: "voracious", polish: "żarłoczny" },
    { english: "wary", polish: "ostrożny" },
    { english: "zeal", polish: "zapał" },
    { english: "abate", polish: "osłabiać" },
    { english: "aberration", polish: "odchylenie" },
    { english: "abrogate", polish: "uchylać" },
    { english: "adroit", polish: "zręczny" },
    { english: "alleviate", polish: "łagodzić" },
    { english: "anecdote", polish: "anekdota" },
    { english: "apocryphal", polish: "apokryficzny" },
    { english: "arcane", polish: "tajemny" },
    { english: "artifice", polish: "sztuczka" },
    { english: "aversion", polish: "odraza" },
    { english: "banal", polish: "banalny" },
    { english: "beguile", polish: "zwodzić" },
    { english: "benevolence", polish: "dobroć" },
    { english: "bifurcate", polish: "rozdzielać" },
    { english: "blatant", polish: "jawny" },
    { english: "candid", polish: "szczery" },
    { english: "capitulate", polish: "poddać się" },
    { english: "censure", polish: "potępienie" },
    { english: "chagrin", polish: "zmartwienie" },
    { english: "clarion", polish: "przejrzysty" },
    { english: "cogitate", polish: "myśleć" },
    { english: "commend", polish: "pochwalać" },
    { english: "compunction", polish: "wyrzuty sumienia" },
    { english: "conjecture", polish: "domysł" },
    { english: "conspicuousness", polish: "rzucający się w oczy" },
    { english: "construe", polish: "interpretować" },
    { english: "contrive", polish: "konstruować" },
    { english: "copiousness", polish: "obfitość" },
    { english: "deference", polish: "szacunek" },
    { english: "devoid", polish: "pozbawiony" },
    { english: "diligent", polish: "pracowity" },
    { english: "diminutive", polish: "zdrobniony" },
    { english: "discrepancy", polish: "rozbieżność" },
    { english: "disparaging", polish: "umniejszający" },
    { english: "divest", polish: "pozbawić" },
    { english: "echelon", polish: "szereg" },
    { english: "efficacious", polish: "skuteczny" },
    { english: "egregiously", polish: "rażąco" },
    { english: "elusive", polish: "nieuchwytny" },
    { english: "empathy", polish: "empatia" },
    { english: "enigma", polish: "enigmatyczny" },
    { english: "epitome", polish: "ucieleśnienie" },
    { english: "eschew", polish: "unikać" },
    { english: "ethereal", polish: "eteryczny" },
    { english: "exemplify", polish: "ilustrować" },
    { english: "expendable", polish: "nieistotny" },
    { english: "extemporaneous", polish: "improwizowany" },
    { english: "facilitate", polish: "ułatwiać" },
    { english: "flourish", polish: "kwitnąć" },
    { english: "fortify", polish: "umacniać" },
    { english: "garner", polish: "gromadzić" },
    { english: "germane", polish: "związany" },
    { english: "goad", polish: "podżegać" },
    { english: "grudging", polish: "niechętny" },
    { english: "hallowed", polish: "święty" },
    { english: "hegemony", polish: "hegemonia" },
    { english: "hubristic", polish: "pychowy" },
    { english: "immutable", polish: "niezmienny" },
    { english: "impertinent", polish: "bezczelny" },
    { english: "impervious", polish: "nieprzenikniony" },
    { english: "impetuously", polish: "impulsywnie" },
    { english: "impugn", polish: "kwestionować" },
    { english: "incessant", polish: "nieustanny" },
    { english: "incongruous", polish: "niespójny" },
    { english: "indulgent", polish: "wyrozumiały" },
    { english: "inexorable", polish: "nieubłagany" },
    { english: "intrepid", polish: "nieustraszony" },
    { english: "invincible", polish: "niewinny" },
    { english: "juxtapose", polish: "zestawiać" },
    { english: "keen", polish: "ostry" },
    { english: "lackluster", polish: "bezbarwny" },
    { english: "lament", polish: "żałować" },
    { english: "litigious", polish: "procesowy" },
    { english: "loquacious", polish: "gadający" },
    { english: "lucrative", polish: "lukratywny" },
    { english: "magnanimous", polish: "wielkoduszny" },
    { english: "malleable", polish: "plastyczny" },
    { english: "metaphor", polish: "metafora" },
    { english: "neologism", polish: "neologizm" },
    { english: "obsequious", polish: "służalczy" },
    { english: "ominous", polish: "złowieszczy" },
    { english: "opportune", polish: "dogodny" },
    { english: "paradigm", polish: "paradygmat" },
    { english: "paragon", polish: "wzór" },
    { english: "patronize", polish: "patronować" },
    { english: "pedagogue", polish: "nauczyciel" },
    { english: "perfunctory", polish: "pobieżny" },
    { english: "perspicacious", polish: "przenikliwy" },
    { english: "philanthropy", polish: "filantropia" },
    { english: "placate", polish: "łagodzić" },
    { english: "plethora", polish: "obfitość" },
    { english: "precarious", polish: "niepewny" },
    { english: "prevalent", polish: "powszechny" },
    { english: "proliferate", polish: "rozprzestrzeniać" },
    { english: "prosaic", polish: "prozaiczny" },
    { english: "quintessential", polish: "kwintesencjalny" },
    { english: "rancor", polish: "zgorzknienie" },
    { english: "rebuke", polish: "upomnienie" },
    { english: "reconciliation", polish: "pojednanie" },
    { english: "reclusive", polish: "izolowany" },
    { english: "relinquish", polish: "zrzec się" },
    { english: "reputable", polish: "renomowany" },
    { english: "retaliate", polish: "odwzajemnić" },
    { english: "sanguine", polish: "optymistyczny" },
    { english: "scrutinize", polish: "badać" },
    { english: "serene", polish: "spokojny" },
    { english: "sophisticated", polish: "wyrafinowany" },
    { english: "spurious", polish: "fałszywy" },
    { english: "staunch", polish: "wierny" },
    { english: "succinct", polish: "zwięzły" },
    { english: "tactile", polish: "dotykowy" },
    { english: "temerity", polish: "brawura" },
    { english: "tenacious", polish: "wytrwały" },
    { english: "tranquil", polish: "spokojny" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "unprecedented", polish: "bezprecedensowy" },
    { english: "venerable", polish: "czcigodny" },
    { english: "verbose", polish: "rozgadany" },
    { english: "vindictive", polish: "mściwy" },
    { english: "zeal", polish: "zapał" },
    { english: "abeyance", polish: "zawieszenie" },
    { english: "accolade", polish: "wyróżnienie" },
    { english: "acumen", polish: "bystrość" },
    { english: "adulate", polish: "schlebiać" },
    { english: "aggregate", polish: "agregat" },
    { english: "altruism", polish: "altruizm" },
    { english: "ameliorate", polish: "polepszać" },
    { english: "anomaly", polish: "anomalie" },
    { english: "antithesis", polish: "antyteza" },
    { english: "apotheosis", polish: "apoteoza" },
    { english: "arduous", polish: "trudny" },
    { english: "ascribe", polish: "przypisywać" },
    { english: "aspersion", polish: "oszczerstwo" },
    { english: "assiduous", polish: "wytrwały" },
    { english: "audacity", polish: "śmiałość" },
    { english: "auspice", polish: "zasiłek" },
    { english: "bane", polish: "zguba" },
    { english: "behemoth", polish: "behemot" },
    { english: "bellicosity", polish: "wojowniczość" },
    { english: "benevolent", polish: "dobroduszny" },
    { english: "blasphemy", polish: "bluźnierstwo" },
    { english: "cajole", polish: "namawiać" },
    { english: "camaraderie", polish: "towarzyskość" },
    { english: "capriciousness", polish: "kapryśność" },
    { english: "catharsis", polish: "katarsis" },
    { english: "cogitation", polish: "rozmyślanie" },
    { english: "commensurate", polish: "proporcjonalny" },
    { english: "compendium", polish: "kompendium" },
    { english: "conflation", polish: "zlewanie" },
    { english: "congeniality", polish: "sympatyczność" },
    { english: "conjectural", polish: "domysłowy" },
    { english: "consolidate", polish: "utrwalać" },
    { english: "contingent", polish: "warunkowy" },
    { english: "copiousness", polish: "obfitość" },
    { english: "corollary", polish: "wniosek" },
    { english: "countermand", polish: "odwoływać" },
    { english: "defer", polish: "odroczyć" },
    { english: "degradation", polish: "degradacja" },
    { english: "deliberation", polish: "rozważanie" },
    { english: "demagogue", polish: "demagog" },
    { english: "deprive", polish: "pozbawić" },
    { english: "despot", polish: "despota" },
    { english: "destitute", polish: "ubożuch" },
    { english: "dichotomous", polish: "dychotomiczny" },
    { english: "diligence", polish: "pracowitość" },
    { english: "disenfranchise", polish: "pozbawiać praw" },
    { english: "disparity", polish: "rozbieżność" },
    { english: "dissemination", polish: "rozpowszechnianie" },
    { english: "divergent", polish: "rozbieżny" },
    { english: "ebullience", polish: "entuzjazm" },
    { english: "edification", polish: "edukacja" },
    { english: "effrontery", polish: "bezczelność" },
    { english: "egregiousness", polish: "rażącość" },
    { english: "elucidation", polish: "wyjaśnienie" },
    { english: "empathy", polish: "empatia" },
    { english: "emphasis", polish: "nacisk" },
    { english: "emulation", polish: "naśladowanie" },
    { english: "equanimity", polish: "spokój" },
    { english: "equivocation", polish: "niejasność" },
    { english: "esoteric", polish: "esoteryczny" },
    { english: "exacerbation", polish: "pogorszenie" },
    { english: "exemplification", polish: "ilustracja" },
    { english: "exhaustive", polish: "wyczerpujący" },
    { english: "expenditure", polish: "wydatek" },
    { english: "facilitation", polish: "ułatwienie" },
    { english: "fallacious", polish: "błędny" },
    { english: "ferocious", polish: "dziki" },
    { english: "finesse", polish: "finezja" },
    { english: "fortitude", polish: "męstwo" },
    { english: "garrulity", polish: "gadatliwość" },
    { english: "grandeur", polish: "wspaniałość" },
    { english: "harbinger", polish: "zapowiedź" },
    { english: "hedonistic", polish: "hedonistyczny" },
    { english: "herald", polish: "herald" },
    { english: "hubris", polish: "pycha" },
    { english: "hypothetical", polish: "hipotetyczny" },
    { english: "iconic", polish: "ikoniczny" },
    { english: "idiosyncratic", polish: "idiosynkratyczny" },
    { english: "imminent", polish: "nieuchronny" },
    { english: "impede", polish: "utrudniać" },
    { english: "implicate", polish: "angażować" },
    { english: "impunity", polish: "bezkarność" },
    { english: "incongruity", polish: "niedopasowanie" },
    { english: "indifferent", polish: "obojętny" },
    { english: "inevitability", polish: "nieuniknioność" },
    { english: "innovation", polish: "innowacja" },
    { english: "inscrutable", polish: "nieprzenikniony" },
    { english: "insidiousness", polish: "podstępność" },
    { english: "insinuate", polish: "sugestia" },
    { english: "integrate", polish: "integracja" },
    { english: "intrinsic", polish: "wewnętrzny" },
    { english: "invincible", polish: "niewinny" },
    { english: "irrevocable", polish: "nieodwołalny" },
    { english: "juxtaposition", polish: "zestawienie" },
    { english: "kaleidoscopic", polish: "kalejdoskopowy" },
    { english: "laudable", polish: "chwalebny" },
    { english: "legitimate", polish: "legitny" },
    { english: "luminous", polish: "luminescencyjny" },
    { english: "malicious", polish: "złośliwy" },
    { english: "meticulousness", polish: "dokładność" },
    { english: "miasma", polish: "miasma" },
    { english: "moratorium", polish: "moratorium" },
    { english: "mundanity", polish: "przyziemność" },
    { english: "neologistic", polish: "neologiczny" },
    { english: "obfuscation", polish: "zaciemnienie" },
    { english: "ostentatious", polish: "ostentacyjny" },
    { english: "paradigm", polish: "paradygmat" },
    { english: "parochialism", polish: "parafializm" },
    { english: "pedantry", polish: "pedanteria" },
    { english: "periphery", polish: "peryferia" },
    { english: "philosophical", polish: "filozoficzny" },
    { english: "plethora", polish: "plethora" },
    { english: "predilection", polish: "upodobanie" },
    { english: "prodigiousness", polish: "gigantyczność" },
    { english: "proliferation", polish: "proliferacja" },
    { english: "quintessence", polish: "kwintesencja" },
    { english: "reconcile", polish: "pojednać" },
    { english: "reluctance", polish: "niechęć" },
    { english: "resilience", polish: "odporność" },
    { english: "reticent", polish: "małomówny" },
    { english: "salubriousness", polish: "zdrowotność" },
    { english: "scintillate", polish: "iskrzyć" },
    { english: "spontaneity", polish: "spontaniczność" },
    { english: "superfluous", polish: "zbędny" },
    { english: "surreptitious", polish: "potajemny" },
    { english: "taciturnity", polish: "milczącość" },
    { english: "tangible", polish: "namacalny" },
    { english: "transcendence", polish: "transcendencja" },
    { english: "ubiquity", polish: "wszechobecność" },
    { english: "utilitarian", polish: "użyteczny" },
    { english: "venerability", polish: "czcigodność" },
    { english: "veracity", polish: "prawdziwość" },
    { english: "vicarious", polish: "pośredni" },
    { english: "vulnerability", polish: "wrażliwość" },
    { english: "warrant", polish: "gwarancja" },
    { english: "zealot", polish: "fanatyk" },
    { english: "abstruse", polish: "niezrozumiały" },
    { english: "acumen", polish: "bystrość" },
    { english: "admonish", polish: "upominać" },
    { english: "alleviate", polish: "łagodzić" },
    { english: "antipathy", polish: "antypatia" },
    { english: "apathy", polish: "apatia" },
    { english: "ascertain", polish: "ustalić" },
    { english: "aspire", polish: "dążyć" },
    { english: "avert", polish: "zapobiegać" },
    { english: "banal", polish: "banalny" },
    { english: "belie", polish: "przeczyć" },
    { english: "benign", polish: "łagodny" },
    { english: "bizarre", polish: "dziwaczny" },
    { english: "candid", polish: "szczery" },
    { english: "capitulate", polish: "poddać się" },
    { english: "caustic", polish: "żrący" },
    { english: "cogent", polish: "przekonujący" },
    { english: "collaborate", polish: "współpracować" },
    { english: "complacent", polish: "zadowolony" },
    { english: "concede", polish: "przyznać" },
    { english: "concur", polish: "zgadzać się" },
    { english: "construe", polish: "interpretować" },
    { english: "contentious", polish: "kontrowersyjny" },
    { english: "cursory", polish: "pobieżny" },
    { english: "debilitate", polish: "osłabiać" },
    { english: "deferential", polish: "posłuszny" },
    { english: "deliberate", polish: "celowy" },
    { english: "diligent", polish: "pracowity" },
    { english: "discrepancy", polish: "rozbieżność" },
    { english: "disdain", polish: "pogarda" },
    { english: "disseminate", polish: "rozpowszechniać" },
    { english: "dissonance", polish: "dysonans" },
    { english: "ebullient", polish: "entuzjastyczny" },
    { english: "eclectic", polish: "eklektyczny" },
    { english: "emulate", polish: "naśladować" },
    { english: "ephemeral", polish: "przemijający" },
    { english: "equivocate", polish: "mówić niejasno" },
    { english: "exacerbate", polish: "pogarszać" },
    { english: "exemplify", polish: "ilustrować" },
    { english: "fervent", polish: "gorliwy" },
    { english: "foible", polish: "słabość" },
    { english: "garrulous", polish: "gadaty" },
    { english: "grievous", polish: "ciężki" },
    { english: "hackneyed", polish: "oklepany" },
    { english: "impasse", polish: "martwy punkt" },
    { english: "incessant", polish: "nieustanny" },
    { english: "incredulous", polish: "niewierzący" },
    { english: "insipid", polish: "mdły" },
    { english: "intrepid", polish: "dzielny" },
    { english: "inundate", polish: "zalewać" },
    { english: "juxtapose", polish: "zestawiać" },
    { english: "kudos", polish: "uznanie" },
    { english: "laconic", polish: "lakoniczny" },
    { english: "lament", polish: "żałować" },
    { english: "macerate", polish: "nasiąkać" },
    { english: "mendacious", polish: "kłamliwy" },
    { english: "metamorphosis", polish: "metamorfoza" },
    { english: "naïve", polish: "naiwny" },
    { english: "neophyte", polish: "nowicjusz" },
    { english: "oblivion", polish: "zapomnienie" },
    { english: "obstinate", polish: "uparty" },
    { english: "palpable", polish: "namacalny" },
    { english: "parsimony", polish: "oszczędność" },
    { english: "patronize", polish: "patronować" },
    { english: "plausible", polish: "prawdopodobny" },
    { english: "quixotic", polish: "idealny" },
    { english: "rapacious", polish: "chciwy" },
    { english: "recalcitrant", polish: "oporny" },
    { english: "remonstrate", polish: "przeciwdziałać" },
    { english: "rescind", polish: "unieważnić" },
    { english: "reverberate", polish: "odbijać" },
    { english: "salient", polish: "rzucający się w oczy" },
    { english: "sanguine", polish: "optymistyczny" },
    { english: "scrutinize", polish: "badać" },
    { english: "serendipity", polish: "szczęśliwy zbieg okoliczności" },
    { english: "stoic", polish: "stoicki" },
    { english: "tacit", polish: "milczący" },
    { english: "tenuous", polish: "cienki" },
    { english: "transcend", polish: "przekraczać" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "unctuous", polish: "oleisty" },
    { english: "vacuous", polish: "pusty" },
    { english: "wry", polish: "sarkastyczny" },
    { english: "zenith", polish: "szczyt" },
    { english: "abjure", polish: "wyrzekać się" },
    { english: "abrogate", polish: "uchylać" },
    { english: "adroit", polish: "zręczny" },
    { english: "affable", polish: "towarzyski" },
    { english: "aggrandize", polish: "pomnażać" },
    { english: "alacrity", polish: "gotowość" },
    { english: "amalgamate", polish: "łączyć" },
    { english: "anathema", polish: "klątwa" },
    { english: "apocryphal", polish: "apokryficzny" },
    { english: "arcane", polish: "tajemny" },
    { english: "audacious", polish: "śmiały" },
    { english: "auspicious", polish: "pomyślny" },
    { english: "bellicose", polish: "wojowniczy" },
    { english: "bifurcate", polish: "rozdzielać" },
    { english: "blithe", polish: "beztroski" },
    { english: "cabal", polish: "spisek" },
    { english: "cacophony", polish: "hałas" },
    { english: "capricious", polish: "kapryśny" },
    { english: "cavil", polish: "czepiać się" },
    { english: "censorious", polish: "krytyczny" },
    { english: "chimerical", polish: "chimericzny" },
    { english: "churlish", polish: "niegrzeczny" },
    { english: "circumspect", polish: "ostrożny" },
    { english: "clandestine", polish: "potajemny" },
    { english: "coalesce", polish: "łączyć się" },
    { english: "complacency", polish: "zadowolenie" },
    { english: "conflagration", polish: "pożar" },
    { english: "congenial", polish: "sympatyczny" },
    { english: "conjecture", polish: "domysł" },
    { english: "connive", polish: "przymknąć oko" },
    { english: "conspicuous", polish: "rzucający się w oczy" },
    { english: "contumacious", polish: "nieposłuszny" },
    { english: "copious", polish: "obfity" },
    { english: "corroborate", polish: "potwierdzać" },
    { english: "covet", polish: "pragnąć" },
    { english: "credulous", polish: "łatwowierny" },
    { english: "cursory", polish: "pobieżny" },
    { english: "dauntless", polish: "nieustraszony" },
    { english: "deference", polish: "posłuszeństwo" },
    { english: "depravity", polish: "zepsucie" },
    { english: "derelict", polish: "porzucony" },
    { english: "desultory", polish: "chaotyczny" },
    { english: "diaphanous", polish: "przezroczysty" },
    { english: "dichotomy", polish: "dychotomia" },
    { english: "discerning", polish: "przenikliwy" },
    { english: "dispassionate", polish: "bezstronny" },
    { english: "divest", polish: "pozbawiać" },
    { english: "droll", polish: "dziwaczny" },
    { english: "effulgent", polish: "jasny" },
    { english: "egregious", polish: "rażący" },
    { english: "elucidate", polish: "wyjaśnić" },
    { english: "emaciated", polish: "wyniszczony" },
    { english: "emphatic", polish: "ekspresyjny" },
    { english: "enervate", polish: "osłabiać" },
    { english: "enigmatic", polish: "enigmatyczny" },
    { english: "ephemeral", polish: "krótkotrwały" },
    { english: "equanimity", polish: "spokój" },
    { english: "erratic", polish: "nieregularny" },
    { english: "eschew", polish: "unikać" },
    { english: "evanescent", polish: "ulotny" },
    { english: "exculpate", polish: "uniewinnić" },
    { english: "exemplary", polish: "przykładowy" },
    { english: "expedient", polish: "wygodny" },
    { english: "extemporaneous", polish: "improwizowany" },
    { english: "facilitate", polish: "ułatwiać" },
    { english: "fatuous", polish: "naiwny" },
    { english: "fervor", polish: "zapał" },
    { english: "florid", polish: "kwiatowy" },
    { english: "fortuitous", polish: "przypadkowy" },
    { english: "garrulous", polish: "gadaty" },
    { english: "germane", polish: "istotny" },
    { english: "grandiloquent", polish: "wielomówny" },
    { english: "gregarious", polish: "towarzyski" },
    { english: "harangue", polish: "wykład" },
    { english: "hegemony", polish: "hegemonia" },
    { english: "herculean", polish: "herkulesowy" },
    { english: "hibernation", polish: "hibernacja" },
    { english: "homogeneous", polish: "jednorodny" },
    { english: "hubris", polish: "pycha" },
    { english: "hyperbole", polish: "przesada" },
    { english: "iconoclast", polish: "ikonoklasta" },
    { english: "idiosyncrasy", polish: "idiosynkrazja" },
    { english: "ignoble", polish: "nikczemny" },
    { english: "illicit", polish: "nielegalny" },
    { english: "impasse", polish: "martwy punkt" },
    { english: "impecunious", polish: "biedny" },
    { english: "impervious", polish: "nieprzenikalny" },
    { english: "impetuous", polish: "impulsywny" },
    { english: "impugn", polish: "podważać" },
    { english: "inane", polish: "pusty" },
    { english: "inchoate", polish: "niedokończony" },
    { english: "incongruous", polish: "niezgodny" },
    { english: "incontrovertible", polish: "niepodważalny" },
    { english: "incorrigible", polish: "niepoprawny" },
    { english: "indefatigable", polish: "niestrudzony" },
    { english: "ineffable", polish: "niewypowiedziany" },
    { english: "inept", polish: "niezdarny" },
    { english: "insatiable", polish: "nienasycony" },
    { english: "insidious", polish: "podstępny" },
    { english: "insipid", polish: "mdły" },
    { english: "intrepid", polish: "dzielny" },
    { english: "irrefutable", polish: "niepodważalny" },
    { english: "jocular", polish: "żartobliwy" },
    { english: "juxtaposition", polish: "zestawienie" },
    { english: "kaleidoscope", polish: "kalejdoskop" },
    { english: "kismet", polish: "los" },
    { english: "lackluster", polish: "bezbarwny" },
    { english: "laudatory", polish: "pochwalny" },
    { english: "lethargy", polish: "letarg" },
    { english: "lucid", polish: "przejrzysty" },
    { english: "magnanimous", polish: "wielkoduszny" },
    { english: "malevolent", polish: "złośliwy" },
    { english: "malediction", polish: "klątwa" },
    { english: "malleable", polish: "plastyczny" },
    { english: "meticulous", polish: "dokładny" },
    { english: "moribund", polish: "umierający" },
    { english: "mundane", polish: "przyziemny" },
    { english: "nefarious", polish: "nikczemny" },
    { english: "neologism", polish: "neologizm" },
    { english: "nocturnal", polish: "nocny" },
    { english: "nonchalant", polish: "obojętny" },
    { english: "obfuscate", polish: "zaciemniać" },
    { english: "oblivious", polish: "nieświadomy" },
    { english: "obsequious", polish: "służalczy" },
    { english: "odious", polish: "odrażający" },
    { english: "opprobrium", polish: "hańba" },
    { english: "ostensible", polish: "pozorny" },
    { english: "panacea", polish: "panaceum" },
    { english: "paradox", polish: "paradoks" },
    { english: "parochial", polish: "parafialny" },
    { english: "pedantic", polish: "pedantyczny" },
    { english: "perfidious", polish: "zdradziecki" },
    { english: "perpetuate", polish: "utrwalać" },
    { english: "phlegmatic", polish: "flegmatyczny" },
    { english: "placate", polish: "uspokoić" },
    { english: "platitude", polish: "banalność" },
    { english: "poignant", polish: "przejmujący" },
    { english: "polemic", polish: "polemiczny" },
    { english: "pragmatic", polish: "pragmatyczny" },
    { english: "precocious", polish: "wcześniejszy" },
    { english: "preclude", polish: "uniemożliwić" },
    { english: "prodigious", polish: "gigantyczny" },
    { english: "prolific", polish: "płodny" },
    { english: "quaint", polish: "dziwaczny" },
    { english: "quandary", polish: "dylemat" },
    { english: "quintessential", polish: "kwintesencja" },
    { english: "rancorous", polish: "zgorzkniały" },
    { english: "rapacious", polish: "chciwy" },
    { english: "recalcitrant", polish: "oporny" },
    { english: "rejuvenate", polish: "odmładzać" },
    { english: "remonstrate", polish: "przeciwdziałać" },
    { english: "resilient", polish: "elastyczny" },
    { english: "rhetoric", polish: "retoryka" },
    { english: "sagacious", polish: "mądry" },
    { english: "salubrious", polish: "zdrowy" },
    { english: "salient", polish: "rzucający się w oczy" },
    { english: "sanctimonious", polish: "świętoszkowaty" },
    { english: "scintillating", polish: "iskrzący" },
    { english: "scrutinize", polish: "badać" },
    { english: "sequester", polish: "odizolować" },
    { english: "serendipity", polish: "szczęśliwy zbieg okoliczności" },
    { english: "soporific", polish: "usypiający" },
    { english: "spurious", polish: "fałszywy" },
    { english: "supercilious", polish: "arogancki" },
    { english: "surreptitious", polish: "potajemny" },
    { english: "taciturn", polish: "milczący" },
    { english: "tenacious", polish: "wytrwały" },
    { english: "therapeutic", polish: "terapeutyczny" },
    { english: "torrid", polish: "upalny" },
    { english: "transitory", polish: "przejściowy" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "unconscionable", polish: "niedopuszczalny" },
    { english: "vacillate", polish: "wahać się" },
    { english: "venerable", polish: "czcigodny" },
    { english: "vindicate", polish: "uzasadniać" },
    { english: "virulent", polish: "złośliwy" },
    { english: "volatile", polish: "niestabilny" },
    { english: "voracious", polish: "pożądliwy" },
    { english: "wheedle", polish: "łagodzić" },
    { english: "zealous", polish: "gorliwy" },
    { english: "abate", polish: "osłabiać" },
    { english: "aberration", polish: "odchylenie" },
    { english: "abstain", polish: "powstrzymywać się" },
    { english: "accolade", polish: "uznanie" },
    { english: "acquaintance", polish: "znajomość" },
    { english: "adulation", polish: "uwielbienie" },
    { english: "adversary", polish: "przeciwnik" },
    { english: "adverse", polish: "niekorzystny" },
    { english: "affinity", polish: "sympatia" },
    { english: "altruistic", polish: "altruistyczny" },
    { english: "ambivalence", polish: "ambiwalencja" },
    { english: "anecdote", polish: "anekdota" },
    { english: "antithesis", polish: "antyteza" },
    { english: "apathy", polish: "apatia" },
    { english: "apprehension", polish: "obawa" },
    { english: "ardent", polish: "żarliwy" },
    { english: "artifice", polish: "sztuczność" },
    { english: "aspire", polish: "dążyć" },
    { english: "assiduous", polish: "wytrwały" },
    { english: "atrocity", polish: "okropność" },
    { english: "austere", polish: "surowy" },
    { english: "autonomy", polish: "autonomia" },
    { english: "beguile", polish: "zwodzić" },
    { english: "belie", polish: "zaprzeczać" },
    { english: "benign", polish: "łagodny" },
    { english: "boisterous", polish: "hałaśliwy" },
    { english: "bolster", polish: "wspierać" },
    { english: "broadly", polish: "ogólnie" },
    { english: "cacophony", polish: "hałas" },
    { english: "candor", polish: "szczerość" },
    { english: "catharsis", polish: "oczyszczenie" },
    { english: "chastise", polish: "karcić" },
    { english: "chronic", polish: "przewlekły" },
    { english: "coherent", polish: "spójny" },
    { english: "colloquial", polish: "potoczny" },
    { english: "compelling", polish: "przekonujący" },
    { english: "complacent", polish: "zadowolony" },
    { english: "concise", polish: "zwięzły" },
    { english: "concur", polish: "zgadzać się" },
    { english: "conducive", polish: "sprzyjający" },
    { english: "connoisseur", polish: "znawca" },
    { english: "conspicuous", polish: "rzucający się w oczy" },
    { english: "contrived", polish: "wymyślony" },
    { english: "corroborate", polish: "potwierdzać" },
    { english: "culpable", polish: "winny" },
    { english: "cursory", polish: "pobieżny" },
    { english: "debacle", polish: "porażka" },
    { english: "deference", polish: "posłuszeństwo" },
    { english: "deplore", polish: "ubolewać" },
    { english: "desolate", polish: "opustoszały" },
    { english: "dichotomy", polish: "dychotomia" },
    { english: "discrepancy", polish: "rozbieżność" },
    { english: "disdain", polish: "lekceważenie" },
    { english: "disseminate", polish: "rozpowszechniać" },
    { english: "dissonance", polish: "dysonans" },
    { english: "diligent", polish: "pilny" },
    { english: "diminutive", polish: "malutki" },
    { english: "disparity", polish: "niesprawiedliwość" },
    { english: "efficacious", polish: "skuteczny" },
    { english: "egregious", polish: "rażący" },
    { english: "emulate", polish: "naśladować" },
    { english: "emulate", polish: "naśladować" },
    { english: "enervate", polish: "osłabiać" },
    { english: "enigmatic", polish: "enigmatyczny" },
    { english: "ephemeral", polish: "krótkotrwały" },
    { english: "equivocal", polish: "dwuznaczny" },
    { english: "erudite", polish: "uczony" },
    { english: "esoteric", polish: "ezoteryczny" },
    { english: "exacerbate", polish: "pogarszać" },
    { english: "exemplary", polish: "przykładowy" },
    { english: "exonerate", polish: "uniewinnić" },
    { english: "expedite", polish: "przyspieszać" },
    { english: "fervent", polish: "gorliwy" },
    { english: "flabbergasted", polish: "zaskoczony" },
    { english: "flamboyant", polish: "ekstrawagancki" },
    { english: "futile", polish: "daremny" },
    { english: "garrulous", polish: "gadaty" },
    { english: "germane", polish: "związany" },
    { english: "gluttonous", polish: "obżarty" },
    { english: "gratuitous", polish: "nieuzasadniony" },
    { english: "guile", polish: "podstęp" },
    { english: "harangue", polish: "wykład" },
    { english: "hedonistic", polish: "hedonistyczny" },
    { english: "herald", polish: "herold" },
    { english: "homogeneous", polish: "jednorodny" },
    { english: "hyperbole", polish: "przesada" },
    { english: "iconoclast", polish: "ikonoklasta" },
    { english: "idiosyncrasy", polish: "idiosynkrazja" },
    { english: "impasse", polish: "martwy punkt" },
    { english: "imperative", polish: "imperatywny" },
    { english: "implacable", polish: "nieprzejednany" },
    { english: "impunity", polish: "bezkarność" },
    { english: "inane", polish: "pusty" },
    { english: "incisive", polish: "ostry" },
    { english: "incontrovertible", polish: "niepodważalny" },
    { english: "incorrigible", polish: "niepoprawny" },
    { english: "indolent", polish: "leniwy" },
    { english: "ineffable", polish: "niewypowiedziany" },
    { english: "inexorable", polish: "niewzruszony" },
    { english: "insidious", polish: "podstępny" },
    { english: "intrepid", polish: "dzielny" },
    { english: "irreverent", polish: "niestosowny" },
    { english: "juxtaposition", polish: "zestawienie" },
    { english: "lackadaisical", polish: "leniwie" },
    { english: "languid", polish: "osłabiony" },
    { english: "laudable", polish: "godny pochwały" },
    { english: "lethargic", polish: "letargiczny" },
    { english: "malleable", polish: "plastyczny" },
    { english: "metamorphosis", polish: "metamorfoza" },
    { english: "misanthropic", polish: "antropofobiczny" },
    { english: "neophyte", polish: "nowicjusz" },
    { english: "obfuscate", polish: "zamieszać" },
    { english: "oblivious", polish: "nieświadomy" },
    { english: "occlude", polish: "zatykać" },
    { english: "opaque", polish: "nieprzezroczysty" },
    { english: "opulent", polish: "zamożny" },
    { english: "ostentatious", polish: "ostentacyjny" },
    { english: "paradigm", polish: "paradygmat" },
    { english: "paragon", polish: "wzór" },
    { english: "perfunctory", polish: "pobieżny" },
    { english: "pervasive", polish: "przenikający" },
    { english: "philanthropy", polish: "filantropia" },
    { english: "platitude", polish: "banalność" },
    { english: "pragmatic", polish: "pragmatyczny" },
    { english: "procrastinate", polish: "odkładać" },
    { english: "profound", polish: "głęboki" },
    { english: "pristine", polish: "nieskazitelny" },
    { english: "quandary", polish: "dylemat" },
    { english: "quixotic", polish: "idealistyczny" },
    { english: "rancor", polish: "zgorzknienie" },
    { english: "recluse", polish: "samotnik" },
    { english: "reproach", polish: "wyrzut" },
    { english: "rescind", polish: "unieważnić" },
    { english: "reticent", polish: "małomówny" },
    { english: "sagacious", polish: "mądry" },
    { english: "salient", polish: "rzucający się w oczy" },
    { english: "sanctimonious", polish: "świętoszkowaty" },
    { english: "scrupulous", polish: "sumienny" },
    { english: "sequester", polish: "odizolować" },
    { english: "soporific", polish: "usypiający" },
    { english: "sparse", polish: "rzadki" },
    { english: "stagnant", polish: "zastój" },
    { english: "stoic", polish: "stoicki" },
    { english: "strident", polish: "głośny" },
    { english: "substantiate", polish: "uzasadnić" },
    { english: "surreptitious", polish: "potajemny" },
    { english: "taciturn", polish: "milczący" },
    { english: "temerity", polish: "zuchwałość" },
    { english: "turbulent", polish: "burzliwy" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "unfathomable", polish: "niezgłębiony" },
    { english: "venerate", polish: "czcić" },
    { english: "verbose", polish: "wielosłowny" },
    { english: "viable", polish: "wykonalny" },
    { english: "vicarious", polish: "pośredni" },
    { english: "vindictive", polish: "mściwy" },
    { english: "volatile", polish: "niestabilny" },
    { english: "warrant", polish: "warrant" },
    { english: "wheedle", polish: "łagodzić" },
    { english: "zephyr", polish: "zefir" },
    { english: "abandon", polish: "porzucić" },
    { english: "abstract", polish: "abstrakcyjny" },
    { english: "acquiesce", polish: "zgodzić się" },
    { english: "acumen", polish: "przenikliwość" },
    { english: "admonish", polish: "upominać" },
    { english: "advocate", polish: "adwokat" },
    { english: "affluent", polish: "zamożny" },
    { english: "aggregate", polish: "agregat" },
    { english: "alleviate", polish: "łagodzić" },
    { english: "ambiguous", polish: "niejednoznaczny" },
    { english: "anomaly", polish: "anomalie" },
    { english: "antithesis", polish: "antyteza" },
    { english: "articulate", polish: "artykułować" },
    { english: "ascertain", polish: "ustalić" },
    { english: "assimilate", polish: "asimilować" },
    { english: "augmented", polish: "powiększony" },
    { english: "benevolent", polish: "życzliwy" },
    { english: "candid", polish: "szczery" },
    { english: "cathartic", polish: "oczyszczający" },
    { english: "coerce", polish: "zmuszać" },
    { english: "collaborate", polish: "współpracować" },
    { english: "commence", polish: "rozpocząć" },
    { english: "compromise", polish: "kompromis" },
    { english: "concur", polish: "zgadzać się" },
    { english: "condone", polish: "przepraszać" },
    { english: "contemplate", polish: "rozważać" },
    { english: "contradict", polish: "przeczyć" },
    { english: "convivial", polish: "towarzyski" },
    { english: "culminate", polish: "kulminować" },
    { english: "debilitate", polish: "osłabiać" },
    { english: "defer", polish: "odraczać" },
    { english: "delineate", polish: "wytyczać" },
    { english: "diligent", polish: "pilny" },
    { english: "diminish", polish: "zmniejszać" },
    { english: "disseminate", polish: "rozpowszechniać" },
    { english: "divulge", polish: "ujawniać" },
    { english: "embellish", polish: "upiększać" },
    { english: "empathy", polish: "empatia" },
    { english: "emulate", polish: "naśladować" },
    { english: "encompass", polish: "obejmować" },
    { english: "engender", polish: "wywoływać" },
    { english: "enthrall", polish: "zniewalać" },
    { english: "exemplify", polish: "ilustrować" },
    { english: "facilitate", polish: "ułatwiać" },
    { english: "feasible", polish: "wykonalny" },
    { english: "flourish", polish: "kwitnąć" },
    { english: "fortuitous", polish: "przypadkowy" },
    { english: "foster", polish: "wspierać" },
    { english: "frivolous", polish: "błahy" },
    { english: "galvanize", polish: "mobilizować" },
    { english: "genuine", polish: "autentyczny" },
    { english: "holistic", polish: "holistyczny" },
    { english: "imminent", polish: "nieuchronny" },
    { english: "impartial", polish: "bezstronny" },
    { english: "incessant", polish: "nieustanny" },
    { english: "indispensable", polish: "niezbędny" },
    { english: "inquisitive", polish: "ciekawski" },
    { english: "insightful", polish: "wnikliwy" },
    { english: "intrepid", polish: "dzielny" },
    { english: "juxtapose", polish: "zestawiać" },
    { english: "keen", polish: "ostry" },
    { english: "meticulous", polish: "dokładny" },
    { english: "nebulous", polish: "niejasny" },
    { english: "obsolete", polish: "przestarzały" },
    { english: "omnipotent", polish: "wszechmogący" },
    { english: "paradoxical", polish: "paradoksalny" },
    { english: "pertinent", polish: "istotny" },
    { english: "precarious", polish: "niepewny" },
    { english: "proactive", polish: "proaktywny" },
    { english: "proficient", polish: "biegły" },
    { english: "quaint", polish: "dziwaczny" },
    { english: "quintessential", polish: "przykładowy" },
    { english: "reiterate", polish: "powtarzać" },
    { english: "rejuvenate", polish: "odmłodzić" },
    { english: "resilient", polish: "odporny" },
    { english: "scrutinize", polish: "badać" },
    { english: "tangible", polish: "namacalny" },
    { english: "tenacious", polish: "wytrwały" },
    { english: "transcend", polish: "przekraczać" },
    { english: "unprecedented", polish: "bezprecedensowy" },
    { english: "ubiquitous", polish: "wszechobecny" },
    { english: "vindicate", polish: "uzasadniać" },
    { english: "wary", polish: "ostrożny" },
    { english: "zealous", polish: "gorliwy" },
];

let selectedWords = words.slice(); // Start with all words
let currentIndex = 0;
let currentWord;
let isEnglishToPolish = true;
let score = 0;
let translationVisible = false;
let answerGiven = false; // Nowa zmienna do śledzenia, czy odpowiedź została podana

const wordDisplay = document.getElementById('wordDisplay');
const userInput = document.getElementById('userInput');
const submitBtn = document.getElementById('submitBtn');
const result = document.getElementById('result');
const nextBtn = document.getElementById('nextBtn');
const optionsContainer = document.getElementById('optionsContainer');
const scoreDisplay = document.getElementById('score');
const translationDisplay = document.getElementById('translationDisplay');
const toggleTranslationBtn = document.getElementById('toggleTranslationBtn');
const switchLanguageBtn = document.getElementById('switchLanguageBtn');

document.querySelectorAll('.word-select-btn').forEach(button => {
    button.addEventListener('click', () => {
        const count = button.getAttribute('data-count');
        if (count === 'all') {
            selectedWords = words.slice();
            selectedCount = words.length; // Zaktualizuj wybraną ilość
        } else {
            const num = Math.min(parseInt(count), words.length);
            selectedWords = words.slice(0, num);
            selectedCount = num; // Zaktualizuj wybraną ilość
        }
        shuffle(selectedWords);
        currentIndex = 0;
        result.textContent = `Wybrano ${selectedCount} słówek do nauki.`; // Wyświetl informację
        setTimeout(displayWord, 2000);
    });
});

function displayWord() {
    if (currentIndex < selectedWords.length) {
        if (isEnglishToPolish) {
            currentWord = selectedWords[currentIndex].english;
            wordDisplay.textContent = currentWord;
            generateOptions(selectedWords[currentIndex].polish);
        } else {
            currentWord = selectedWords[currentIndex].polish;
            wordDisplay.textContent = currentWord;
            generateOptions(selectedWords[currentIndex].english);
        }
        userInput.value = '';
        result.textContent = '';
        updateTranslationDisplay();
    } else {
        // Loop back to the start of the selected words
        currentIndex = 0;
        displayWord();
    }
}

function generateOptions(correctAnswer) {
    optionsContainer.innerHTML = ''; // Clear previous options

    const options = [correctAnswer];
    while (options.length < 4) {
        const randomWord = selectedWords[Math.floor(Math.random() * selectedWords.length)];
        if (!options.includes(randomWord.polish) && isEnglishToPolish) {
            options.push(randomWord.polish);
        }
        if (!options.includes(randomWord.english) && !isEnglishToPolish) {
            options.push(randomWord.english);
        }
    }

    shuffle(options); // Shuffle options

    options.forEach(option => {
        const btn = document.createElement('button');
        btn.textContent = option;
        btn.className = 'option-btn';
        btn.addEventListener('click', () => checkAnswer(option, correctAnswer));
        optionsContainer.appendChild(btn);
    });
}

function checkAnswer(selected, correct) {
    if (answerGiven) return; // Jeśli odpowiedź została już podana, nie rób nic

    const userTranslation = userInput.value.trim().toLowerCase();
    const isCorrect = selected === correct || userTranslation === correct.toLowerCase();

    if (isCorrect) {
        result.textContent = "Dobrze!";
    } else {
        result.textContent = `Źle! Poprawne tłumaczenie to: ${correct}`;
    }

    answerGiven = true; // Oznacz, że odpowiedź została podana
}

submitBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    checkAnswer(null, correctTranslation);
});

nextBtn.addEventListener('click', () => {
    if (!answerGiven) return; // Jeśli odpowiedź nie została podana, nie rób nic

    currentIndex++;
    answerGiven = false; // Zresetuj stan
    displayWord();
});

toggleTranslationBtn.addEventListener('click', () => {
    translationVisible = !translationVisible;
    updateTranslationDisplay();
});

function updateTranslationDisplay() {
    if (translationVisible) {
        const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
        translationDisplay.textContent = correctTranslation;
    } else {
        translationDisplay.textContent = '';
    }
}

switchLanguageBtn.addEventListener('click', () => {
    isEnglishToPolish = !isEnglishToPolish; // Toggle the language direction
    displayWord(); // Refresh the displayed word
});

displayWord(); // Initial word display

function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

const toggleButton = document.getElementById('hideButton');
const myDiv = document.getElementById('wordSelectContainer');

toggleButton.addEventListener('click', () => {
    if (myDiv.style.display === 'none') {
        myDiv.style.display = 'block'; // Pokaż div
    } else {
        myDiv.style.display = 'none'; // Ukryj div
    }
});