const words = [
        { english: "I", polish: "ja" },
        { english: "you", polish: "ty" },
        { english: "he", polish: "on" },
        { english: "she", polish: "ona" },
        { english: "it", polish: "to" },
        { english: "we", polish: "my" },
        { english: "they", polish: "oni" },
        { english: "this", polish: "to" },
        { english: "that", polish: "tamto" },
        { english: "here", polish: "tutaj" },
        { english: "there", polish: "tam" },
        { english: "who", polish: "kto" },
        { english: "what", polish: "co" },
        { english: "where", polish: "gdzie" },
        { english: "when", polish: "kiedy" },
        { english: "why", polish: "dlaczego" },
        { english: "yes", polish: "tak" },
        { english: "no", polish: "nie" },
        { english: "not", polish: "nie" },
        { english: "and", polish: "i" },
        { english: "but", polish: "ale" },
        { english: "or", polish: "lub" },
        { english: "so", polish: "więc" },
        { english: "because", polish: "ponieważ" },
        { english: "very", polish: "bardzo" },
        { english: "much", polish: "dużo" },
        { english: "many", polish: "wiele" },
        { english: "little", polish: "mało" },
        { english: "some", polish: "niektóre" },
        { english: "any", polish: "jakikolwiek" },
        { english: "all", polish: "wszystko" },
        { english: "one", polish: "jeden" },
        { english: "two", polish: "dwa" },
        { english: "three", polish: "trzy" },
        { english: "four", polish: "cztery" },
        { english: "five", polish: "pięć" },
        { english: "big", polish: "duży" },
        { english: "small", polish: "mały" },
        { english: "good", polish: "dobry" },
        { english: "bad", polish: "zły" },
        { english: "happy", polish: "szczęśliwy" },
        { english: "sad", polish: "smutny" },
        { english: "hot", polish: "gorący" },
        { english: "cold", polish: "zimny" },
        { english: "new", polish: "nowy" },
        { english: "old", polish: "stary" },
        { english: "long", polish: "długi" },
        { english: "short", polish: "krótki" },
        { english: "right", polish: "prawy" },
        { english: "left", polish: "lewy" },
        { english: "day", polish: "dzień" },
        { english: "night", polish: "noc" },
        { english: "morning", polish: "ranek" },
        { english: "evening", polish: "wieczór" },
        { english: "time", polish: "czas" },
        { english: "year", polish: "rok" },
        { english: "week", polish: "tydzień" },
        { english: "month", polish: "miesiąc" },
        { english: "house", polish: "dom" },
        { english: "home", polish: "dom" },
        { english: "room", polish: "pokój" },
        { english: "kitchen", polish: "kuchnia" },
        { english: "bathroom", polish: "łazienka" },
        { english: "door", polish: "drzwi" },
        { english: "window", polish: "okno" },
        { english: "street", polish: "ulica" },
        { english: "school", polish: "szkoła" },
        { english: "teacher", polish: "nauczyciel" },
        { english: "student", polish: "uczeń" },
        { english: "book", polish: "książka" },
        { english: "pen", polish: "długopis" },
        { english: "pencil", polish: "ołówek" },
        { english: "paper", polish: "papier" },
        { english: "table", polish: "stół" },
        { english: "chair", polish: "krzesło" },
        { english: "food", polish: "jedzenie" },
        { english: "drink", polish: "napój" },
        { english: "water", polish: "woda" },
        { english: "coffee", polish: "kawa" },
        { english: "tea", polish: "herbata" },
        { english: "milk", polish: "mleko" },
        { english: "fruit", polish: "owoc" },
        { english: "vegetable", polish: "warzywo" },
        { english: "bread", polish: "chleb" },
        { english: "meat", polish: "mięso" },
        { english: "fish", polish: "ryba" },
        { english: "egg", polish: "jajko" },
        { english: "family", polish: "rodzina" },
        { english: "mother", polish: "matka" },
        { english: "father", polish: "ojciec" },
        { english: "sister", polish: "siostra" },
        { english: "brother", polish: "brat" },
        { english: "friend", polish: "przyjaciel" },
        { english: "boy", polish: "chłopiec" },
        { english: "girl", polish: "dziewczynka" },
        { english: "baby", polish: "niemowlę" },
        { english: "man", polish: "mężczyzna" },
        { english: "woman", polish: "kobieta" },
        { english: "people", polish: "ludzie" },
        { english: "child", polish: "dziecko" },
        { english: "love", polish: "miłość" },
        { english: "like", polish: "lubić" },
        { english: "want", polish: "chcieć" },
        { english: "need", polish: "potrzebować" },
        { english: "see", polish: "widzieć" },
        { english: "hear", polish: "słyszeć" },
        { english: "speak", polish: "mówić" },
        { english: "say", polish: "powiedzieć" },
        { english: "make", polish: "robić" },
        { english: "do", polish: "robić" },
        { english: "go", polish: "iść" },
        { english: "come", polish: "przyjść" },
        { english: "give", polish: "dać" },
        { english: "take", polish: "brać" },
        { english: "know", polish: "wiedzieć" },
        { english: "think", polish: "myśleć" },
        { english: "feel", polish: "czuć" },
        { english: "find", polish: "znaleźć" },
        { english: "look", polish: "patrzeć" },
        { english: "want", polish: "chcieć" },
        { english: "show", polish: "pokazać" },
        { english: "play", polish: "grać" },
        { english: "work", polish: "pracować" },
        { english: "call", polish: "dzwonić" },
        { english: "wait", polish: "czekać" },
        { english: "try", polish: "próbować" },
        { english: "ask", polish: "pytać" },
        { english: "answer", polish: "odpowiadać" },
        { english: "help", polish: "pomagać" },
        { english: "need", polish: "potrzebować" },
        { english: "understand", polish: "rozumieć" },
        { english: "believe", polish: "wierzyć" },
        { english: "remember", polish: "pamiętać" },
        { english: "forget", polish: "zapomnieć" },
        { english: "try", polish: "próbować" },
        { english: "work", polish: "pracować" },
        { english: "begin", polish: "zaczynać" },
        { english: "end", polish: "kończyć" },
        { english: "change", polish: "zmieniać" },
        { english: "move", polish: "ruszać" },
        { english: "play", polish: "grać" },
        { english: "dance", polish: "tańczyć" },
        { english: "laugh", polish: "śmiać się" },
        { english: "cry", polish: "płakać" },
        { english: "smile", polish: "uśmiechać się" },
        { english: "watch", polish: "oglądać" },
        { english: "listen", polish: "słuchać" },
        { english: "read", polish: "czytać" },
        { english: "write", polish: "pisać" },
        { english: "draw", polish: "rysować" },
        { english: "paint", polish: "malować" },
        { english: "clean", polish: "czyścić" },
        { english: "wash", polish: "myć" },
        { english: "cook", polish: "gotować" },
        { english: "eat", polish: "jeść" },
        { english: "drink", polish: "pić" },
        { english: "sleep", polish: "spać" },
        { english: "wake", polish: "budzić się" },
        { english: "rest", polish: "odpoczywać" },
        { english: "work", polish: "pracować" },
        { english: "study", polish: "uczyć się" },
        { english: "travel", polish: "podróżować" },
        { english: "visit", polish: "odwiedzać" },
        { english: "buy", polish: "kupować" },
        { english: "sell", polish: "sprzedawać" },
        { english: "spend", polish: "wydawać" },
        { english: "pay", polish: "płacić" },
        { english: "save", polish: "oszczędzać" },
        { english: "find", polish: "znaleźć" },
        { english: "lose", polish: "zgubić" },
        { english: "meet", polish: "spotykać" },
        { english: "bring", polish: "przynosić" },
        { english: "carry", polish: "nieść" },
        { english: "send", polish: "wysyłać" },
        { english: "ask", polish: "pytać" },
        { english: "answer", polish: "odpowiadać" },
        { english: "tell", polish: "powiedzieć" },
        { english: "say", polish: "mówić" },
        { english: "speak", polish: "mówić" },
        { english: "talk", polish: "rozmawiać" },
        { english: "discuss", polish: "dyskutować" },
        { english: "explain", polish: "wyjaśniać" },
        { english: "describe", polish: "opisywać" },
        { english: "suggest", polish: "sugerować" },
        { english: "advise", polish: "doradzać" },
        { english: "recommend", polish: "polecać" },
        { english: "inform", polish: "informować" },
        { english: "warn", polish: "ostrzegać" },
        { english: "invite", polish: "zapraszać" },
        { english: "thank", polish: "dziękować" },
        { english: "apologize", polish: "przepraszać" },
        { english: "promise", polish: "obiecać" },
        { english: "wish", polish: "życzyć" },
        { english: "hope", polish: "mieć nadzieję" },
        { english: "dream", polish: "marzyć" },
        { english: "believe", polish: "wierzyć" },
        { english: "think", polish: "myśleć" },
        { english: "know", polish: "wiedzieć" },
        { english: "understand", polish: "rozumieć" },
        { english: "learn", polish: "uczyć się" },
        { english: "forget", polish: "zapomnieć" },
        { english: "remember", polish: "pamiętać" },
        { english: "realize", polish: "zdawać sobie sprawę" },
        { english: "belong", polish: "należeć" },
        { english: "exist", polish: "istnieć" },
        { english: "believe", polish: "wierzyć" },
        { english: "trust", polish: "ufać" },
        { english: "hope", polish: "mieć nadzieję" },
        { english: "wish", polish: "życzyć" },
        { english: "learn", polish: "uczyć się" },
        { english: "teach", polish: "uczyć" },
        { english: "help", polish: "pomagać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "encourage", polish: "zachęcać" },
        { english: "advise", polish: "doradzać" },
        { english: "recommend", polish: "polecać" },
        { english: "suggest", polish: "sugerować" },
        { english: "share", polish: "dzielić się" },
        { english: "care", polish: "troszczyć się" },
        { english: "love", polish: "kochać" },
        { english: "hate", polish: "nienawidzić" },
        { english: "enjoy", polish: "cieszyć się" },
        { english: "prefer", polish: "preferować" },
        { english: "dislike", polish: "nie lubić" },
        { english: "like", polish: "lubić" },
        { english: "want", polish: "chcieć" },
        { english: "need", polish: "potrzebować" },
        { english: "wish", polish: "życzyć" },
        { english: "hope", polish: "mieć nadzieję" },
        { english: "dream", polish: "marzyć" },
        { english: "believe", polish: "wierzyć" },
        { english: "trust", polish: "ufać" },
        { english: "respect", polish: "szanować" },
        { english: "value", polish: "cenić" },
        { english: "appreciate", polish: "doceniać" },
        { english: "celebrate", polish: "świętować" },
        { english: "enjoy", polish: "cieszyć się" },
        { english: "appreciate", polish: "doceniać" },
        { english: "thank", polish: "dziękować" },
        { english: "apologize", polish: "przepraszać" },
        { english: "promise", polish: "obiecać" },
        { english: "hope", polish: "mieć nadzieję" },
        { english: "wish", polish: "życzyć" },
        { english: "believe", polish: "wierzyć" },
        { english: "think", polish: "myśleć" },
        { english: "know", polish: "wiedzieć" },
        { english: "understand", polish: "rozumieć" },
        { english: "learn", polish: "uczyć się" },
        { english: "forget", polish: "zapomnieć" },
        { english: "remember", polish: "pamiętać" },
        { english: "realize", polish: "zdawać sobie sprawę" },
        { english: "exist", polish: "istnieć" },
        { english: "become", polish: "stać się" },
        { english: "remain", polish: "pozostać" },
        { english: "belong", polish: "należeć" },
        { english: "achieve", polish: "osiągnąć" },
        { english: "succeed", polish: "odnosić sukces" },
        { english: "fail", polish: "nie udać się" },
        { english: "improve", polish: "poprawić" },
        { english: "develop", polish: "rozwijać" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "build", polish: "budować" },
        { english: "construct", polish: "konstruować" },
        { english: "produce", polish: "produkować" },
        { english: "make", polish: "robić" },
        { english: "do", polish: "robić" },
        { english: "perform", polish: "wykonywać" },
        { english: "act", polish: "działać" },
        { english: "react", polish: "reagować" },
        { english: "respond", polish: "reagować" },
        { english: "respond", polish: "odpowiadać" },
        { english: "influence", polish: "wpływać" },
        { english: "persuade", polish: "przekonywać" },
        { english: "encourage", polish: "zachęcać" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "lead", polish: "prowadzić" },
        { english: "guide", polish: "prowadzić" },
        { english: "follow", polish: "podążać" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "decide", polish: "decydować" },
        { english: "make", polish: "robić" },
        { english: "take", polish: "brać" },
        { english: "give", polish: "dać" },
        { english: "send", polish: "wysyłać" },
        { english: "receive", polish: "otrzymać" },
        { english: "buy", polish: "kupować" },
        { english: "sell", polish: "sprzedawać" },
        { english: "trade", polish: "handlować" },
        { english: "exchange", polish: "wymieniać" },
        { english: "spend", polish: "wydawać" },
        { english: "waste", polish: "marnować" },
        { english: "save", polish: "oszczędzać" },
        { english: "invest", polish: "inwestować" },
        { english: "borrow", polish: "pożyczyć" },
        { english: "lend", polish: "pożyczyć" },
        { english: "earn", polish: "zarabiać" },
        { english: "pay", polish: "płacić" },
        { english: "owe", polish: "być winnym" },
        { english: "cost", polish: "kosztować" },
        { english: "value", polish: "cenić" },
        { english: "price", polish: "cena" },
        { english: "worth", polish: "wartość" },
        { english: "afford", polish: "stać na" },
        { english: "afford", polish: "można sobie pozwolić" },
        { english: "purchase", polish: "zakup" },
        { english: "transaction", polish: "transakcja" },
        { english: "business", polish: "biznes" },
        { english: "company", polish: "firma" },
        { english: "market", polish: "rynek" },
        { english: "consumer", polish: "konsument" },
        { english: "supplier", polish: "dostawca" },
        { english: "customer", polish: "klient" },
        { english: "client", polish: "klient" },
        { english: "employee", polish: "pracownik" },
        { english: "employer", polish: "pracodawca" },
        { english: "manager", polish: "menedżer" },
        { english: "director", polish: "dyrektor" },
        { english: "leader", polish: "lider" },
        { english: "team", polish: "zespół" },
        { english: "department", polish: "dział" },
        { english: "organization", polish: "organizacja" },
        { english: "institution", polish: "instytucja" },
        { english: "association", polish: "stowarzyszenie" },
        { english: "society", polish: "społeczeństwo" },
        { english: "community", polish: "społeczność" },
        { english: "government", polish: "rząd" },
        { english: "policy", polish: "polityka" },
        { english: "law", polish: "prawo" },
        { english: "regulation", polish: "regulacja" },
        { english: "rule", polish: "zasada" },
        { english: "system", polish: "system" },
        { english: "process", polish: "proces" },
        { english: "procedure", polish: "procedura" },
        { english: "method", polish: "metoda" },
        { english: "approach", polish: "podejście" },
        { english: "strategy", polish: "strategia" },
        { english: "goal", polish: "cel" },
        { english: "objective", polish: "obiekt" },
        { english: "target", polish: "cel" },
        { english: "aim", polish: "cel" },
        { english: "result", polish: "rezultat" },
        { english: "outcome", polish: "wynik" },
        { english: "impact", polish: "wpływ" },
        { english: "effect", polish: "efekt" },
        { english: "consequence", polish: "konsekwencja" },
        { english: "change", polish: "zmiana" },
        { english: "improvement", polish: "ulepszenie" },
        { english: "progress", polish: "postęp" },
        { english: "development", polish: "rozwój" },
        { english: "advancement", polish: "awans" },
        { english: "growth", polish: "wzrost" },
        { english: "decline", polish: "spadek" },
        { english: "reduction", polish: "redukcja" },
        { english: "increase", polish: "wzrost" },
        { english: "expansion", polish: "rozszerzenie" },
        { english: "enlargement", polish: "powiększenie" },
        { english: "enhancement", polish: "wzbogacenie" },
        { english: "improvement", polish: "poprawa" },
        { english: "evaluation", polish: "ewaluacja" },
        { english: "assessment", polish: "ocena" },
        { english: "analysis", polish: "analiza" },
        { english: "research", polish: "badanie" },
        { english: "study", polish: "badanie" },
        { english: "investigation", polish: "śledztwo" },
        { english: "experiment", polish: "eksperyment" },
        { english: "exploration", polish: "eksploracja" },
        { english: "discovery", polish: "odkrycie" },
        { english: "invention", polish: "wynalazek" },
        { english: "innovation", polish: "innowacja" },
        { english: "creation", polish: "tworzenie" },
        { english: "development", polish: "rozwój" },
        { english: "design", polish: "projektowanie" },
        { english: "production", polish: "produkcja" },
        { english: "manufacturing", polish: "produkcja" },
        { english: "construction", polish: "budowa" },
        { english: "installation", polish: "instalacja" },
        { english: "maintenance", polish: "utrzymanie" },
        { english: "repair", polish: "naprawa" },
        { english: "service", polish: "serwis" },
        { english: "operation", polish: "operacja" },
        { english: "function", polish: "funkcja" },
        { english: "task", polish: "zadanie" },
        { english: "assignment", polish: "zadanie" },
        { english: "duty", polish: "obowiązek" },
        { english: "responsibility", polish: "odpowiedzialność" },
        { english: "accountability", polish: "odpowiedzialność" },
        { english: "authority", polish: "władza" },
        { english: "leadership", polish: "przywództwo" },
        { english: "management", polish: "zarządzanie" },
        { english: "administration", polish: "administracja" },
        { english: "organization", polish: "organizacja" },
        { english: "operation", polish: "operacja" },
        { english: "methodology", polish: "metodologia" },
        { english: "framework", polish: "ramy" },
        { english: "structure", polish: "struktura" },
        { english: "system", polish: "system" },
        { english: "network", polish: "sieć" },
        { english: "platform", polish: "platforma" },
        { english: "software", polish: "oprogramowanie" },
        { english: "hardware", polish: "sprzęt" },
        { english: "technology", polish: "technologia" },
        { english: "innovation", polish: "innowacja" },
        { english: "science", polish: "nauka" },
        { english: "research", polish: "badania" },
        { english: "development", polish: "rozwój" },
        { english: "education", polish: "edukacja" },
        { english: "training", polish: "szkolenie" },
        { english: "learning", polish: "nauka" },
        { english: "knowledge", polish: "wiedza" },
        { english: "skill", polish: "umiejętność" },
        { english: "competence", polish: "kompetencja" },
        { english: "experience", polish: "doświadczenie" },
        { english: "expertise", polish: "ekspertyza" },
        { english: "ability", polish: "zdolność" },
        { english: "talent", polish: "talent" },
        { english: "capacity", polish: "zdolność" },
        { english: "potential", polish: "potencjał" },
        { english: "development", polish: "rozwój" },
        { english: "growth", polish: "wzrost" },
        { english: "progress", polish: "postęp" },
        { english: "improvement", polish: "ulepszenie" },
        { english: "success", polish: "sukces" },
        { english: "achievement", polish: "osiągnięcie" },
        { english: "goal", polish: "cel" },
        { english: "objective", polish: "obiekt" },
        { english: "target", polish: "cel" },
        { english: "plan", polish: "plan" },
        { english: "strategy", polish: "strategia" },
        { english: "tactic", polish: "taktyka" },
        { english: "approach", polish: "podejście" },
        { english: "method", polish: "metoda" },
        { english: "process", polish: "proces" },
        { english: "system", polish: "system" },
        { english: "procedure", polish: "procedura" },
        { english: "policy", polish: "polityka" },
        { english: "rule", polish: "zasada" },
        { english: "regulation", polish: "regulacja" },
        { english: "standard", polish: "standard" },
        { english: "criteria", polish: "kryteria" },
        { english: "measure", polish: "mierzyć" },
        { english: "evaluate", polish: "oceniać" },
        { english: "assess", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" },
        { english: "design", polish: "projektować" },
        { english: "develop", polish: "rozwijać" },
        { english: "produce", polish: "produkować" },
        { english: "manufacture", polish: "produkować" },
        { english: "construct", polish: "budować" },
        { english: "assemble", polish: "montować" },
        { english: "install", polish: "instalować" },
        { english: "maintain", polish: "utrzymywać" },
        { english: "repair", polish: "naprawiać" },
        { english: "service", polish: "serwisować" },
        { english: "operate", polish: "operować" },
        { english: "manage", polish: "zarządzać" },
        { english: "administer", polish: "administrować" },
        { english: "supervise", polish: "nadzorować" },
        { english: "coordinate", polish: "koordynować" },
        { english: "lead", polish: "prowadzić" },
        { english: "motivate", polish: "motywować" },
        { english: "inspire", polish: "inspirować" },
        { english: "encourage", polish: "zachęcać" },
        { english: "support", polish: "wspierać" },
        { english: "assist", polish: "pomagać" },
        { english: "help", polish: "pomagać" },
        { english: "advise", polish: "doradzać" },
        { english: "counsel", polish: "doradzać" },
        { english: "guide", polish: "prowadzić" },
        { english: "direct", polish: "kierować" },
        { english: "plan", polish: "planować" },
        { english: "strategize", polish: "opracować strategię" },
        { english: "decide", polish: "decydować" },
        { english: "choose", polish: "wybierać" },
        { english: "select", polish: "wybierać" },
        { english: "execute", polish: "wykonać" },
        { english: "implement", polish: "wdrażać" },
        { english: "perform", polish: "wykonywać" },
        { english: "monitor", polish: "monitorować" },
        { english: "evaluate", polish: "oceniać" },
        { english: "review", polish: "recenzować" },
        { english: "assess", polish: "oceniać" },
        { english: "measure", polish: "mierzyć" },
        { english: "analyze", polish: "analizować" },
        { english: "research", polish: "prowadzić badania" },
        { english: "study", polish: "uczyć się" },
        { english: "learn", polish: "uczyć się" },
        { english: "discover", polish: "odkryć" },
        { english: "explore", polish: "badać" },
        { english: "investigate", polish: "prowadzić śledztwo" },
        { english: "experiment", polish: "przeprowadzać eksperyment" },
        { english: "innovate", polish: "wprowadzać innowacje" },
        { english: "create", polish: "tworzyć" }
];

let selectedWords = [];
let currentIndex = 0;
let isEnglishToPolish = true;
let score = 0;
let answerGiven = false; // Śledzenie, czy odpowiedź została podana

// Elementy DOM
const container = document.getElementById("containerAnswer");
const wordDisplay = document.getElementById('wordDisplay');
const userInput = document.getElementById('userInput');
const submitBtn = document.getElementById('submitBtn');
const result = document.getElementById('result');
const nextBtn = document.getElementById('nextBtn');
const optionsContainer = document.getElementById('optionsContainer');
const translationDisplay = document.getElementById('translationDisplay');
const toggleTranslationBtn = document.getElementById('toggleTranslationBtn');
const switchLanguageBtn = document.getElementById('switchLanguageBtn');

// Inicjalizacja
function init() {
    selectedWords = words.slice(); // Wybierz wszystkie słowa
    currentIndex = 0;
    displayWord(); // Wyświetl pierwsze słowo
}

// Wybór słów
document.querySelectorAll('.word-select-btn').forEach(button => {
    button.addEventListener('click', () => {
        const count = button.getAttribute('data-count');
        if (count === 'all') {
            selectedWords = words.slice(); // Wybierz wszystkie słowa
        } else {
            const num = Math.min(parseInt(count), words.length);
            selectedWords = getRandomWords(words, num); // Wybierz losowe słowa
        }
        currentIndex = 0;
        result.textContent = `Wybrano ${selectedWords.length} słówek do nauki.`; // Wyświetl informację
        setTimeout(displayWord, 2000); // Wyświetl pierwsze słowo
    });
});

// Funkcja losująca słowa
function getRandomWords(sourceArray, count) {
    const shuffled = sourceArray.slice().sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
}

// Wyświetlanie słowa
function displayWord() {
    if (selectedWords.length === 0) {
        result.textContent = "Nie wybrano słówek do nauki!";
        return;
    }

    const currentWord = isEnglishToPolish ? selectedWords[currentIndex].english : selectedWords[currentIndex].polish;
    wordDisplay.textContent = currentWord;
    generateOptions(isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english);
    userInput.value = '';
    result.textContent = '';
}

// Generowanie opcji do wyboru
function generateOptions(correctAnswer) {
    optionsContainer.innerHTML = ''; // Wyczyść poprzednie opcje

    const options = [correctAnswer];
    while (options.length < 4) {
        const randomWord = selectedWords[Math.floor(Math.random() * selectedWords.length)];
        if (isEnglishToPolish) {
            if (!options.includes(randomWord.polish)) options.push(randomWord.polish);
        } else {
            if (!options.includes(randomWord.english)) options.push(randomWord.english);
        }
    }

    shuffle(options); // Tasowanie opcji

    options.forEach(option => {
        const btn = document.createElement('button');
        btn.textContent = option;
        btn.className = 'option-btn';
        btn.addEventListener('click', () => checkAnswer(option, correctAnswer));
        optionsContainer.appendChild(btn);
    });
}

// Sprawdzanie odpowiedzi
function checkAnswer(selected, correct) {
    if (answerGiven) return; // Jeśli odpowiedź została już podana, nie rób nic

    const isCorrect = selected === correct || userInput.value.trim().toLowerCase() === correct.toLowerCase();
    
    if (isCorrect) {
        result.textContent = "Dobrze!";
        score++; // Zwiększ wynik
        container.classList.add('bounce'); // Animacja bounce

        // Dodaj klasę .btn-yellow do wszystkich przycisków
        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-yellow'));

        // Usuń klasy po pewnym czasie
        setTimeout(() => {
            container.classList.remove('bounce');
            buttons.forEach(button => button.classList.remove('btn-yellow'));
        }, 600);
    } else {
        result.textContent = `Źle! Poprawne tłumaczenie to: ${correct}`;
        container.classList.add('shake'); // Animacja shake

        // Dodaj klasę .btn-red do wszystkich przycisków
        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-red'));

        // Usuń klasy po pewnym czasie
        setTimeout(() => {
            container.classList.remove('shake');
            buttons.forEach(button => button.classList.remove('btn-red'));
        }, 600);
    }

    answerGiven = true; // Oznacz, że odpowiedź została podana
}

// Obsługa przycisku "Submit"
submitBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    checkAnswer(null, correctTranslation);
});

// Obsługa przycisku "Next"
nextBtn.addEventListener('click', () => {
    if (!answerGiven) return; // Jeśli odpowiedź nie została podana, nie rób nic
    currentIndex = (currentIndex + 1) % selectedWords.length; // Przechodź do następnego słowa (cyklicznie)
    answerGiven = false; // Zresetuj stan
    displayWord();
});

// Toggle tłumaczenia
toggleTranslationBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    translationDisplay.textContent = translationDisplay.textContent ? '' : correctTranslation;
});

// Zmiana języka
switchLanguageBtn.addEventListener('click', () => {
    isEnglishToPolish = !isEnglishToPolish; // Zmień kierunek języka
    displayWord(); // Odśwież wyświetlane słowo
});

// Inicjalizacja
init();

// Funkcja tasująca
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

// Przycisk do ukrywania/pokazywania kontenera wyboru słów
const toggleButton = document.getElementById('hideButton');
const myDiv = document.getElementById('wordSelectContainer');

toggleButton.addEventListener('click', () => {
    myDiv.style.display = myDiv.style.display === 'none' ? 'block' : 'none'; // Przełącz widoczność
});