const words = [
    {english: "asset allocation - Asset allocation is the strategy of dividing investments among different asset classes, such as stocks, bonds, and cash, to optimize the risk-reward profile", polish: "alokacja aktywów - Alokacja aktywów to strategia dzielenia inwestycji między różne klasy aktywów, takie jak akcje, obligacje i gotówka, w celu optymalizacji stosunku ryzyka do zysku."},
    {english: "diversification - Diversification is the practice of spreading investments across various assets to reduce the risk of loss", polish: "dywersyfikacja - Dywersyfikacja to praktyka rozpraszania inwestycji w różnych aktywach w celu zmniejszenia ryzyka straty."},
    {english: "capital gains - Capital gains are the profits made from the sale of an asset such as stocks or real estate", polish: "zyski kapitałowe - Zyski kapitałowe to zyski uzyskane ze sprzedaży aktywów, takich jak akcje czy nieruchomości."},
    {english: "risk tolerance - Risk tolerance is the degree of risk an investor is willing to take in pursuit of higher returns", polish: "tolerancja ryzyka - Tolerancja ryzyka to stopień ryzyka, które inwestor jest gotów podjąć w dążeniu do wyższych zwrotów."},
    {english: "bull market - A bull market is a financial market in which prices are rising or are expected to rise", polish: "rynek byka - Rynek byka to rynek finansowy, na którym ceny rosną lub przewiduje się ich wzrost."},
    {english: "bear market - A bear market is a financial market in which prices are falling or are expected to fall", polish: "rynek niedźwiedzia - Rynek niedźwiedzia to rynek finansowy, na którym ceny spadają lub przewiduje się ich spadek."},
    {english: "liquidity - Liquidity refers to how quickly and easily an asset can be converted into cash without affecting its price", polish: "płynność - Płynność odnosi się do tego, jak szybko i łatwo aktywa mogą zostać przekształcone w gotówkę, bez wpływu na ich cenę."},
    {english: "portfolio - A portfolio is a collection of investments held by an individual or an institution", polish: "portfel inwestycyjny - Portfel inwestycyjny to zbiór inwestycji posiadanych przez osobę lub instytucję."},
    {english: "mutual funds - Mutual funds are investment vehicles that pool funds from many investors to purchase securities like stocks, bonds, or other assets", polish: "fundusze inwestycyjne - Fundusze inwestycyjne to pojazdy inwestycyjne, które gromadzą fundusze od wielu inwestorów w celu zakupu papierów wartościowych, takich jak akcje, obligacje lub inne aktywa."},
    {english: "exchange-traded fund (ETF) - An ETF is a type of investment fund that is traded on a stock exchange, much like stocks", polish: "fundusz notowany na giełdzie (ETF) - ETF to rodzaj funduszu inwestycyjnego, który jest notowany na giełdzie, podobnie jak akcje."},
    {english: "dividend - A dividend is a payment made by a corporation to its shareholders, typically from profits", polish: "dywidenda - Dywidenda to płatność dokonywana przez korporację na rzecz swoich akcjonariuszy, zazwyczaj z zysków."},
    {english: "yield - Yield refers to the income generated by an investment, usually expressed as a percentage of the investment's cost", polish: "stopa zwrotu - Stopa zwrotu odnosi się do dochodu generowanego przez inwestycję, zwykle wyrażonego jako procent kosztu inwestycji."},
    {english: "compound interest - Compound interest is the interest on a loan or deposit that is calculated based on both the initial principal and the accumulated interest", polish: "odsetki składane - Odsetki składane to odsetki od pożyczki lub depozytu, które są obliczane na podstawie zarówno początkowego kapitału, jak i skumulowanych odsetek."},
    {english: "bonds - Bonds are debt securities issued by an entity such as a government or corporation, promising to pay interest and return the principal at maturity", polish: "obligacje - Obligacje to papiery dłużne emitowane przez podmiot, taki jak rząd lub korporacja, obiecujące wypłatę odsetek i zwrot kapitału początkowego po terminie wykupu."},
    {english: "stocks - Stocks represent ownership in a corporation and constitute a claim on part of the company’s assets and earnings", polish: "akcje - Akcje reprezentują własność w korporacji i stanowią roszczenie do części aktywów i zysków firmy."},
    {english: "market capitalization - Market capitalization refers to the total value of a company's outstanding shares, calculated by multiplying the stock price by the number of shares outstanding", polish: "kapitalizacja rynkowa - Kapitalizacja rynkowa odnosi się do całkowitej wartości wszystkich wyemitowanych akcji firmy, obliczanej przez pomnożenie ceny akcji przez liczbę akcji w obiegu."},
    {english: "initial public offering (IPO) - An IPO is the process through which a private company offers shares to the public for the first time", polish: "pierwsza oferta publiczna (IPO) - IPO to proces, w którym prywatna firma po raz pierwszy oferuje swoje akcje publiczności."},
    {english: "risk management - Risk management involves identifying, assessing, and prioritizing risks followed by coordinated efforts to minimize or control the likelihood of negative events", polish: "zarządzanie ryzykiem - Zarządzanie ryzykiem polega na identyfikowaniu, ocenianiu i priorytetyzowaniu ryzyk, a następnie podejmowaniu skoordynowanych działań w celu minimalizacji lub kontrolowania prawdopodobieństwa wystąpienia negatywnych zdarzeń."},
    {english: "valuation - Valuation is the process of determining the present value of an asset or company, often using financial metrics and analysis", polish: "wycena - Wycena to proces określania bieżącej wartości aktywów lub firmy, często z użyciem wskaźników finansowych i analizy."},
    {english: "real estate investment - Real estate investment involves purchasing property to generate income or capital gains", polish: "inwestycja w nieruchomości - Inwestycja w nieruchomości polega na zakupie nieruchomości w celu generowania dochodu lub zysków kapitałowych."},
    {english: "investor - An investor is an individual or entity that allocates capital to an asset or venture with the expectation of a return", polish: "inwestor - Inwestor to osoba lub podmiot, który alokuje kapitał w aktywa lub przedsięwzięcie, oczekując zwrotu."},
    {english: "private equity - Private equity refers to investments in companies that are not listed on a public exchange, typically through direct investment or buyouts", polish: "kapitał prywatny - Kapitał prywatny odnosi się do inwestycji w firmy, które nie są notowane na giełdzie publicznej, zazwyczaj poprzez inwestycje bezpośrednie lub przejęcia."},
    {english: "hedge fund - A hedge fund is an investment fund that uses advanced strategies such as short selling, leverage, and derivatives to generate high returns", polish: "fundusz hedgingowy - Fundusz hedgingowy to fundusz inwestycyjny, który stosuje zaawansowane strategie, takie jak sprzedaż krótka, dźwignia finansowa i instrumenty pochodne, aby uzyskać wysokie zwroty."},
    {english: "angel investor - An angel investor is a high-net-worth individual who provides financial backing to early-stage startups in exchange for ownership equity or debt", polish: "anioł biznesu - Anioł biznesu to osoba o wysokiej wartości netto, która udziela wsparcia finansowego startupom na wczesnym etapie w zamian za udziały własnościowe lub dług."},
    {english: "venture capital - Venture capital refers to funding provided to startups and small businesses with high growth potential, typically in exchange for equity ownership", polish: "kapitał podwyższonego ryzyka - Kapitał podwyższonego ryzyka odnosi się do finansowania udzielanego startupom i małym firmom o dużym potencjale wzrostu, zazwyczaj w zamian za udziały własnościowe."},
    {english: "real estate investment trust (REIT) - A REIT is a company that owns, operates, or finances income-producing real estate, offering investors a way to invest in real estate without having to own property", polish: "fundusz inwestycyjny w nieruchomości (REIT) - REIT to firma, która posiada, zarządza lub finansuje nieruchomości generujące dochód, oferując inwestorom sposób inwestowania w nieruchomości bez konieczności posiadania własności."},
    {english: "fixed income - Fixed income refers to investment securities that provide regular interest payments, such as bonds or certificates of deposit", polish: "dochód stały - Dochód stały odnosi się do papierów wartościowych inwestycyjnych, które zapewniają regularne płatności odsetek, takich jak obligacje czy certyfikaty depozytowe."},
    {english: "inflation risk - Inflation risk is the risk that the value of an investment's return will be eroded by rising inflation", polish: "ryzyko inflacyjne - Ryzyko inflacyjne to ryzyko, że wartość zwrotu z inwestycji zostanie zredukowana przez rosnącą inflację."},
    {english: "interest rate risk - Interest rate risk is the potential for investment losses due to changes in interest rates", polish: "ryzyko stopy procentowej - Ryzyko stopy procentowej to potencjalne straty z inwestycji spowodowane zmianami stóp procentowych."},
    {english: "market risk - Market risk is the risk of losses in an investment due to factors that affect the overall performance of the financial markets", polish: "ryzyko rynkowe - Ryzyko rynkowe to ryzyko strat z inwestycji spowodowane czynnikami wpływającymi na ogólną wydajność rynków finansowych."},
    {english: "credit risk - Credit risk is the risk of a borrower defaulting on a loan or bond, which could lead to financial losses for the lender or bondholder", polish: "ryzyko kredytowe - Ryzyko kredytowe to ryzyko, że pożyczkobiorca nie spłaci pożyczki lub obligacji, co może prowadzić do strat finansowych dla pożyczkodawcy lub posiadacza obligacji."},
    {english: "inflation-protected securities - Inflation-protected securities are investment instruments that are designed to protect investors from inflation by adjusting returns based on inflation rates", polish: "papiery wartościowe chronione przed inflacją - Papiery wartościowe chronione przed inflacją to instrumenty inwestycyjne zaprojektowane w celu ochrony inwestorów przed inflacją, poprzez dostosowywanie zwrotów w zależności od wskaźników inflacji."},
    {english: "capital preservation - Capital preservation is an investment strategy that aims to prevent the loss of the original investment, even in low-risk environments", polish: "ochrona kapitału - Ochrona kapitału to strategia inwestycyjna, której celem jest zapobieganie utracie początkowej inwestycji, nawet w środowiskach o niskim ryzyku."},
    {english: "asset-backed security (ABS) - An asset-backed security is a financial instrument backed by a pool of assets, such as loans or receivables, which are used to generate income for investors", polish: "papier wartościowy zabezpieczony aktywami (ABS) - Papier wartościowy zabezpieczony aktywami to instrument finansowy zabezpieczony pulą aktywów, takich jak pożyczki lub należności, które są wykorzystywane do generowania dochodów dla inwestorów."},
    {english: "emerging markets - Emerging markets refer to economies that are in the process of rapid growth and industrialization, offering investment opportunities but also higher risks", polish: "rynki wschodzące - Rynki wschodzące to gospodarki, które przechodzą proces szybkiego wzrostu i industrializacji, oferujące możliwości inwestycyjne, ale również wyższe ryzyko."},
    {english: "commodity - A commodity is a basic good used in commerce that is interchangeable with other goods of the same type, such as oil or gold", polish: "towar - Towar to podstawowy produkt wykorzystywany w handlu, który jest wymienny z innymi produktami tego samego typu, takimi jak ropa naftowa czy złoto."},
    {english: "forex - Forex, or foreign exchange, refers to the global market for buying and selling currencies", polish: "forex - Forex, czyli wymiana walut, odnosi się do globalnego rynku kupna i sprzedaży walut."},
    {english: "commodity futures - Commodity futures are contracts to buy or sell a commodity at a future date at an agreed-upon price", polish: "futures na towary - Futures na towary to kontrakty kupna lub sprzedaży towaru w przyszłości po uzgodnionej cenie."},
    {english: "asset class - An asset class is a group of investments with similar characteristics, such as stocks, bonds, real estate, or commodities", polish: "klasa aktywów - Klasa aktywów to grupa inwestycji o podobnych cechach, takich jak akcje, obligacje, nieruchomości lub towary."},
    {english: "bull market - A bull market refers to a period in which the prices of securities are rising or are expected to rise", polish: "rynek byka - Rynek byka odnosi się do okresu, w którym ceny papierów wartościowych rosną lub oczekuje się, że będą rosły."},
    {english: "bear market - A bear market refers to a period in which the prices of securities are falling or are expected to fall", polish: "rynek niedźwiedzia - Rynek niedźwiedzia odnosi się do okresu, w którym ceny papierów wartościowych spadają lub oczekuje się, że będą spadały."},
    {english: "real estate investment trust (REIT) - A real estate investment trust is a company that owns, operates, or finances real estate that produces income", polish: "fundusz inwestycyjny w nieruchomości (REIT) - Fundusz inwestycyjny w nieruchomości to firma, która posiada, zarządza lub finansuje nieruchomości, które generują dochód."},
    {english: "capital preservation - Capital preservation is an investment strategy that seeks to protect the value of an investment portfolio by minimizing the risk of loss", polish: "ochrona kapitału - Ochrona kapitału to strategia inwestycyjna, która ma na celu ochronę wartości portfela inwestycyjnego poprzez minimalizowanie ryzyka straty."},
    {english: "blue-chip stocks - Blue-chip stocks are shares of well-established, financially sound, and reputable companies with a history of reliable performance", polish: "akcje blue-chip - Akcje blue-chip to udziały w dobrze ustanowionych, stabilnych finansowo i renomowanych firmach z historią niezawodnych wyników."},
    {english: "value investing - Value investing is an investment strategy that involves picking stocks that appear to be undervalued based on fundamental analysis", polish: "inwestowanie w wartość - Inwestowanie w wartość to strategia inwestycyjna, która polega na wybieraniu akcji, które wydają się niedowartościowane na podstawie analizy fundamentalnej."},
    {english: "growth investing - Growth investing is an investment strategy focused on companies that exhibit signs of above-average growth, even if their stock prices are high", polish: "inwestowanie w wzrost - Inwestowanie w wzrost to strategia inwestycyjna, która koncentruje się na firmach wykazujących oznaki wzrostu powyżej średniej, nawet jeśli ich ceny akcji są wysokie."},
    {english: "exchange rate - The exchange rate is the value of one currency for the purpose of conversion to another", polish: "kurs wymiany - Kurs wymiany to wartość jednej waluty w celu jej konwersji na inną."},
    {english: "inflation - Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power", polish: "inflacja - Inflacja to stopa, w jakiej ogólny poziom cen towarów i usług rośnie, co prowadzi do utraty siły nabywczej."},
    {english: "yield - Yield refers to the income return on an investment, typically expressed as a percentage of the investment's cost or market value", polish: "stopa zwrotu - Stopa zwrotu odnosi się do dochodowego zwrotu z inwestycji, zazwyczaj wyrażanego jako procent kosztu inwestycji lub jej wartości rynkowej."},
    {english: "margin trading - Margin trading involves borrowing money from a broker to trade financial assets, amplifying both potential profits and potential losses", polish: "handel na marginesie - Handel na marginesie polega na pożyczaniu pieniędzy od brokera w celu handlu aktywami finansowymi, co zwiększa zarówno potencjalne zyski, jak i potencjalne straty."},
    {english: "capital gain tax - Capital gain tax is the tax levied on the profit from the sale of an asset, such as stocks, bonds, or real estate", polish: "podatek od zysków kapitałowych - Podatek od zysków kapitałowych to podatek pobierany od zysku uzyskanego ze sprzedaży aktywa, takiego jak akcje, obligacje lub nieruchomości."},
    {english: "compound interest - Compound interest is the interest on a loan or deposit that is calculated based on both the initial principal and the accumulated interest from previous periods", polish: "odsetki składane - Odsetki składane to odsetki od pożyczki lub depozytu, które są obliczane na podstawie zarówno początkowego kapitału, jak i nagromadzonych odsetek z poprzednich okresów."},
    {english: "dividend yield - Dividend yield is the ratio of a company's annual dividend payment compared to its stock price", polish: "stopa dywidendy - Stopa dywidendy to stosunek rocznej wypłaty dywidendy firmy do ceny jej akcji."},
    {english: "fund manager - A fund manager is an individual or firm responsible for managing a mutual fund or other investment portfolio", polish: "zarządca funduszu - Zarządca funduszu to osoba lub firma odpowiedzialna za zarządzanie funduszem inwestycyjnym lub innym portfelem inwestycyjnym."},
    {english: "fundamental analysis - Fundamental analysis involves evaluating a company’s financial health and overall performance by reviewing financial statements, market conditions, and management", polish: "analiza fundamentalna - Analiza fundamentalna polega na ocenie kondycji finansowej firmy i ogólnych wyników poprzez przeglądanie sprawozdań finansowych, warunków rynkowych i zarządzania."},
    {english: "capital structure - Capital structure refers to the way a company finances its operations through a combination of debt and equity", polish: "struktura kapitałowa - Struktura kapitałowa odnosi się do sposobu finansowania działalności firmy za pomocą kombinacji długu i kapitału własnego."},
    {english: "liquidity - Liquidity refers to how easily an asset can be converted into cash without affecting its market price", polish: "płynność - Płynność odnosi się do tego, jak łatwo aktywo może zostać przekształcone w gotówkę bez wpływu na jego cenę rynkową."},
    {english: "beta - Beta measures the volatility of an asset or portfolio in relation to the overall market", polish: "beta - Beta mierzy zmienność aktywa lub portfela w odniesieniu do ogólnego rynku."},
    {english: "risk tolerance - Risk tolerance is the degree of variability in investment returns that an individual is willing to withstand", polish: "tolerancja ryzyka - Tolerancja ryzyka to stopień zmienności w zwrotach z inwestycji, którymi osoba jest gotowa się zająć."},
    {english: "portfolio diversification - Portfolio diversification is the practice of spreading investments across various asset classes to reduce risk", polish: "dywersyfikacja portfela - Dywersyfikacja portfela to praktyka rozpraszania inwestycji na różne klasy aktywów w celu zmniejszenia ryzyka."},
    {english: "economic moat - An economic moat is a competitive advantage that allows a company to protect its profits from competitors", polish: "rowek gospodarczy - Rowek gospodarczy to przewaga konkurencyjna, która pozwala firmie chronić swoje zyski przed konkurencją."},
    {english: "short selling - Short selling is the practice of selling a security that the seller does not own, with the intention of buying it back later at a lower price", polish: "krótką sprzedaż - Krótką sprzedaż to praktyka sprzedaży papieru wartościowego, którego sprzedawca nie posiada, z zamiarem odkupu go później po niższej cenie."},
    {english: "market capitalization - Market capitalization is the total value of a company's outstanding shares of stock, calculated by multiplying the share price by the number of shares", polish: "kapitalizacja rynkowa - Kapitalizacja rynkowa to całkowita wartość akcji firmy na rynku, obliczana przez pomnożenie ceny akcji przez liczbę akcji."},
    {english: "tax loss harvesting - Tax loss harvesting is a strategy used to offset capital gains by selling investments that have lost value", polish: "pozyskiwanie strat podatkowych - Pozyskiwanie strat podatkowych to strategia wykorzystywania strat kapitałowych przez sprzedaż inwestycji, które straciły na wartości."},
    {english: "municipal bond - A municipal bond is a debt security issued by a local government or its agencies to raise capital", polish: "obligacja komunalna - Obligacja komunalna to papier dłużny emitowany przez lokalny rząd lub jego agencje w celu pozyskania kapitału."},
    {english: "correlation - Correlation refers to the relationship between two assets or markets, indicating how they move in relation to each other", polish: "korelacja - Korelacja odnosi się do zależności między dwoma aktywami lub rynkami, wskazując, jak poruszają się one względem siebie."},
    {english: "leveraged buyout (LBO) - A leveraged buyout is the acquisition of a company using a significant amount of borrowed money to meet the cost of acquisition", polish: "wykup lewarowany (LBO) - Wykup lewarowany to przejęcie firmy przy użyciu znacznej ilości pożyczonych pieniędzy na pokrycie kosztu przejęcia."},
    {english: "stock split - A stock split is an action taken by a company to divide its existing shares into multiple new shares to lower the trading price of each share", polish: "podział akcji - Podział akcji to działanie podejmowane przez firmę w celu podzielenia swoich istniejących akcji na wiele nowych akcji, aby obniżyć cenę handlową każdej akcji."},
    {english: "asset allocation - Asset allocation is the process of dividing investments among different asset categories such as stocks, bonds, and cash", polish: "alokacja aktywów - Alokacja aktywów to proces dzielenia inwestycji między różne kategorie aktywów, takie jak akcje, obligacje i gotówka."},
    {english: "securities - Securities are tradable financial assets, including stocks, bonds, and other investment instruments", polish: "papiery wartościowe - Papiery wartościowe to tradable aktywa finansowe, takie jak akcje, obligacje i inne instrumenty inwestycyjne."},
    {english: "initial public offering (IPO) - An IPO is the first sale of a company's shares to the public, which helps the company raise capital", polish: "pierwsza oferta publiczna (IPO) - IPO to pierwsza sprzedaż akcji firmy na rynku publicznym, która pomaga firmie pozyskać kapitał."},
    {english: "diversified portfolio - A diversified portfolio is one that contains different types of investments to minimize risk", polish: "dywersyfikowany portfel - Dywersyfikowany portfel to taki, który zawiera różne rodzaje inwestycji w celu zminimalizowania ryzyka."},
    {english: "interest rate risk - Interest rate risk refers to the risk that changes in interest rates will negatively affect the value of investments", polish: "ryzyko stopy procentowej - Ryzyko stopy procentowej odnosi się do ryzyka, że zmiany stóp procentowych negatywnie wpłyną na wartość inwestycji."},
    {english: "hedging - Hedging is a strategy used to offset potential losses in investments by taking an opposite position in a related asset", polish: "hedging - Hedging to strategia stosowana w celu zrekompensowania potencjalnych strat w inwestycjach poprzez przyjęcie przeciwnej pozycji w powiązanym aktywie."},
    {english: "bull market - A bull market is a market in which prices are rising or are expected to rise", polish: "rynek byka - Rynek byka to rynek, na którym ceny rosną lub oczekuje się, że będą rosły."},
    {english: "bear market - A bear market is a market in which prices are falling or are expected to fall", polish: "rynek niedźwiedzia - Rynek niedźwiedzia to rynek, na którym ceny spadają lub oczekuje się, że będą spadały."},
    {english: "capital gain - A capital gain is the profit made from the sale of an asset, such as stocks or real estate, at a higher price than its purchase price", polish: "zysk kapitałowy - Zysk kapitałowy to zysk uzyskany ze sprzedaży aktywa, takiego jak akcje lub nieruchomości, po wyższej cenie niż cena zakupu."},
    {english: "capital loss - A capital loss is the loss incurred when the value of an asset falls below its purchase price", polish: "strata kapitałowa - Strata kapitałowa to strata poniesiona, gdy wartość aktywa spada poniżej jego ceny zakupu."},
    {english: "dividend yield - Dividend yield is a financial ratio that shows how much income an investor can expect to receive from a dividend as a percentage of the investment", polish: "stopa dywidendy - Stopa dywidendy to wskaźnik finansowy, który pokazuje, ile dochodu inwestor może oczekiwać od dywidendy jako procent inwestycji."},
    {english: "growth stock - A growth stock is a share in a company that is expected to grow at an above-average rate compared to other companies in the market", polish: "akcje wzrostowe - Akcje wzrostowe to akcje w firmie, która ma oczekiwaną wyższą stopę wzrostu niż inne firmy na rynku."},
    {english: "value stock - A value stock is a stock that is trading for less than its intrinsic value, often based on fundamental analysis", polish: "akcje wartościowe - Akcje wartościowe to akcje, które są notowane poniżej swojej wewnętrznej wartości, często na podstawie analizy fundamentalnej."},
    {english: "fixed income - Fixed income refers to investments that provide regular income payments, such as bonds or preferred stocks", polish: "dochód stały - Dochód stały odnosi się do inwestycji, które zapewniają regularne płatności dochodowe, takie jak obligacje lub akcje uprzywilejowane."},
    {english: "inflation risk - Inflation risk is the risk that inflation will erode the purchasing power of money or reduce the real value of returns", polish: "ryzyko inflacji - Ryzyko inflacji to ryzyko, że inflacja zmniejszy siłę nabywczą pieniądza lub obniży rzeczywistą wartość zwrotów."},
    {english: "yield curve - The yield curve is a graph that shows the relationship between bond yields and their maturities", polish: "krzywa dochodowości - Krzywa dochodowości to wykres, który pokazuje zależność między rentownościami obligacji a ich terminami wykupu."},
    {english: "coupon rate - The coupon rate is the interest rate paid by a bond issuer on the bond's face value", polish: "stopa kuponowa - Stopa kuponowa to stopa procentowa wypłacana przez emitenta obligacji na wartości nominalnej obligacji."},
    {english: "Treasury bond - A Treasury bond is a long-term debt security issued by the U.S. government", polish: "obligacja skarbowa - Obligacja skarbowa to długoterminowy papier dłużny emitowany przez rząd Stanów Zjednoczonych."},
    {english: "municipal bond - A municipal bond is a debt security issued by a local government to finance public projects", polish: "obligacja komunalna - Obligacja komunalna to papier dłużny emitowany przez lokalny rząd w celu finansowania projektów publicznych."},
    {english: "foreign exchange - Foreign exchange is the market where currencies are traded", polish: "rynek walutowy - Rynek walutowy to rynek, na którym handluje się walutami."},
    {english: "currency risk - Currency risk is the risk of losing value due to fluctuations in exchange rates between currencies", polish: "ryzyko walutowe - Ryzyko walutowe to ryzyko utraty wartości w wyniku wahań kursów wymiany między walutami."},
    {english: "interest rate risk - Interest rate risk refers to the potential for changes in interest rates to negatively affect the value of an investment", polish: "ryzyko stopy procentowej - Ryzyko stopy procentowej odnosi się do potencjalnych zmian stóp procentowych, które mogą negatywnie wpłynąć na wartość inwestycji."},
    {english: "commodity - A commodity is a basic good used in commerce that is interchangeable with other goods of the same type", polish: "towar - Towar to podstawowy produkt używany w handlu, który jest wymienny z innymi produktami tego samego typu."},
    {english: "real estate investment - Real estate investment refers to the purchase, ownership, management, rental, and/or sale of real estate for profit", polish: "inwestycje w nieruchomości - Inwestycje w nieruchomości odnoszą się do zakupu, posiadania, zarządzania, wynajmu i/lub sprzedaży nieruchomości w celu osiągnięcia zysku."},
    {english: "crowdfunding - Crowdfunding is a way of raising capital through the collective effort of a large number of individuals", polish: "crowdfunding - Crowdfunding to sposób pozyskiwania kapitału dzięki zbiorowemu wysiłkowi dużej liczby osób."},
    {english: "angel investor - An angel investor is an individual who provides financial support to early-stage businesses in exchange for ownership equity or debt", polish: "anioł biznesu - Anioł biznesu to osoba, która zapewnia wsparcie finansowe dla firm na wczesnym etapie rozwoju w zamian za udziały w firmie lub dług."},
    {english: "venture capital - Venture capital is funding provided to early-stage companies with high growth potential in exchange for equity or debt", polish: "kapitał venture - Kapitał venture to finansowanie udzielane firmom na wczesnym etapie rozwoju, które mają duży potencjał wzrostu, w zamian za udziały lub dług."},
    {english: "private equity - Private equity refers to investment funds that directly invest in private companies or buy out public companies to delist them", polish: "kapitał prywatny - Kapitał prywatny odnosi się do funduszy inwestycyjnych, które bezpośrednio inwestują w prywatne firmy lub wykupują firmy publiczne, aby je zderegulować."},
    {english: "business valuation - Business valuation is the process of determining the economic value of a business or company", polish: "wycena firmy - Wycena firmy to proces określania wartości ekonomicznej firmy lub przedsiębiorstwa."},
    {english: "initial coin offering (ICO) - An ICO is a type of fundraising mechanism in which new cryptocurrency projects sell their underlying tokens in exchange for capital", polish: "pierwsza oferta monet (ICO) - ICO to rodzaj mechanizmu zbierania funduszy, w którym nowe projekty kryptowalutowe sprzedają swoje tokeny w zamian za kapitał."},
    {english: "blockchain - Blockchain is a decentralized digital ledger used to record transactions across many computers", polish: "blockchain - Blockchain to zdecentralizowany cyfrowy rejestr służący do rejestrowania transakcji w wielu komputerach."},
    {english: "cryptocurrency - Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates independently of a central authority", polish: "kryptowaluta - Kryptowaluta to cyfrowa lub wirtualna waluta, która korzysta z kryptografii w celu zapewnienia bezpieczeństwa i działa niezależnie od centralnego organu."},
    {english: "digital asset - A digital asset is any form of digital content that has value, such as cryptocurrencies, digital art, or other online assets", polish: "aktywa cyfrowe - Aktywa cyfrowe to wszelkie formy treści cyfrowej, które mają wartość, takie jak kryptowaluty, sztuka cyfrowa czy inne aktywa internetowe."},
    {english: "alternative investment - An alternative investment is a financial asset that does not fall into one of the conventional categories of stocks, bonds, or cash", polish: "inwestycje alternatywne - Inwestycje alternatywne to aktywa finansowe, które nie mieszczą się w jednej z tradycyjnych kategorii akcji, obligacji czy gotówki."},
    {english: "index fund - An index fund is a type of mutual fund designed to replicate the performance of a specific index, such as the S&P 500", polish: "fundusz indeksowy - Fundusz indeksowy to rodzaj funduszu inwestycyjnego, którego celem jest odwzorowanie wyników określonego indeksu, takiego jak S&P 500."},
    {english: "ETFs (Exchange-Traded Funds) - ETFs are investment funds that are traded on stock exchanges, much like stocks", polish: "fundusze ETF - Fundusze ETF to fundusze inwestycyjne notowane na giełdach papierów wartościowych, podobnie jak akcje."},
    {english: "real estate investment trust (REIT) - A REIT is a company that owns, operates, or finances real estate that generates income", polish: "fundusz inwestycyjny nieruchomości (REIT) - REIT to firma, która posiada, zarządza lub finansuje nieruchomości generujące dochód."},
    {english: "peer-to-peer lending - Peer-to-peer lending is the practice of lending money to individuals or businesses through online services that match lenders with borrowers", polish: "pożyczki peer-to-peer - Pożyczki peer-to-peer to praktyka pożyczania pieniędzy osobom lub firmom za pośrednictwem internetowych usług, które łączą pożyczkodawców z pożyczkobiorcami."},
    {english: "crowd investing - Crowd investing involves raising small amounts of capital from a large number of people, typically through an online platform", polish: "crowd investing - Crowd investing to pozyskiwanie małych kwot kapitału od dużej liczby osób, zazwyczaj za pośrednictwem platformy internetowej."},
    {english: "venture capital funding - Venture capital funding refers to the money provided by investors to startup firms or small businesses with strong growth potential", polish: "finansowanie kapitałem venture - Finansowanie kapitałem venture to środki dostarczane przez inwestorów do firm startupowych lub małych firm o dużym potencjale wzrostu."},
    {english: "initial public offering (IPO) - An IPO is the process by which a private company offers its shares to the public for the first time", polish: "pierwsza oferta publiczna (IPO) - IPO to proces, w którym prywatna firma po raz pierwszy oferuje swoje akcje publiczności."},
    {english: "secondary offering - A secondary offering is the sale of new or closely held shares by a company that has already made its initial public offering", polish: "wtórna oferta - Wtórna oferta to sprzedaż nowych lub ściśle posiadanych akcji przez firmę, która już przeprowadziła swoją pierwszą ofertę publiczną."},
    {english: "angel funding - Angel funding refers to the financial support provided by wealthy individuals (angels) to startup companies, usually in exchange for equity", polish: "finansowanie aniołów - Finansowanie aniołów odnosi się do wsparcia finansowego udzielonego przez bogatych indywidualnych inwestorów (aniołów) firmom startupowym, zazwyczaj w zamian za udziały."},
    {english: "corporate bond - A corporate bond is a debt security issued by a corporation to raise capital, with a promise to repay the principal amount along with interest", polish: "obligacja korporacyjna - Obligacja korporacyjna to papier dłużny emitowany przez korporację w celu pozyskania kapitału, z obietnicą spłaty kwoty głównej wraz z odsetkami."},
    {english: "municipal bond - A municipal bond is a debt security issued by a state, municipality, or county to finance public projects", polish: "obligacja komunalna - Obligacja komunalna to papier dłużny emitowany przez państwo, miasto lub powiat w celu finansowania projektów publicznych."},
    {english: "investment grade - Investment grade is a rating that indicates that a bond is considered a relatively low risk for investors", polish: "poziom inwestycyjny - Poziom inwestycyjny to ocena wskazująca, że obligacja jest uważana za relatywnie niskie ryzyko dla inwestorów."},
    {english: "high-yield bond - A high-yield bond is a bond that carries a higher level of risk and pays a higher interest rate than investment-grade bonds", polish: "obligacja o wysokim dochodzie - Obligacja o wysokim dochodzie to obligacja, która niesie ze sobą wyższy poziom ryzyka i oferuje wyższy oprocentowanie niż obligacje o poziomie inwestycyjnym."},
    {english: "fixed interest - Fixed interest refers to an investment that pays a constant interest rate for the duration of the investment", polish: "stałe oprocentowanie - Stałe oprocentowanie odnosi się do inwestycji, która płaci stałą stopę procentową przez cały okres trwania inwestycji."},
    {english: "floating interest - Floating interest is an interest rate that moves up and down with market interest rates", polish: "zmienne oprocentowanie - Zmienne oprocentowanie to stopa procentowa, która waha się w zależności od rynkowych stóp procentowych."},
    {english: "asset allocation - Asset allocation is the process of dividing investments among different asset categories, such as stocks, bonds, and real estate", polish: "alokacja aktywów - Alokacja aktywów to proces dzielenia inwestycji pomiędzy różne kategorie aktywów, takie jak akcje, obligacje i nieruchomości."},
    {english: "portfolio diversification - Portfolio diversification is the practice of spreading investments across various assets to reduce risk", polish: "dywersyfikacja portfela - Dywersyfikacja portfela to praktyka rozpraszania inwestycji w różnych aktywach, aby zredukować ryzyko."},
    {english: "leverage - Leverage is the use of borrowed capital to increase the potential return on an investment", polish: "dźwignia finansowa - Dźwignia finansowa to wykorzystanie pożyczonych środków w celu zwiększenia potencjalnego zwrotu z inwestycji."},
    {english: "margin trading - Margin trading is the practice of borrowing funds from a broker to trade a financial asset, using the asset itself as collateral", polish: "handel na marginesie - Handel na marginesie to praktyka pożyczania środków od brokera w celu handlu aktywem finansowym, wykorzystując samo aktywo jako zabezpieczenie."},
    {english: "short selling - Short selling is the practice of selling a security that the seller does not own, with the intention of buying it back later at a lower price", polish: "sprzedaż krótka - Sprzedaż krótka to praktyka sprzedaży papieru wartościowego, którego sprzedawca nie posiada, z zamiarem odkupienia go później po niższej cenie."},
    {english: "real estate bubble - A real estate bubble is a situation where the prices of real estate rise to unsustainable levels and then crash", polish: "bańka na rynku nieruchomości - Bańka na rynku nieruchomości to sytuacja, w której ceny nieruchomości rosną do poziomów nie do utrzymania, a następnie spadają."},
    {english: "forex trading - Forex trading is the act of buying and selling currencies on the foreign exchange market", polish: "handel walutowy - Handel walutowy to akt kupna i sprzedaży walut na rynku wymiany walut."},
    {english: "hedging - Hedging is a strategy used to reduce or offset the risk of adverse price movements in an asset", polish: "hedging - Hedging to strategia stosowana w celu zredukowania lub zrównoważenia ryzyka niekorzystnych ruchów cenowych w aktywach."},
    {english: "currency swap - A currency swap is a financial agreement in which two parties exchange cash flows in different currencies", polish: "swap walutowy - Swap walutowy to umowa finansowa, w której dwie strony wymieniają przepływy gotówkowe w różnych walutach."},
    {english: "capital gains - Capital gains are the profits realized from the sale of an asset, such as stocks, bonds, or real estate", polish: "zyski kapitałowe - Zyski kapitałowe to zyski uzyskane ze sprzedaży aktywów, takich jak akcje, obligacje czy nieruchomości."},
    {english: "capital loss - Capital loss occurs when the selling price of an asset is lower than its purchase price", polish: "strata kapitałowa - Strata kapitałowa występuje, gdy cena sprzedaży aktywa jest niższa od ceny zakupu."},
    {english: "dividend - A dividend is a payment made by a corporation to its shareholders, usually in the form of cash or additional shares", polish: "dywidenda - Dywidenda to wypłata dokonywana przez korporację na rzecz swoich akcjonariuszy, zazwyczaj w formie gotówki lub dodatkowych akcji."},
    {english: "yield - Yield is the income return on an investment, expressed as a percentage of the investment’s cost or market value", polish: "dochód - Dochód to zwrot z inwestycji, wyrażony jako procent kosztu lub wartości rynkowej inwestycji."},
    {english: "beta - Beta is a measure of a stock’s volatility in relation to the overall market", polish: "beta - Beta to miara zmienności akcji w stosunku do ogólnego rynku."},
    {english: "alpha - Alpha is a measure of an investment's performance compared to a market index or benchmark", polish: "alfa - Alfa to miara wydajności inwestycji w porównaniu do indeksu rynkowego lub punktu odniesienia."},
    {english: "liquidity - Liquidity refers to how easily an asset can be converted into cash without affecting its market price", polish: "płynność - Płynność odnosi się do łatwości, z jaką aktywo może zostać zamienione na gotówkę, bez wpływu na jego cenę rynkową."},
    {english: "investment horizon - The investment horizon is the length of time an investor expects to hold an investment before taking the money out", polish: "horyzont inwestycyjny - Horyzont inwestycyjny to okres, przez który inwestor planuje utrzymywać inwestycję przed jej sprzedażą."},
    {english: "systematic risk - Systematic risk refers to the risk inherent in the entire market or a particular segment of the market", polish: "ryzyko systematyczne - Ryzyko systematyczne odnosi się do ryzyka wrodzonego całemu rynkowi lub określonemu segmentowi rynku."},
    {english: "unsystematic risk - Unsystematic risk is the risk that is unique to a particular company or industry", polish: "ryzyko niesystematyczne - Ryzyko niesystematyczne to ryzyko, które jest unikalne dla konkretnej firmy lub branży."},
    {english: "volatility - Volatility is the degree of variation in the price of an asset over time", polish: "zmienność - Zmienność to stopień wahań ceny aktywa w czasie."},
    {english: "securities - Securities are tradable financial assets such as stocks, bonds, and options", polish: "papiery wartościowe - Papiery wartościowe to aktywa finansowe, które mogą być przedmiotem obrotu, takie jak akcje, obligacje czy opcje."},
    {english: "derivatives - Derivatives are financial instruments whose value is derived from the value of an underlying asset, such as a stock or bond", polish: "instrumenty pochodne - Instrumenty pochodne to instrumenty finansowe, których wartość zależy od wartości bazowego aktywa, takiego jak akcje czy obligacje."},
    {english: "call option - A call option gives the holder the right, but not the obligation, to buy an asset at a specified price within a certain period", polish: "opcja kupna - Opcja kupna daje jej posiadaczowi prawo, ale nie obowiązek, do zakupu aktywa po określonej cenie w określonym okresie."},
    {english: "put option - A put option gives the holder the right, but not the obligation, to sell an asset at a specified price within a certain period", polish: "opcja sprzedaży - Opcja sprzedaży daje jej posiadaczowi prawo, ale nie obowiązek, do sprzedaży aktywa po określonej cenie w określonym okresie."},
    {english: "options trading - Options trading is the practice of buying and selling options contracts on financial markets", polish: "handel opcjami - Handel opcjami to praktyka kupna i sprzedaży kontraktów opcyjnych na rynkach finansowych."},
    {english: "futures contract - A futures contract is a legal agreement to buy or sell an asset at a predetermined price at a specified time in the future", polish: "kontrakt futures - Kontrakt futures to umowa prawna na zakup lub sprzedaż aktywa po ustalonej cenie w określonym czasie w przyszłości."},
    {english: "forward contract - A forward contract is a customized contract between two parties to buy or sell an asset at a specific future date for a price that is agreed upon today", polish: "kontrakt terminowy - Kontrakt terminowy to spersonalizowana umowa między dwiema stronami na zakup lub sprzedaż aktywa w określonym dniu w przyszłości po cenie uzgodnionej dzisiaj."},
    {english: "leverage ratio - The leverage ratio measures the proportion of a company’s capital that is financed through debt", polish: "wskaźnik dźwigni - Wskaźnik dźwigni mierzy proporcję kapitału firmy finansowanego za pomocą zadłużenia."}

];

let selectedWords = [];
let currentIndex = 0;
let isEnglishToPolish = true;
let score = 0;
let answerGiven = false; // Track if an answer has been given
let isSpeakingEnabled = false; // Track if speaking is enabled

// DOM Elements
const container = document.getElementById("containerAnswer");
const wordDisplay = document.getElementById('wordDisplay');
const userInput = document.getElementById('userInput');
const submitBtn = document.getElementById('submitBtn');
const result = document.getElementById('result');
const nextBtn = document.getElementById('nextBtn');
const optionsContainer = document.getElementById('optionsContainer');
const translationDisplay = document.getElementById('translationDisplay');
const toggleTranslationBtn = document.getElementById('toggleTranslationBtn');
const switchLanguageBtn = document.getElementById('switchLanguageBtn');
const toggleSpeakBtn = document.getElementById('toggleSpeakBtn'); // New button for toggling speaking

// Initialization
function init() {
    selectedWords = words.slice(); // Select all words
    currentIndex = 0;
    translationDisplay.style.display = 'none'; // Hide translation by default
    displayWord(); // Display the first word
}

// Displaying the word
function displayWord() {
    if (selectedWords.length === 0) {
        result.textContent = "Nie wybrano słówek do nauki!";
        return;
    }

    const currentWord = isEnglishToPolish ? selectedWords[currentIndex].english : selectedWords[currentIndex].polish;
    wordDisplay.textContent = currentWord;
    generateOptions(isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english);
    userInput.value = '';
    result.textContent = '';

    // Speak the word only if speaking is enabled
    if (isSpeakingEnabled) {
        speakWord(); // Automatically speak the displayed word
    }

    // Update the translation display
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    translationDisplay.textContent = correctTranslation; // Show the current translation
}

// Function to speak the current word
function speakWord() {
    const currentWord = wordDisplay.textContent; // Read the word from the wordDisplay div
    const utterance = new SpeechSynthesisUtterance(currentWord);
    utterance.lang = isEnglishToPolish ? 'en-US' : 'pl-PL'; // Set language
    window.speechSynthesis.speak(utterance);
}

// Select words
document.querySelectorAll('.word-select-btn').forEach(button => {
    button.addEventListener('click', () => {
        const count = button.getAttribute('data-count');
        if (count === 'all') {
            selectedWords = words.slice(); // Select all words
        } else {
            const num = Math.min(parseInt(count), words.length);
            selectedWords = getRandomWords(words, num); // Select random words
        }
        currentIndex = 0;
        result.textContent = `Wybrano ${selectedWords.length} słówek do nauki.`; // Display information
        setTimeout(displayWord, 2000); // Display the first word
    });
});

// Random word selection function
function getRandomWords(sourceArray, count) {
    const shuffled = sourceArray.slice().sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
}

// Generating options for selection
function generateOptions(correctAnswer) {
    optionsContainer.innerHTML = ''; // Clear previous options

    const options = [correctAnswer];
    while (options.length < 4) {
        const randomWord = selectedWords[Math.floor(Math.random() * selectedWords.length)];
        if (isEnglishToPolish) {
            if (!options.includes(randomWord.polish)) options.push(randomWord.polish);
        } else {
            if (!options.includes(randomWord.english)) options.push(randomWord.english);
        }
    }

    shuffle(options); // Shuffle options

    options.forEach(option => {
        const btn = document.createElement('button');
        btn.textContent = option;
        btn.className = 'option-btn';
        btn.addEventListener('click', () => checkAnswer(option, correctAnswer));
        optionsContainer.appendChild(btn);
    });
}

// Check the answer
function checkAnswer(selected, correct) {
    if (answerGiven) return; // If an answer has already been given, do nothing

    const isCorrect = selected === correct || userInput.value.trim().toLowerCase() === correct.toLowerCase();
    
    if (isCorrect) {
        result.textContent = "Dobrze!";
        score++; // Increase score
        container.classList.add('bounce'); // Bounce animation

        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-yellow'));
        toggleTranslationBtn.classList.add("BtnGreen");
        switchLanguageBtn.classList.add("BtnGreen");
        nextBtn.classList.add("nextBtnGreen");
        submitBtn.classList.add("submitBtnGreen");
        toggleSpeakBtn.classList.add("BtnGreen");

        // Wait 2 seconds, then show the next word
        setTimeout(() => {
            currentIndex = (currentIndex + 1) % selectedWords.length; // Move to the next word
            answerGiven = false; // Reset state
            displayWord(); // Display new word
        }, 600);

        setTimeout(() => {
            container.classList.remove('bounce');
            buttons.forEach(button => button.classList.remove('btn-yellow'));
            toggleTranslationBtn.classList.remove("BtnGreen");
            switchLanguageBtn.classList.remove("BtnGreen");
            nextBtn.classList.remove("nextBtnGreen");
            submitBtn.classList.remove("submitBtnGreen");
            toggleSpeakBtn.classList.remove("BtnGreen");
        }, 600);
    } else {
        result.textContent = `Źle! Poprawne tłumaczenie to: ${correct}`;
        container.classList.add('shake'); // Shake animation

        const buttons = document.querySelectorAll('.option-btn');
        buttons.forEach(button => button.classList.add('btn-red'));
        toggleTranslationBtn.classList.add("btn-red");
        switchLanguageBtn.classList.add("btn-red");
        nextBtn.classList.add("nextBtnRed");
        submitBtn.classList.add("submitBtnRed");
        toggleSpeakBtn.classList.add("btn-red");

        setTimeout(() => {
            container.classList.remove('shake');
            buttons.forEach(button => button.classList.remove('btn-red'));
            toggleTranslationBtn.classList.remove("btn-red");
            switchLanguageBtn.classList.remove("btn-red");
            nextBtn.classList.remove("nextBtnRed");
            submitBtn.classList.remove("submitBtnRed");
            toggleSpeakBtn.classList.remove("btn-red");
        }, 600);
    }

    answerGiven = true; // Mark that an answer has been given
}

// Handle submit button click
submitBtn.addEventListener('click', () => {
    const correctTranslation = isEnglishToPolish ? selectedWords[currentIndex].polish : selectedWords[currentIndex].english;
    checkAnswer(null, correctTranslation);
});

// Handle next button click
nextBtn.addEventListener('click', () => {
    if (!answerGiven) return; // If an answer hasn't been given, do nothing
    currentIndex = (currentIndex + 1) % selectedWords.length; // Move to the next word (cyclically)
    answerGiven = false; // Reset state
    displayWord();
});

// Toggle translation visibility
toggleTranslationBtn.addEventListener('click', () => {
    if (translationDisplay.style.display === 'none' || !translationDisplay.style.display) {
        translationDisplay.style.display = 'block'; // Show the translation
    } else {
        translationDisplay.style.display = 'none'; // Hide the translation
    }
});

// Switch language
switchLanguageBtn.addEventListener('click', () => {
    isEnglishToPolish = !isEnglishToPolish; // Change language direction
    displayWord(); // Refresh displayed word
});

// Toggle speaking
toggleSpeakBtn.addEventListener('click', () => {
    isSpeakingEnabled = !isSpeakingEnabled; // Toggle speaking on/off
    toggleSpeakBtn.innerHTML = isSpeakingEnabled ? '<i class="fa-solid fa-volume-low"></i>' : '<i class="fa-solid fa-volume-low"></i>'; // Update button text
});

// Initialization
init();

// Shuffle function
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

// Toggle word selection container
const toggleButton = document.getElementById('hideButton');
const myDiv = document.getElementById('wordSelectContainer');

toggleButton.addEventListener('click', () => {
    myDiv.style.display = myDiv.style.display === 'none' ? 'block' : 'none'; // Toggle visibility
});